### ISSUE TITLE
Add player watchlist support

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#1]
ADK runs a player watchlist for suspected hackers, those on the borderline between questionable and obvious. Add addition and checking for players on that watchlist into the plugin.

**Comment by Prophet731** [comment]
Man this is old.

**Comment by ColColonCleaner** [comment]
Yup, reviving the dead and dying.

**Comment by Prophet731** [comment]
Will be added in BFACP Version 3.0

https://gitlab.com/Prophet731/battlefield-admin-control-panel/issues/13
