### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by dangerBEclose** [AdKats/AdKats#1010]
The download link for the plugin is not working

**Comment by ColColonCleaner** [comment]
Which download link are you trying to use?

We have the latest version on myrcon.net and here on github.com.
And an older version on sourceforge.

https://myrcon.net/files/file/30-advanced-in-game-admin-and-ban-enforcer-adkats/
https://github.com/AdKats/AdKats/releases
https://sourceforge.net/projects/adkats/files/

**Comment by dangerBEclose** [comment]
Under user manual there is a line `The latest universal version of XpKiller's Stat Logger can be downloaded from here: Procon Chat, GUID, Stats and Mapstats Logger` redirecting to [https://myrcon.net/index.php?/topic/11-chat-guid-stats-and-mapstats-logger-1003-by-xpkiller/](https://myrcon.net/index.php?/topic/11-chat-guid-stats-and-mapstats-logger-1003-by-xpkiller/) wish does not work. Thanks for the info

**Comment by ColColonCleaner** [comment]
@dangerBEclose Ah yes, that's for the prerequisite plugin.
That link is here: https://myrcon.net/topic/162-chat-guid-stats-and-mapstats-logger-1003/
I can update it in the documentation. Thanks.
