### ISSUE TITLE
Add option to ban enforcer to not delete records after import in adkats

### ISSUE THREAD

**Issue by xtonystarkx** [AdKats/AdKats#1013]
Some game server crashers can only be stoped on EA server using banlist.txt
But other ban can store on adkats

**Comment by liec0dez** [comment]
I second this issue. BanEnforcer is too slow to prevent accounts with corrupted stats from crashing servers.

**Comment by xtonystarkx** [comment]
Workaround program
https://github.com/ResupinePuma/BF_AntiCrasher
https://github.com/ResupinePuma/BF_AntiCrasher/releases/tag/start
