### ISSUE TITLE
Ban Management- GorillaYeti

### ISSUE THREAD

**Issue by GorillaYeti** [AdKats/AdKats#1015]
Good evening,
I was banned on multiple BF4 servers due to: HSK F2000. The server uses AdKat to my knowledge. Here is my BF4DB profile: https://bf4db.com/player/1032099427
I own a server which is made for completing Phantom assighments and dog tag searching. I hate to admit but I was stat padding in order to complete the assignments which I had no idea it was against EA TOS which I now know for future references, as it won't happen again. Here is one the matches which was "thought to be" of me "hacking": https://battlelog.battlefield.com/bf4/battlereport/show/1/1251686206975665024/1032099427/
as you can see it is on my own server, and if able to you can even spectate the game. I do apologize about this behavior.
Thank you

**Comment by ColColonCleaner** [comment]
Bans made through AdKats are done on an individual server basis, I don't control a master list of bans on my end. Servers can set the level for each ban type, so you'll need to contact the admins of the servers you want to join to be unbanned/whitelisted. I would suggest playing with the f2000 some more normally to bring your average stats down if you were boosting with it.

**Comment by GorillaYeti** [comment]
> Bans made through AdKats are done on an individual server basis, I don't control a master list of bans on my end. Servers can set the level for each ban type, so you'll need to contact the admins of the servers you want to join to be unbanned/whitelisted. I would suggest playing with the f2000 some more normally to bring your average stats down if you were boosting with it.

Will do, thank you.
