### ISSUE TITLE
Banned Tag problem

### ISSUE THREAD

**Issue by JJHACKER** [AdKats/AdKats#1016]
Banned Tag is case sensitive , must ignore case...
 if (_BannedTags.Contains(aPlayer.player_clanTag) && !String.IsNullOrEmpty(aPlayer.player_clanTag))

==
 if (_BannedTags.Contains(aPlayer.player_clanTag, StringComparer.OrdinalIgnoreCase) &&!String.IsNullOrEmpty(aPlayer.player_clanTag))

**Comment by ColColonCleaner** [comment]
If you want to change that on your own instance that's fine, but i don't think that pushing it to all instances would be a good idea.

**Comment by JJHACKER** [comment]
Sometime player with change one word , enter server again
example: Clan MARS
now user use: Mars or MARs or ... and enter server

**Comment by ColColonCleaner** [comment]
That's not how the banned tags work. If someone joins with a banned tag it just permabans them and they need to be manually unbanned, even if they change their tag after that point they are still banned. I assume you're talking about multiple different players.
Even adding case-insensitivity to that functionality is easily bypassed, they could just change their tag to MARZ and bypass it. This isn't meant as a catch all, just a convenience.
