### ISSUE TITLE
/pupdate flips between 7.6.0.5 and 7.6.0.3 back and forth

### ISSUE THREAD

**Issue by hit757** [AdKats/AdKats#1018]
If I use /pupdate AdKats downgrades from 7.6.0.5 to 7.6.0.3.
When 7.6.0.3 it says it's old and next /pupdate upgrades it back to 7.6.0.5.
The loop repeats endlessly.

**Comment by ColColonCleaner** [comment]
This should be resolved. We were bad programmers and were fixing things on master without pushing things back down to the test branch.

**Comment by hit757** [comment]
:)
