### ISSUE TITLE
"Feed server reserved slots" and VIP Slot Manager

### ISSUE THREAD

**Issue by redge** [AdKats/AdKats#1023]
Currently AdKats can send new VIP/reserved slots properly in an environment using VIP Slot Manager when players complete challenges, but not in other functions (such as discord/teamspeak player monitors, populator perks, etc). It appears there's already a function that adds reserved slots using VIP Slot Manager first then directly through Adkats' reserved slot management if the plugin call fails. The reserved slot management and/or perks settings should be refactored so these other features can use reserved slots as perks when VIP Slot Manager is present.

**Comment by Hedius** [comment]
The Problem with this one is that AdKats can add VIP slots to VSM by using the built-in VSM commands. However, it is not possible
for AdKats to remove slots from VSM if needed. VSM would need an update.
