### ISSUE TITLE
DPS Automatic Ban [4-FAMAS-206-120-17-58] [perm][AutoAdmin]

### ISSUE THREAD

**Issue by zefirkez** [AdKats/AdKats#1027]

**Comment by zefirkez** [comment]
https://battlelog.battlefield.com/bf4/ru/battlereport/show/1/1328819055660035776/227563764/

**Comment by Hedius** [comment]
Lower your stats. (Shots hit / shots fired).

Or create a new BF4 account.

You did stats padding which against the ToS of BF4. You deserve the ban.

Also: posting here is useless. This is not a support forum and the code works.

**Comment by ColColonCleaner** [comment]
@zefirkez Hedius does not represent the development group behind this plugin, please ignore their comments about whether the ban was deserved.

You will however need to reduce the stats on that weapon to avoid being automatically banned by servers running AdKats. And will need to contact the admins of specific servers where you've already been automatically banned to have those bans lifted. You can also optionally have the admins of those servers whitelist you, then you will be unbanned and new stat-based bans will not be issued against your player. Boosting is not something that the anti-cheat measures in this plugin work around so they can/will cause bans like this. Cheers.

**Comment by zefirkez** [comment]
> @zefirkez Hedius does not represent the development group behind this plugin, please ignore their comments about whether the ban was deserved.
> 
> You will however need to reduce the stats on that weapon to avoid being automatically banned by servers running AdKats. And will need to contact the admins of specific servers where you've already been automatically banned to have those bans lifted. You can also optionally have the admins of those servers whitelist you, then you will be unbanned and new stat-based bans will not be issued against your player. Boosting is not something that the anti-cheat measures in this plugin work around so they can/will cause bans like this. Cheers.

the server admin says that they do not remove the plugin ban! and I need to be banned for the fact that I have damage from FAMAS 200%

**Comment by zefirkez** [comment]
https://forum.xl-games.ru/threads/bf4-metro-zajavka-na-razban-zefirkez.6035/
