### ISSUE TITLE
HSK Automatic Ban

### ISSUE THREAD

**Issue by IordX** [AdKats/AdKats#1028]
Hi
Sniping is not included ? right ?
how about Magnum 44 sniping ? example = https://youtu.be/BpPv4Urlt7s
Contacting because of server admin requested to clarify the automatic ban with script makers , yes I know this is strange request.
played same as youtube example above and game ended with auto ban = Game disconnected: you were kicked by an admin. Stated reason: HSK Automatic Ban [LIVE][6-L22-143-91 [perm][AutoAdmin][Appeal at hardlocker.pl] 
log here = https://battlelog.battlefield.com/bf4/battlereport/show/1/1334258450338950656/984630420
looks like admin think this is impossible or he not qualified enough to judge.

if snipers excluded in HSK Automatic Ban maybe will be good idea to add Magnum44 to white list ? because this is same thing .
let me know what you think, and any advice to the server admin ? 

more examples :
https://youtu.be/NETlpmIM6jU = short example 
https://youtu.be/-I2Fv8y6TKU = full game 90% HSK

**Comment by Prophet731** [comment]
You'll want to dispute this with the server that issued the ban. We cannot do anything here to help.

**Comment by IordX** [comment]
I am contacting here not about dispute .
please read it again , was talking about Magnum44 and white list in the script and comment about it , and about your opinion .
