### ISSUE TITLE
hardcoded reservedSlots developer users that are impossible to remove

### ISSUE THREAD

**Issue by pguridi** [AdKats/AdKats#1032]
There are 2 hard coded developer usernames in AdKats.cs (ColColonCleaner and PhirePhrey) that are impossible to remove from reservedSlots list as they are constantly been added back by AdKats.cs.
I understand that probably this is of no importance for the developers, but as a developer myself I find this been a bad practice that I had to fix in my local deployment, so I'm opening this issue to leave it documented it. 
In case you care, my fork has those entries removed: https://github.com/pguridi/AdKats

Cheers,
Pedro

**Comment by ColColonCleaner** [comment]
Those lines are there to provide myself and PhirePhrey VIP slots on any server running my admin tools as a pittance for the thousands of hours spent in development.
