### ISSUE TITLE
How to disable round events?

### ISSUE THREAD

**Issue by kikibf4** [AdKats/AdKats#1033]
Hey,

I just set up a new server running AdKats. Randomly on some rounds the server is running events which change the server rules automatically. I'd like to disable these, but can't find anything in the documentation. I thought this might be the challenge system, but I already disabled that and it didn't change anything.

Here's what is printed to the chat when this event happens:
```
[14.01.22] AdKats > Tell[5s] > WELCOME TO ROUND EVENT 1! ALL WEAPONS!
[14.01.25] AdKats > Say > ALL WEAPONS! Use !rules for details.
[14.01.28] AdKats > Say > ALL WEAPONS! Use !rules for details.
[14.01.31] AdKats > Say > ALL WEAPONS! Use !rules for details.
[14.01.34] AdKats > Say > ALL WEAPONS! Use !rules for details.
```

**Comment by ColColonCleaner** [comment]
You turned on the experimental tools at some point and then enabled the event system. Turn off the event system.

**Comment by kikibf4** [comment]
I did enable the experimental tools at some point but I also disabled them afterwards, but the round event still occurred. Which setting inside the event automation do I need to change to make sure the events are disabled? Would setting the "Event Duration Rounds" to 0 disable them altogether?

**Comment by ColColonCleaner** [comment]
Turn off 'weekly events' and then set the date of the event to some day far in the future. Few decades from now.

**Comment by kikibf4** [comment]
I changed the event date to 1.1.2050 and the events section instantly started saying "Failed to build setting section." and the console logged this:
```
[16.47.32 30] [AdKats] EXCEPTION-7609-A0-D-RunEventMonitor-StatusMonitor11: [Error running event monitor.][System.OverflowException: Die arithmetische Operation hat einen Überlauf verursacht.
   bei PRoConEvents.AdKats.FetchEstimatedEventRoundNumber()
   bei PRoConEvents.AdKats.RunEventMonitor()]
```
I hope this doesn't break the rest of the plugin? If the events are now broken it's fine by me since I wanted them off anyways but should I do something about this?

**Comment by ColColonCleaner** [comment]
Ah, my mistake, should have been a date in the past not the future, like yesterday. If you're able to get that setting section to load again after rebooting procon do that, otherwise you might get spammed with errors. This shouldn't affect other areas of the plugin.

**Comment by kikibf4** [comment]
The section doesn't load at all anymore even after restarting procon and AdKats. It only throws the error once when starting AdKats and if I re-enable the experimental part of the options, so it's not the worst thing ever. I just hope that the events are now fully disabled, otherwise I'll probably have to ask again here to see what I should do.

**Comment by ColColonCleaner** [comment]
Alright, if you run into more issues down the line we can figure it out.
