### ISSUE TITLE
Restricted Battlelog profiles

### ISSUE THREAD

**Issue by Christianuss** [AdKats/AdKats#1034]
```csharp
if (!String.IsNullOrEmpty(personaResponse))
{
    KickPlayerMessage(aPlayer, "Battlelog info fetch issue. Please re-join.");
    warnMessage += " Player kicked from server.";
}
```

There are players whose Battlelog profiles can't be retrieved because it says they're underage (see [this player](https://battlelog.battlefield.com/bf4/user/EvanTheGreat27/) for example). The restricted profile doesn't contain the user's persona IDs, so AdKats keeps kicking them indefinitely since it can't get their stats like this.

One option to still get their stats would be to find the persona through the search function, since unlike the restricted profile, this does contain the persona IDs:
```
POST /bf4/search/query/
query=EvanTheGreat27
```
Stats can then be retrieved [like normally](https://battlelog.battlefield.com/bf4/soldier/EvanTheGreat27/stats/1453115684/pc/).

**Comment by Hedius** [comment]
Also happens for this profile: https://battlelog.battlefield.com/bf4/user/oloWAV/

Not showing anything at all?

**Comment by Hedius** [comment]
I have made a workaround. Just commenting out the Kick message and returning true. AdKats does work without persona IDs.
Stats fetching, anti cheat etc. does not work for affected players, but at least they can play.
https://github.com/Hedius/E4GLAdKats/commit/d52fcc8edbaee33ab79ee88562a2b0f98b6d86e7

I'm still testing this at the moment.

**Comment by Hedius** [comment]
Successfully tested: https://github.com/AdKats/AdKats/pull/1036 

or use my fork https://github.com/Hedius/E4GLAdKats/tree/master-upstream

**Comment by Prophet731** [comment]
Partially Fixed, still a battlelog problem sadly.
