### ISSUE TITLE
Duplicate chat messages

### ISSUE THREAD

**Issue by Ryckie** [AdKats/AdKats#1042]
Since I switched off the chatlogging from PRoCon CHat, GUID, ... plugin and turned on the AdKats to avoid the spam of commands and so in the chat logs. I noticed that there are sometimes chat messages beinding logged multiple times.
![image](https://user-images.githubusercontent.com/63733138/123487578-783bc000-d60e-11eb-9ce4-cb0dcac5e948.png)
![image](https://user-images.githubusercontent.com/63733138/123487793-eed8bd80-d60e-11eb-85bb-2d64661d33e6.png)

**Comment by Ryckie** [comment]
Please some feedback or solution.

**Comment by Prophet731** [comment]
Little late but make sure the Feed stat logger settings is enabled and make sure to disable the chat log function in the Stats Logger plugin. You shouldn't be getting duplicate messages.
