### ISSUE TITLE
Adkats - Proxy using fineproxy.de

### ISSUE THREAD

**Issue by PeekNotPeak** [AdKats/AdKats#1043]
Since I'm apparently to dumb setting up adkats with a proxy I'm writing this issue. As the title explains I choosed fineproxy.de for my provider of choice. But I can't for the life of me get it working what am I doing wrong. I tried proxys with authorisations and without. Still no sign of working. What provider should I use? Do free proxys work also? There are so many questions hopefully you can help me.

Thank you in advance!

**Comment by Prophet731** [comment]
I had not realized this was open... Dang GitHub.

Anyways you could try https://brightdata.com/, it's not free but it works. EZSCALE offers the proxy service for free as part of the Procon Layer hosting (only works while on EZSCALE infrastructure).
