### ISSUE TITLE
Add @mytrouble command

### ISSUE THREAD

**Issue by Area51Brett** [AdKats/AdKats#143]
This command would show the player how many points are against himself and the reason of each one. So for example if I typed @MyTrouble the plugin would do a psay to me saying "exampleplayer, you have 4 infraction points against you for [reason of infraction point 1], [reason of infraction point 2], [reason of infraction point 3], [reason of infraction point 4]. If you wish to dispute any of these please go to [yourclansite.com]"

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
