### ISSUE TITLE
REQUEST: !Nextmap

### ISSUE THREAD

**Issue by Phenom300** [AdKats/AdKats#211]
Miss this command from the default in-game admin, while there's "nextlevel" it's kind of annoying having to !nextlevel !yes then repeating it in the second round again.

Would be nice if you could just !nextmap and have it switch to the next one.

Perhaps renaming nextlevel to nextround as well

**Comment by ColColonCleaner** [comment]
No response, closing.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
