### ISSUE TITLE
REQUEST: Email system enhancement

### ISSUE THREAD

**Issue by Hutchew** [AdKats/AdKats#276]
Enhancements, please......

Perhaps have grouping levels either in roles or in email subsytem.

I do not want an email every time someone says !admin or !report; those are for our active admins to deal with.

I DO want an email on blaze, crash, plugin panic, etc.........

Hutchew

**Comment by ColColonCleaner** [comment]
Closing as no response was given.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
