### ISSUE TITLE
Commands not executing unless Procon layer restarted

### ISSUE THREAD

**Issue by dmmaciag** [AdKats/AdKats#428]
We run AdKats and web admin on both of our servers, and commands will work temporarily but after a short time, if I punish someone, or any other command for that matter, the page on web admin will show them being punished but won't kill/kick/etc without the Procon layer being restarting. Once it's restarting everything goes through. I don't see any errors in  the console. Same occurs when processing reports, will @accept a report, but in the console it'll say the update for one of the players failed, so not sure if it actually went through or not.

**Comment by ColColonCleaner** [comment]
This issue has not been reported as continuing, or from any other sources.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
