### ISSUE TITLE
REQUEST: Country Blocker/Kicker on the ping managment

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#576]
As the title says :)

**Comment by iraqiboy90** [comment]
Hi

I would like to add to this the following:
Is it possible to make an option so that Country blocking is forced regardless of the "minimum player to kick" option?

**Comment by ColColonCleaner** [comment]
This could be added.

All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!
