### ISSUE TITLE
Add ability to send first spawn reputation/infraction messages to admins only.

### ISSUE THREAD

**Issue by Hutchew** [AdKats/AdKats#578]
The first spawn reputation/infraction messages were driving us batty. Players want to know what their infractions are, and what "reputation" is, and no easy way to tell them. We have turned this off on our servers for now.

Would still like to have it sent to admins, though. Troublemakers with bad rep and infractions are more easily spotted.

**Comment by ColColonCleaner** [comment]
Oh priorities. This can be used internally now. Will be completed in 7.0.0.0.

**Comment by ColColonCleaner** [comment]
"Will be completed in 7.0.0.0." LUL
This would cause a lot of chat spam for admins. Cancelling for now.
