### ISSUE TITLE
Add ability to define default expiration time for "roles", and send notification email on expiration.

### ISSUE THREAD

**Issue by Hutchew** [AdKats/AdKats#585]
So, we want admins, military and VIP to never expire, but would be nice to have the ability to define the default expiration time for other "roles".

Such as:
RL02 Small donor (default 1 month)
RL02 Medium Donor (default 2 months)
RL03 Large Donor (default 3 month)

Then, say 24-48 hours before expiration, it sends an email to the user (assuming he registered on webadmin) and to server admins (default RL20) to notify them as well.

Or possibly an in-game reminder that their perks are about to expire?

Do-able?

**Comment by ColColonCleaner** [comment]
This can be used internally. Will be completed in 7.0.0.0.

**Comment by ColColonCleaner** [comment]
I believe this is already added, users have expiration dates and there is a perk expiration system.
