### ISSUE TITLE
Request: Changing way roles gets marked as admin

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#598]
A separate True/False option added to every role that enables the role to be an admin role or not.

I want to be able to give some roles the ability to use some of the commands that are usually marked as admin command, without getting the entire role to get marked as admin therefore some commands acts differently (i.e. the !rules command)

I dont know if this request requires the webpanel to be changed as well?

**Comment by Prophet731** [comment]
@ColColonCleaner how much of a change would this take for you to do?

**Comment by ColColonCleaner** [comment]
This is referenced in many places, it's gonna be big.
