### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by Sturmkraehe** [AdKats/AdKats#607]
EXCEPTION: Line Unknown: [GetDisplayPluginVariables][Error while fetching display vars.]: System.InvalidOperationException: Die Auflistung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   bei PRoConEvents.AdKats.GetDisplayPluginVariables()

AdKats 5.2.2.5 while updating Adminrights!

**Comment by ColColonCleaner** [comment]
This was fixed in #655
