### ISSUE TITLE
REQUEST: Watchlist

### ISSUE THREAD

**Issue by kkaracho** [AdKats/AdKats#630]
I would really love if you could add something like a watchlist so you could add players (incl reason why) on that list and every admin can check that list or gets the list telled when they join the game

would be useful for players which usually tend to do certain stuff or if you just got a suspicion on a certain player

that way every admin knows about that player and can watch him if hes online

i hope you get what i am trying to explain :)

**Comment by ColColonCleaner** [comment]
This is being added in 6.5.0.0.

**Comment by ColColonCleaner** [comment]
This can be used internally, and will be released in 7.0.0.0.

**Comment by ColColonCleaner** [comment]
All AdKats 7 issues need to be recreated on the engine repository in the proper order. If you are still interested in this, add it there.
