### ISSUE TITLE
REQUEST: Push Notification

### ISSUE THREAD

**Issue by jamesonp** [AdKats/AdKats#637]
It would be awesome to have the ability to send push notifications for reports using Pushbullet or Pushover.  Both have APIs here:

https://docs.pushbullet.com/
https://www.reddit.com/r/PushBullet/comments/2m2pui/c_implementation_for_those_that_find_it_handy/

https://pushover.net/
https://pushover.net/faq#library-csharp

Not sure how feasible it would be but it would be awesome.

**Comment by ColColonCleaner** [comment]
Assigned to future usage. It would be nice, but don't get your hopes up for it.

**Comment by ColColonCleaner** [comment]
This could be added in the near future.

All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!

**Comment by ColColonCleaner** [comment]
Pushbullet integration was added.
