### ISSUE TITLE
Deny certain command actions from lower power levels on higher power levels

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#639]
Certain commands will be denied when issued from a lower power level player on a higher power level player. Players at the same power level can use all their allowed commands on each other.

These commands will be the following:

player_kill (player_kill_force still allowed)
player_kick
player_ban_temp
player_ban_perm
player_ban_perm_future
player_punish
player_forgive
player_mute
player_move
player_fmove
self_lead
player_pull
player_lock

**Comment by iraqiboy90** [comment]
Sry for re-opening this, but it seems like this was implemented in 6.5?
How do I control this option?

**Comment by ColColonCleaner** [comment]
No, it was in the 6.0.0.0 release a couple months ago, and in a few test versions before that as well. There are no controls for this. Power level calculation is in #629. I don't believe documentation in the manual was written for this section.
