### ISSUE TITLE
Adkats Extension: Loadout Enforcer not working correctly

### ISSUE THREAD

**Issue by Breakmaster90** [AdKats/AdKats#645]
Hi,

i have your Adkats Extension the Loadout Enforcer.
There is a bug/glitch:
I limit Smoke, Airburst and C4, but:
Players already in server cant change to c4, while joining ppl can use airburst, c4, etc.

**Comment by epos85** [comment]
So far so good, I will reply if I see any bugs later on.

Thanks for the fix, and have a happy new year!

Regards, 
Aleksander

**Comment by ColColonCleaner** [comment]
Closing issue.

**Comment by ColColonCleaner** [comment]
Marked invalid as this was not a bug with AdKats. For future inquiries please use the LRT repository.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
