### ISSUE TITLE
REQUEST: Add duration parameter to reserved slot command

### ISSUE THREAD

**Issue by TheMrApostel** [AdKats/AdKats#648]
It would be great when you add a optional timestamp to the "!reserved <playername> <reason>" like 
"!reserved <playername> <reason> [timelimit]"

So i could add temp. reserved Slots and dont have to delete by hand.

Thanks!

**Comment by ColColonCleaner** [comment]
All of the special player assignment commands are being changed to include a timespan. Thanks!
