### ISSUE TITLE
Request: Remove delay limitation on Spambot

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#678]
Hi

I still dont know why the minimum 60 second option for "yell" and "say" is being forced.
I think it's up to the admin if they want to mess up their server, right?

**Comment by ColColonCleaner** [comment]
The limitation is there as a standard.

**Comment by iraqiboy90** [comment]
Why?
How can I remove that limitation manually if you dont want to put it on the public files?

**Comment by ColColonCleaner** [comment]
There are other plugins that can do spambot-like functions, you can use those. AdKats is the only one that can whitelist players from it though.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
