### ISSUE TITLE
REQUEST: Tracking of commands issued for other plugins

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#679]
Hi

Would be nice if the "External plugin player/admin commands" gets to be tracked and logged on the player's profile. :)

**Comment by ColColonCleaner** [comment]
I do not understand the request.

**Comment by iraqiboy90** [comment]
Section 5
"External plugin player commands"
"Extenal plugin admin commands"

Currently used for the !help command

**Comment by iraqiboy90** [comment]
To be logged as in when it was used, just like any other adkat command.

**Comment by ColColonCleaner** [comment]
This request cannot be completed due to the program structure at this time. Storing for later.
