### ISSUE TITLE
auto nuke too slow?

### ISSUE THREAD

**Issue by BP4U** [AdKats/AdKats#680]
see below

**Comment by ColColonCleaner** [comment]
Your forum is private.

**Comment by BP4U** [comment]
DemonicDM - 17. Dezember 2014
I noticed auto-nuke twice today and that happened when all objective were taken so its working. but a lots of ppl didnt understood it and though admin was nuking. there was lags after that 
i dont know if that was because of plugin or just random lag.

maybe more clear information should shown for players or longer msg. but i liked it.

just fyi :)

--

Dr_F1ST - 18. Dezember 2014
Hey Demonic,
thx for your post, we will try to fix all issues soon.
I'm quite sure that in the next days the plugin will be known better by the players so that should be much better soon, too. But i will add another msg in the spambot about this feature.

--
	
DemonicDM - 22. Dezember 2014
just a suggestion, the auto nuke trigger has a very slow countdown and sometimes it gets cancel middle of count down, i dont know because of a admin or bug, its like 3 trigger left and still all the objective is taken and suddenly it gets cancel.

 --
	
OmniStress - Vor 5 Minuten
Yeah I agree with that... sometimes takes aggess for it to actually fire a nuke.

**Comment by ColColonCleaner** [comment]
Update to 6.0.2.3, then if the issue continues let me know.

**Comment by ColColonCleaner** [comment]
Updates please.

**Comment by BP4U** [comment]
it seems to work fine now...there only was one or two feedbacks that the counter goes 20 - 33 - nuke
but i cant confirm that it happened and if it happened it was only on one day

**Comment by BP4U** [comment]
20% - 33% - nuke
