### ISSUE TITLE
Ping Enforcer is not working

### ISSUE THREAD

**Issue by TheMrApostel** [AdKats/AdKats#682]
When the Ping Enforcer is section B21 is enabled players with the specified "high ping" won't be kicked.
Is the ping enforcer not working?
![2015-01-10 12_05_57-procon frostbite](https://cloud.githubusercontent.com/assets/10365495/5691327/288a43ec-98c1-11e4-9aa9-deef879f0087.jpg)

**Comment by ColColonCleaner** [comment]
Try removing every value in your ignore roles list, and setting ignore user list to true. If it works then, I've found the issue. If not, i'm not sure yet.

**Comment by ColColonCleaner** [comment]
These are our settings, try first changing all yours to these, and confirm it's working. Then, continuing to confirm it's working for each, change each value in order back to the ones you have: http://i.gyazo.com/9274da7058e5d29b4e49a9b22a3a6715.png
Let me know which setting it fails on.

**Comment by TheMrApostel** [comment]
i cleared the ping kick ingore roles and set the ingore user list to true.

**Comment by TheMrApostel** [comment]
Changed the options like you said but sadly nothing worked.
I think i will go with the Latency Manager. That plugin works fine for me:
[15:10:45 84] Latency Manager: Kicking xGlunt : You were kicked because a high Ping of (535)! Sry!

I think theres some problem on our side. Maybe the layer server or whatever are not able to receive the players ping properly. With the !pinfo command the players ping is also missing.
Maybe this two problems have the same source? What do you think? 
In that case you can close that ticket.

Thanks!!

**Comment by ColColonCleaner** [comment]
Is this still an issue?

**Comment by danidoedel** [comment]
Yeah for me it is... Same problem for me.

**Comment by ColColonCleaner** [comment]
Moving from questions into 7.0.0.0, i'll work on confirming this bug.
