### ISSUE TITLE
Automatic player locking on admin action is not working as intended

### ISSUE THREAD

**Issue by TheMrApostel** [AdKats/AdKats#683]
When i set the option "Automatically Lock Players on Admin Action" to true it would be awesome when the admin who triggerd this action could still use action on the players without using the command !unlock.

For example:
When i kill a player with !punish the player will be locked and no admin can trigger any actions with that player.
Also i have to unlock the player first in order to trigger one more action.
It would be awesome to change the locking system so that the admin who triggerd the first action on the player can trigger more actions without unlocking them.
Other admins should still get the message "player xxxx is locked by admin xxx".

Is that possible?

Thanks in advance!

**Comment by ColColonCleaner** [comment]
This should already be the case. If it's not, this is a bug.

**Comment by ColColonCleaner** [comment]
These are our settings, try first changing all yours to these, and confirm it's working. Then, continuing to confirm it's working for each, change each value in order back to the ones you have: http://i.gyazo.com/9274da7058e5d29b4e49a9b22a3a6715.png

**Comment by TheMrApostel** [comment]
When i lock a player while the option "automatically lock players on admin action" is set to true i will get the message 
[13:13:46] AdKats > Say > TheMrApostel > [C4C]TheMrApostel is command locked by TheMrApostel. Please wait for unlock [2m18s].
![2015-01-10 13_09_50-procon frostbite](https://cloud.githubusercontent.com/assets/10365495/5691502/10ef884c-98ca-11e4-81e9-0fd3efadb0b0.jpg)

This is what happen when we also take actions on other "not admins".

**Comment by TheMrApostel** [comment]
Thats also a very "interesting" message:
[23:35:41 16] [AdKats] Crybt0 is command locked by AFKManager. Please wait for unlock [47s].

**Comment by ColColonCleaner** [comment]
Oh wow, this was never assigned a milestone, apologies.
