### ISSUE TITLE
Improving the mute command

### ISSUE THREAD

**Issue by TheMrApostel** [AdKats/AdKats#684]
I noticed when i create a private converstation with a player the conversation will not be displayed in the ingame chat.

Is it possible to do that with the mute command also?
The player can still write in the chat and gets punished but the chat shouldn't be displayed in the chat like the one from private converstation.
Maybe it would be possible to create a private converstation with the admin who triggerd the mute?

**Comment by TheMrApostel** [comment]
![2015-01-11 00_36_27-new issue adkats_adkats - opera](https://cloud.githubusercontent.com/assets/10365495/5693855/c08caccc-9932-11e4-845f-184516a05558.jpg)
Here you can see what i mentioned.
In the private converstation the command /r text won't be displayed and that would be exactly what i wanted for the mute command :)

The chat of the muted player is just visible for the admin who triggerd the mute and the player still get the counts of the muting command.

**Comment by ColColonCleaner** [comment]
I'm not sure what you are asking. I can't block a player from typing in chat, only punish them for doing so.

And as for commands not showing up in chat, just use / as the command prefix.

@mute
!mute 
.mute 
/@mute 
/!mute
/.mute
/mute

...all work. Every command is this way.

**Comment by TheMrApostel** [comment]
Take a look on the screenshot above.
Here you can see that i am in a private conversation with a player.
To reply i use the command /r [text] right?

In the procon chat you can also see that i was typing /r Test and me and the other player got this message:
(MSG)(TheMrApostel):Test

All other players can't see this private conversation not even the command i was typing.
Lets say i use the !adminmsg [text] command.
In this case every player can read the command line.

For example:
I am typing in Squadchat :"!adminmsg Hello Admins"
Then all players in my Squad can see what i was typing. They can simply read the command.

In a private converstation the command is not visible for all other players except for me and the other player within the conversation.

So back to the screenshot. I type "/r test" but the command was not displayed ingame.

Let's say you mute me for some reason it would be enough when i enter a permanent private converstation without knowing it for the rest of the round + get punished while talking.
Nobody except for you can see what i am typing and noone else.
Everything what the player is typing have to be part in the private converstation to the muting admin.
I don't know if its possible to do such a thing but it was very interessting when i discovered that other players couldn't see the text i was typing within the private conversation.

Hope you understand me now a little better :)

**Comment by ColColonCleaner** [comment]
you can !r [text] a conversation, all that changes is the slash. it's a standard in many video games, and chat systems as a whole, messages starting with / are assumed commands and are not shown to anyone. This has nothing to do with the fact that it's assigned to a certain command, any message beginning with / will not be shown in chat. 

/hello this is a test

would be hidden. This is the game's coding, not mine, i have no control over what messages are displayed or not displayed in chat, it's all up to the person writing the message.

**Comment by ColColonCleaner** [comment]
I hope you understood what i was trying to say. If i could actually make a muted player's chat be hidden at all times, I would have already made it that way.

**Comment by TheMrApostel** [comment]
Yes i understood what you say.
Was just throwing my ideas in the room.

Thank you anyway.
