### ISSUE TITLE
REQUEST: automatic VIP for TOP X players

### ISSUE THREAD

**Issue by kkaracho** [AdKats/AdKats#702]
Is it possible to add this to adkats?
Since its using statslogger it could grab the TOP X players and automatically give them VIP slots or am i wrong?
that would be really awesome if that could be implemented :+1:

**Comment by ColColonCleaner** [comment]
Yes it can be done, the CMW Gaming clan donated for setting section B27-1, which has options for automatic VIP (including options for reserved slot, autobalance whitelist, ping whitelist, and teamkilltracker whitelist) for players who help them seed their servers. Update to the latest test version 6.0.5.0 to see it.

I can do the same with top X players, send a donation via the AdKats thread and i'll add your feature. Thanks!

**Comment by ColColonCleaner** [comment]
Closing in 10 days.

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
