### ISSUE TITLE
Request: Options for power level & its restrictions

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#721]
https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-5-0-0&p=116876&viewfull=1#post116876

:)

**Comment by ColColonCleaner** [comment]
Could be useful for some.

All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!

**Comment by ColColonCleaner** [comment]
Closing for now unless someone wants to reopen it. It's a very specific ask.
