### ISSUE TITLE
REQUEST: Auto kill new players to "force" reading rules

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#722]
Hello

Maybe a drastic measure this one, but if I check my server logs, maybe 5 out of 100 new players uses the !rules command, and not until they are already punished, that's when they start reading the rules.
So, instead of doing the punishments and add a record to their profile, a forced warning is better.

So, I've been thinking about a method for autoadmin to kill new players joining for the first time to the server and telling them to read the rules. 

Option 1: Kill multiple times once alive, until the !rules has been used, and not just new players.
With option 1, there will be no "I didnt know the rules"
Option 2: Kill only once when the player has spawned for first time.

If possible the message is translated (or pre-set) according to their Geo-location

What do you think?

regards
iraqiboy90

**Comment by Prophet731** [comment]
Personally I think just focing the rules to be displayed on player spawn without killing them would be better. Also accompanying it with a yell.

For geo-location specific messages I think creating a new table that just has the country code and the messages would be easier to maintain and easier parsing.

@ColColonCleaner what do you think?

**Comment by iraqiboy90** [comment]
Currently I have this, and they dont care:
- Welcome to our server. Use !help to see all commands. Read the rules, you have been warned.

**Comment by ColColonCleaner** [comment]
Sounds like admin abuse waiting to happen, but could be added.

All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!

**Comment by ColColonCleaner** [comment]
Yeah, this would just end up emptying any server its used on. "Sounds like admin abuse waiting to happen" is about right. Closing.
