### ISSUE TITLE
Question: Server spesific users/roles?

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#725]
Hello

Is this already possible?
I want to add a user for our BF3 servers, but I'm thinking, if I have a bf4 server as well, it would automatically transfer itself?

**Comment by ColColonCleaner** [comment]
All users will transfer between any servers you run. The only difference is you will have different soldiers for bf3 and bf4. Once your bf3 soldier has been loaded into the database by joining the server, simply add them to your user like any other. Once added, you will see two soldiers with the same name on your user but having different game identifiers.

**Comment by iraqiboy90** [comment]
Thanks. How can I close ticket?

**Comment by iraqiboy90** [comment]
Sry, but I just came up to a situation;

If I want to give VIP to a BF3 player just on one of the BF3 servers, how do I assign a group to him without getting it to apply globally on all BF3 servers?

**Comment by ColColonCleaner** [comment]
There is no such thing as "VIP", what are you trying to do?

**Comment by iraqiboy90** [comment]
"VIP" is a group I created with special permissions, i.e. whitelists.
If I want to assign this group to a player on only one server at a time, how is it possible with the current setup?

**Comment by ColColonCleaner** [comment]
There is no way to do that at the current time.
