### ISSUE TITLE
REQUEST: Automatic Infraction Reduction

### ISSUE THREAD

**Issue by Phenom300** [AdKats/AdKats#726]
Hi,

As discussed it would be nice if players had their infractions automatically reduced over a period of time if their player reputation is positive, or through seeding servers etc becomes positive.

cheers
Jason

**Comment by ColColonCleaner** [comment]
This can be used internally. Automatic single forgive if a player joins with positive reputation, has positive infraction points, has not been punished in the last month, and has not been forgiven in the last month. I'll work on it.

**Comment by iraqiboy90** [comment]
Will this be adjustable?

**Comment by ColColonCleaner** [comment]
An on/off switch will be provided for now.
