### ISSUE TITLE
REQUEST: Prevent moderators from forgiving themselves

### ISSUE THREAD

**Issue by Phenom300** [AdKats/AdKats#727]
It would be nice if moderators were unable to forgive themselves (Infraction system), of course some would see this as abuse and it is, but preventing them from being able to use the command on themselves in the first place would cause less problems.

Disabling the command means they can't use it on anyone.

**Comment by ColColonCleaner** [comment]
This can be used internally. Once implemented the only player able to forgive themselves will be the debug soldier for usage with testing/setup, everyone else must get a secondary admin to forgive them. This does not block people from using procon to forgive themselves.

**Comment by iraqiboy90** [comment]
nice one this one.
I was looking through the panel when I saw that this could be useful :)
:+1:

**Comment by ColColonCleaner** [comment]
@Prophet731 You should probably set this up to work for non 'site administrator' GCP users forgiving themselves as well.
