### ISSUE TITLE
Grant / deny roles selected whitelist

### ISSUE THREAD

**Issue by dyn0** [AdKats/AdKats#730]
Either explicitly grant or explicitly deny specific roles from being added to each orchestration setting / perk setting. For example, feed admin roles teamkilltracker, reserved, and multibalance white lists (all of them, I suppose) for admins provided they have that particulate orchestration setting set for their role. 

The same would be true for admin messages.  Certain groups do not need to see the admin messages, while others do.  

Originally from: https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-5-0-0&p=117295&viewfull=1#post117295

**Comment by iraqiboy90** [comment]
Check section 4-2 in the Adkats settings. You can do specific whitelists based on groups

**Comment by ColColonCleaner** [comment]
Was this issue resolved?

**Comment by ColColonCleaner** [comment]
No response.
