### ISSUE TITLE
Pull player stats from battlelog instead of BF3stats/BF4stats

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#734]
With the latest hacker craze brought on the "free play time" offered by EA, having fully updated stats has become necessary.

@Prophet731 Please provide details about your stat parsing for both BF3 and BF4 at earliest convenience so I can expedite the conversion. PM.

**Comment by Prophet731** [comment]
I'm on TS right now if you're still up.

**Comment by ColColonCleaner** [comment]
Just send the details please, I must sleep, finals and job interview tomorrow.
