### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by BFMP00P** [AdKats/AdKats#737]
I know I seen someone have this same issue in the Phogue forums but I don't recall seeing a resolution.
Everytime I try injecting the sql file into my database I get the following error:

Error
SQL query:

REPLACE INTO `adkats_rolecommands` VALUES(1, 76);

REPLACE INTO `adkats_rolecommands` VALUES(2, 1);
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `adkats_rolecommands` VALUES(2, 1)' at line 3

**Comment by ColColonCleaner** [comment]
Yes, this is an error caused by a new version of phpmyadmin. Any older version of phpmyadmin, or using another program such as MySQL Workbench does not see this issue. Something is wrong with their system, it is not because of an error in the SQL file. Try using MySQL workbench.

**Comment by BFMP00P** [comment]
MySQL Workbench worked like a charm.
I forgot that program even existed and I use to use it all the time awhile back.
Thanks for the heads up.
