### ISSUE TITLE
REQUEST: Report/CallAdmin Blacklist and respective commands

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#738]
Hello

The feature to put a player on the "reporting blacklist" so he cannot report someone else.
This is add those who abuse the report system to this list so they stop spamming.

**Comment by ColColonCleaner** [comment]
All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!

**Comment by ColColonCleaner** [comment]
Donation provided, item will be completed within the week.

**Comment by ColColonCleaner** [comment]
Tested and functional. AdKats TEST branch 6.5.1.9.

**Comment by iraqiboy90** [comment]
Hi
Just saw this message, is the test branch safe for the DB?

**Comment by ColColonCleaner** [comment]
Yes, simply replace the plugin file.

You can download the latest test branch plugin from here: http://api.gamerethos.net/adkats/fetch/test?force=1

**Comment by iraqiboy90** [comment]
Hi
What is the function called on the settings?
- Report Target blacklist?

**Comment by ColColonCleaner** [comment]
Commands
/rblacklist
/unrblacklist
Special Player Group:
Report Target Blacklist

**Comment by antivanity** [comment]
is rblacklist now no longer available ?
