### ISSUE TITLE
REQUEST: Custom temp-ban durations in the punishment hierarchy

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#739]
Add parsing of ban duration times like the tban in-game command on top of that though?

:)

**Comment by ColColonCleaner** [comment]
This feature can be used internally, so it will be added at no cost. Added to 7.0.0.0.

**Comment by ColColonCleaner** [comment]
I think adding custom durations at this point is overkill. Closing as cancelled for now.
