### ISSUE TITLE
Request: Multiple Bans and Bans by server ID

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#740]
Hello

In respect to the previous change on https://github.com/AdKats/AdKats/issues/294

I'm asking for a modification request:

An option on the Adkats settings to select whether ingame bans are set per server group or server ID. This will not apply to the bans made manually in the panel.

Autoadmin bans will need to have the same but separate option to select whether or not bans are made per server group or server ID.

Also the possibility for multiple bans per player, because unless we do global bans, then a player cant be banned on multiple selective servers.

In regards to BFAdminCP: @Prophet731 
On manual bans, a checkbox based selection of servers. Where this will serve for the combination of Ban by Server Group, per server ID and as a Global Ban if all selected.

**Comment by Prophet731** [comment]
This would require a major modification of how the ban system is done. Including the schema. The bans table is not designed for this due to the player id being a unique index. So only 1 entry per player. 
Also there is no column on the bans table for server id.

Schema changes shouldn't be too difficult but in AdKats I think it will be lots of code rewriting of the ban management system alone. @ColColonCleaner correct me if im wrong on that.

**Comment by iraqiboy90** [comment]
I'm willing to support the change..
I mean, this current setup is only usefull for clans/communities having the ban someone global policy, but yet again, if you use different Server Group number then you will still have issue of not being able to transfer those bans to other server groups...

**Comment by ColColonCleaner** [comment]
Understand there was no server or server group specificity before, if someone was banned, they were banned, period. That is how the system was originally built and intended to run. 

A workaround was added for one person to have their bans work a certain way, anything else was out of scope.

We need to document what exactly is wanted, in detail, then plan a system around that if the change is worth it to the supporting person.

**Comment by iraqiboy90** [comment]
Ok

This problem becomes bigger with the more servers a clan/community have. Specially, like I said, if they use different Server Group on different group of servers then they will be stuck with the limitation of only having the possibility to add one ban to one server group at a time.
I'm sure you guys at ADK are running different Server Groups, if not then it's a global ban but yet again, we don't practice the "Global ban" policy unless the player is cheating.

Currently here's what I see the Server Group number system is being used for (the ones I could see first hand):
- When a new player joins the server, Adkats says "Player joined this server group for first time".
If, like us, use different Server Group number on each server, then this feature would be used to see if the player joined THE server for the first time. Which is more useful than the next way:
If all servers running the same Group number then this would be used to see if the player joined ANY of the servers...
- Obviously so far; The server group number is currently being used to add one ban to a group of servers at a time.
- (Optional by Statlogger) It's being used if the community wants to consolidate all stats into group of stats.

That's it. Or is there more?


What is wanted:
- To change the banning system to apply on server ID and not server group.
- To change the banning system to be able to have more than one ban on the same player ID.
With these two, the banning system will not have any of the restrictions it currently have...
It would allow both the "Global Ban" and the "Selective Ban" policies to be practised.

Details:
I wont say I have the technical knowledge into this coding to say anything on how, but if I would guess I could say to:
- Autoadmin bans will need to have an selectable option to be able to select whether or not bans are made per server group or server ID.
This will utilize the need of server group banning when, lets say, you have a set of no-explosive servers.
- For BFAdminCP: To have checkboxes when selecting servers for bans through the panel.
Also, the "editing" a ban should not create a new record.

**Comment by Prophet731** [comment]
> For BFAdminCP: To have checkboxes when selecting servers for bans through the panel. ||| Also, the "editing" a ban should not create a new record.

The reason why we create new records is for the ban history. You want to keep track of all the changes done to the ban.

**Comment by iraqiboy90** [comment]
Well... two factors should decide the ban is history or not:
- the expiration time
- Disabling the ban

**Comment by ColColonCleaner** [comment]
This isn't going to happen without a funded request. Too much work would be required to make this viable as an internal request.

**Comment by ColColonCleaner** [comment]
Ok, back on this topic.

@Prophet731 We would either need to untie the 1 ban per player listing somehow, or add another column to the bans table that contained a list of server IDs. The first seems like the best approach but there is a lot of code we've both written that assumes one ban per player.

If we untie that connection with bans to players being 1-1 we can use the existing server ID column to signify which server the ban is active on, and null for all servers. We would need to add a server group column though, because there are people who expect the existing functionality and we don't want to modify that.

It's gonna be trench work to go through and rework this, prophet and I can come up with a number once we've analyzed it more, if it's even feasible at this point.

**Comment by Soulzz** [comment]
@ColColonCleaner , if you need funding, just let me know, I might be able to at least contribute something.

**Comment by Prophet731** [comment]
@ColColonCleaner 

We just need to revamp that system to do it properly. Not just add to it as a quick fix. So we need to find time to actually sit down and build a blueprint for that.

**Comment by Prophet731** [comment]
@ColColonCleaner 

Can you create the milestone version 6.9.0.0 and put this ticket under that and any other tickets that we are planning for that version.
