### ISSUE TITLE
MYSQL Error #1558 - Column count of mysql.proc is wrong. Expected 20, found 16. Created with MySQL 50051, now running 50538. Please use mysql_upgrade to fix this error. 

### ISSUE THREAD

**Issue by knownchild** [AdKats/AdKats#745]
How to fix this?

**Comment by ColColonCleaner** [comment]
This error is unrelated to AdKats, it is a general MySQL error.

http://stackoverflow.com/questions/16177465/column-count-of-mysql-proc-is-wrong-expected-20-found-16-the-table-is-probabl

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
