### ISSUE TITLE
CMDRManager shouldn't kick existing commanders if player count drops below X

### ISSUE THREAD

**Issue by Prophet731** [AdKats/AdKats#746]
Instead it should act if on next round the player count is below X instead of during the current active round.

**Comment by ColColonCleaner** [comment]
This can be added as an option, some people want commanders gone regardless.

**Comment by Prophet731** [comment]
All I know is it was hard for my debugging purposes when I got kicked last night because of that.

**Comment by ColColonCleaner** [comment]
All AdKats 7 issues need to be recreated on the engine repository in the proper order.
