### ISSUE TITLE
AdKats 7 - Watchlist Table

### ISSUE THREAD

**Issue by Prophet731** [AdKats/AdKats#749]
This needs to be added in version 7. It's a simple table that will just have player ids and the created datetime field.

**Comment by ColColonCleaner** [comment]
Or just use a special player group. Probably renamed.

**Comment by Prophet731** [comment]
I guess it could be used for that.

**Comment by ColColonCleaner** [comment]
It's designed for things like this, i'll assign/rework this once i have a basic system down.

**Comment by ColColonCleaner** [comment]
All AdKats 7 issues need to be recreated on the engine repository in the proper order.

**Comment by Prophet731** [comment]
Hey @ColColonCleaner, you think we'll be able to add this in?
