### ISSUE TITLE
admin role configuration

### ISSUE THREAD

**Issue by BP4U** [AdKats/AdKats#773]
Hi,

we use the specialplayers table for our reservedslotlist, so all in specialplayers and admins should be on the reservedslotlist. This is working good with the "automatic reserved slots for admins", but now also our premium players, who have to buy slots but have also some limited power on the server, also get counted as admins and are automatically added to the reservedslotlist. Is there a way to get this Premium Role out of the admin-counting, so they don't automatically get into the reservedslotlist?
Thx

**Comment by ColColonCleaner** [comment]
Yes. Firstly update to the latest test version.

1. Turn off automatic reserved slot for admins. 
2. Enable reserved slot in section 4-2 for only the roles you want to have an automatic reserved slot.

Cheers.

**Comment by BP4U** [comment]
thanks a lot!
