### ISSUE TITLE
how to Double nukes?

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#774]
Auto Nuke work after 
How to continuous automatic kill player?

e.g
AdKats > Say > Preparing auto-nuke. 20% ready.
AdKats > Say > Preparing auto-nuke. 40% ready.
AdKats > Say > Preparing auto-nuke. 60% ready.
AdKats > Say > Preparing auto-nuke. 80% ready.
AdKats > Tell[5s] > Nuking US Army for baserape!
AdKats > Say > Auto-nuke paused.

I hope I can change to:
AdKats > Say > Preparing auto-nuke. 20% ready.
AdKats > Say > Preparing auto-nuke. 40% ready.
AdKats > Say > Preparing auto-nuke. 60% ready.
AdKats > Say > Preparing auto-nuke. 80% ready.
AdKats > Say> First Nuking US Army for basename! second Nuking will 12 seconds after!
AdKats > Tell[5s] > First Nuking US Army for basename! second Nuking will 12 seconds after!
AdKats > Say> Second Nuking US Army for basename! 
AdKats > Tell[5s] > Second Nuking US Army for basename! 
AdKats > Say > Auto-nuke paused.

**Comment by BP4U** [comment]
+1

that would be awesome

**Comment by Subman-CNP** [comment]
+2
one nuke in most situations is not enough

**Comment by BP4U** [comment]
push

**Comment by supewong** [comment]
@ColColonCleaner 
I know you're busy
But can you give some attention to this thread?
THX
Or this thread will be impossible?

**Comment by ColColonCleaner** [comment]
This has been solved by nuke duration. The nuke will keep a team dead for a specified amount of time now.
