### ISSUE TITLE
REQUEST: Time-Of-Day ping limit modifier

### ISSUE THREAD

**Issue by wdfstryfe** [AdKats/AdKats#775]
Have a ping limit based on the time of day.

IE

300am - 1200pm -- full server 300
1201pm - 0600pm -- full server 200
0601pm -- 259pm -- full server 120

**Comment by ColColonCleaner** [comment]
Request funded.

Current Ping Limit (Display)
Ping Kick Low Population Trigger ms
Ping Kick Low Population Time Modifier
Ping Kick Medium Population Trigger ms
Ping Kick Medium Population Time Modifier
Ping Kick High Population Trigger ms
Ping Kick High Population Time Modifier
Ping Kick Full Population Trigger ms
Ping Kick Full Population Time Modifier

Time Modifier list will contain 24 numbers, 1 on each line. Each line represents an hour of the day in the procon layer time zone, the number on the line will be the modifier on the current ping limit.

e.g.

Current population: Full
Full ping limit: 100
Time of day (layer timezone): 3:30 AM
Full pop Time Modifier:
0
50
50
100
200
etc...to 24 lines

resulting ping limit = 200 ms

**Comment by ColColonCleaner** [comment]
Version 6.7.0.48 contains this update. Please reply once you've tried it out.

**Comment by smogsy** [comment]
i've set it up as follows on 1 server just for testing.

Low pop =  500ms 
no Modfier

Medium pop = 250 
Modifer of 50ms between 00:00-07:00

High pop = 180
Modifier of 120ms = 120 between 00:00-07:00

**Comment by wdfstryfe** [comment]
I hadn’t had a chance to mess with mine yet, I’m trying to get feedback from the regular players to see what would seem best. I have full faith that this will work wonders though. :)

 

From: "don williams"
 <don@whendarknessfalls.org>
Sent: Thursday, June 04, 2015 12:54 PM
To: AdKats/AdKats
Cc: wdfstryfe
Subject: Re: [AdKats] Request: Time based ping limit (#775)

 

i've set it up as follows on 1 server just for testing.

Low pop = 500ms 
no Modfier

Medium pop = 250 
Modifer of 50ms between 00:00-07:00

High pop = 180
Modifier of 120ms = 120 between 00:00-07:00

—
Reply to this email directly or view it on GitHub <https://github.com/AdKats/AdKats/issues/775#issuecomment-108968244> .  <https://github.com/notifications/beacon/AJprxEfSFVfU_tUadoaPKBoBAm-Oao6gks5oQHoigaJpZM4EwAoh.gif> 






IMPORTANT NOTICE: This e-mail message is intended to be received only by persons entitled to receive the confidential information it may contain. E-mail messages to clients of the WDF Gaming Network may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system.

**Comment by ColColonCleaner** [comment]
Keep in mind this is NOT using server time, it's using procon layer time. If your layer/server are in different places it has no knowledge of the time zone difference.

**Comment by wdfstryfe** [comment]
Yeah, I figured this much. :)

 

From: "don williams"
 <don@whendarknessfalls.org>
Sent: Thursday, June 04, 2015 1:12 PM
To: AdKats/AdKats
Cc: wdfstryfe
Subject: Re: [AdKats] Request: Time based ping limit (#775)

 

Keep in mind this is NOT using server time, it's using procon layer time. If your layer/server are in different places it has no knowledge of the time zone difference.

—
Reply to this email directly or view it on GitHub <https://github.com/AdKats/AdKats/issues/775#issuecomment-108978703> .  <https://github.com/notifications/beacon/AJprxHs1g4cXfnW5UPo-_ZuRPtgdtg0gks5oQH5igaJpZM4EwAoh.gif> 






IMPORTANT NOTICE: This e-mail message is intended to be received only by persons entitled to receive the confidential information it may contain. E-mail messages to clients of the WDF Gaming Network may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system.

**Comment by wdfstryfe** [comment]
So far it’s been working great.

 

From: "don williams"
 <don@whendarknessfalls.org>
Sent: Thursday, June 04, 2015 1:12 PM
To: AdKats/AdKats
Cc: wdfstryfe
Subject: Re: [AdKats] Request: Time based ping limit (#775)

 

Keep in mind this is NOT using server time, it's using procon layer time. If your layer/server are in different places it has no knowledge of the time zone difference.

—
Reply to this email directly or view it on GitHub <https://github.com/AdKats/AdKats/issues/775#issuecomment-108978703> .  <https://github.com/notifications/beacon/AJprxHs1g4cXfnW5UPo-_ZuRPtgdtg0gks5oQH5igaJpZM4EwAoh.gif> 






IMPORTANT NOTICE: This e-mail message is intended to be received only by persons entitled to receive the confidential information it may contain. E-mail messages to clients of the WDF Gaming Network may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system.

**Comment by ColColonCleaner** [comment]
Ticket will be closed in 1 week if no issues are found.

**Comment by smogsy** [comment]
not a issue, just a question, 
i assume when a player gets kicked they get the message i set eg
Please lower your ping <180 & re-join Anarchy UK!

is their anyway of making the 180 say the current set limit? or does it already do it?

ive not been kicked so not seen the message :D

**Comment by ColColonCleaner** [comment]
You can turn on disconnect messages in the procon chat tab to see all kick reasons. 

No it does not operate like that currently.
