### ISSUE TITLE
Adkats BanEnforcer

### ISSUE THREAD

**Issue by Breakmaster90** [AdKats/AdKats#778]
Hi,

i think its a bug on BanEnforcer.
We banned some guys, but the banned Players can still join.
Its only work, if i activate Metabans.
Then it parse always with metabans.
But without metabans...banenforcer not working.

Can you check that.

Adkats 6.7.0.65
Procon Layer by Gameserver Provider on Windows Machines.
MySQL Database on my Dedicated Windows Server 2012 R2 64 Bit Server
MySQL Server 5.6.25

**Comment by ColColonCleaner** [comment]
Try banning yourself and attempting to join again, if it works for you then their player identification data was probably wiped by stat logger. This is a known bug with that plugin. Create the trigger mentioned in this post to stop it from happening: https://forum.myrcon.com/showthread.php?6698-Chat-GUID-Stats-and-Mapstats-Logger-1-0-0-2&p=118362&viewfull=1#post118362

If it also does not work on your player without running metabans then that's an issue I haven't seen yet.

**Comment by Breakmaster90** [comment]
Oh nice.
You are right. Now is OK.
Damn stat logger ^^"

**Comment by ColColonCleaner** [comment]
It's a great plugin, just a few bugs and the plugin creator is long gone :(

Closing.
