### ISSUE TITLE
Hacker-Checker in 6.7.0.67

### ISSUE THREAD

**Issue by BP4U** [AdKats/AdKats#780]
Hi,
There seems to be a problem with the Hacker-Checker in the latest test 6.7.0.67 as the "enable" switch for "DPS Checker" is missing. Is hacker-checker working properly anyways? Can i switch it on in the database? Is there a way to check if it's working except start cheating? ;)

**Comment by ColColonCleaner** [comment]
The DPS checker is always active now, it can't be disabled. The only setting that can be changed for it is the ban message.

**Comment by BP4U** [comment]
cool, thx!
