### ISSUE TITLE
Hacker-Checker DPS [LIVE] check has issues on hardcore servers

### ISSUE THREAD

**Issue by antivanity** [AdKats/AdKats#782]
I am getting a lot of bans from the DPS checker looking like "[LIVE][QBZ951-44-12-0]"

What does the [LIVE] part of it mean ?

**Comment by ColColonCleaner** [comment]
In the latest test version AdKats now catches damage mods live between rounds, in addition to using overall weapon statistics.

There is one issue which has been noted with that system on hardcore servers. I will be patching that tonight. If you are running a hardcore server please disable the hacker-checker until tonight's patch.

**Comment by antivanity** [comment]
Yep we are HC, lots of bans here as of late. thanks for your work man!

**Comment by ColColonCleaner** [comment]
Yeah they are most likely false positives. Please remove the bans and disable hacker-checker until tonight's patch.

**Comment by ColColonCleaner** [comment]
Uploaded 6.7.0.68, it should be fixed in that version.

Update with /pupdate

**Comment by antivanity** [comment]
Updated, thanks again for your hard work.

**Comment by ColColonCleaner** [comment]
If you see any further LIVE bans you believe to be invalid please let me know. I'll keep this issue open for a few weeks.

**Comment by antivanity** [comment]
Just to update, we had 3 DPS bans come in. All check out as legit bans! Looks fixed to me CCC. Thanks man! Also i saw you drop by our teamspeak (rTr), did you want to catch up on something ?

**Comment by ColColonCleaner** [comment]
Sounds good. If it's not too much trouble please ban reasons given for any live triggers issued in the next couple weeks. We don't have hardcore servers so having that information is important. Thanks.

As for TS, i honestly didn't remember you were from rTr. I joined there to make sure this wasn't messing up any of their hardcore stuff, then saw your name :P

**Comment by antivanity** [comment]
Ill pass on DPS kill info to this thread for a bit.

Yeah, unfortunately Hutchew ran into some real life issues. I have stepped up to take over procon duties.

**Comment by antivanity** [comment]
[P226-75-134-59] http://bf4db.com/players/12660293
[MG4-98-74-5] http://bf4db.com/players/7449430
[LIVE 60][L86A2-52-40-2-46] http://bf4db.com/players/12193054

3 bans so far, whats the 'LIVE 60' mean, 60 minutes ?

**Comment by ColColonCleaner** [comment]
Correct, it is the server health amount at ban time. I will be moving the values around once this is pushed to everyone, but this will be there until then.

**Comment by antivanity** [comment]
[L86A2-53-83-10] http://bf4db.com/players/1791078
[A91-59-68-7] http://bf4db.com/players/15699992

**Comment by ColColonCleaner** [comment]
Thanks, any other live bans?

**Comment by antivanity** [comment]
No other bans, i have passed all the bans that come through so far.

**Comment by antivanity** [comment]
This just came in, not as blatant as the others: [93R-49-136-50] http://bf4db.com/players/2402824

**Comment by ColColonCleaner** [comment]
His 93R is dealing 223% its normal damage. Not blatant overall, but that weapon appears to be.

**Comment by antivanity** [comment]
[ASVAL-82-61-11]  http://bf4db.com/players/14404843
[M416-67-81-32] http://bf4db.com/players/15678150

**Comment by antivanity** [comment]
Look at this one please: [LIVE 60][CBJMS-76-14-2-11]  http://bf4db.com/players/1168004

[AKU12-81-52-5] http://bf4db.com/players/7993629

**Comment by ColColonCleaner** [comment]
Thanks for the update. Both are valid. For the live he killed 14 players with 11 hits, the two headshots making up the difference.

**Comment by antivanity** [comment]
[TYPE88LMG-70-57-16] http://bf4db.com/players/12123622
[AEK971-49-176-38] http://bf4db.com/players/113851

**Comment by antivanity** [comment]
Everything looks good CCC, need any more examples ?

**Comment by ColColonCleaner** [comment]
Nope, looks good on my end too. Thank you for the testing. Issue closed.
