### ISSUE TITLE
Certain AdKats functions throw errors on Linux x64 layers

### ISSUE THREAD

**Issue by BP4U** [AdKats/AdKats#783]
[13:47:25 44] [AdKats] EXCEPTION-6670-D-FetchPlayerStatInformation-HackerChecker54: [Error while parsing player stats data.][System.NullReferenceException: Object reference not set to an instance of an object

**Comment by ColColonCleaner** [comment]
Your servers:
#06 [BP4U.net] Operation Whiteout-Conquest Large by G-Portal.de
#05 [BP4U.net] Siege of Shanghai
#03 [BP4U.net] Metro only No Grenades + Explosives! 1200T

Need to be updated, they are on outdated versions. The rest of your servers are up to date.

**Comment by BP4U** [comment]
i updated to 6.7.0.77, same error on "03 [BP4U.net] Metro only No Grenades + Explosives! 1200T" but no error on the others. The others are running on a windows server, the "03 [BP4U.net] Metro only No Grenades + Explosives! 1200T", which triggers that error, is running on our linux root. Any idea if that could be the problem?

**Comment by ColColonCleaner** [comment]
Enable plugin debugging on that layer so I can get line numbers from the exception.

**Comment by BP4U** [comment]
done

**Comment by BP4U** [comment]
i switched the layer of our #01 server to another linux server and i got the same error.

**Comment by ColColonCleaner** [comment]
So what is the updated error message?

**Comment by BP4U** [comment]
On both layers 6.7.0.77 is running, error message is
[19:30:04 76] [AdKats] EXCEPTION-67077-D-FetchPlayerStatInformation-HackerChecker64: [Error while parsing player stats data.][System.NullReferenceException: Object reference not set to an instance of an object at PRoConEvents.AdKats.FetchPlayerStatInformation (PRoConEvents.AdKatsPlayer aPlayer) [0x00000] in <filename unknown>:0 ]

**Comment by ColColonCleaner** [comment]
Notice the D in the error message, that will be a line number if plugin debugging is enabled on your layer.

**Comment by BP4U** [comment]
![adkats](https://cloud.githubusercontent.com/assets/3889930/8552958/68fff768-24e0-11e5-9735-b3ec101cc4c5.PNG)

**Comment by ColColonCleaner** [comment]
That's plugin debugging on your client, not on your layer. 

enablePluginDebugging True

in your procon.cfg, or using your layer config control panel if your host provides one.

**Comment by BP4U** [comment]
ok, i checked it in the procon.cfg and it was already activated. Any idea why it's showing the needed infos?

![adkats2](https://cloud.githubusercontent.com/assets/3889930/8554450/5189800e-24ea-11e5-811f-b67a0fc9a7db.PNG)

**Comment by ColColonCleaner** [comment]
It looks like plugin debugging does not function properly on linux layers, which will make it relatively difficult to find the issue. I would sooner suggest not using linux layers with AdKats.

**Comment by ColColonCleaner** [comment]
oops hit the close button

**Comment by BP4U** [comment]
ok, i will continue some testing on other distros and let you know then if i can fix it, but thanks so far for the information.

**Comment by BP4U** [comment]
All I tested today: 
Rootserver 1: Ubuntu 14.04.1, 64 Bit: Error
Rootserver 2: Ubuntu 14.04, 64 Bit: Error
Rootserver 2: Debian Jessie 32 Bit: No Error
Rootserver 2:Ubuntu 14.04, 32 Bit: No Error

So it looks like it is because of the 64 bits...

**Comment by ColColonCleaner** [comment]
Intriguing. I can update this into the docs on next release stating linux x64 is not supported by AdKats.

**Comment by BP4U** [comment]
k, nevermind
