### ISSUE TITLE
Odd Issue

### ISSUE THREAD

**Issue by tngweb** [AdKats/AdKats#784]
Running the latest ProCon and linking into a layer for my BF4 server. The odd issue is that while logged into my layer, the AdKats plugin is NOT being listed, however, If I just log into my BF4 server from ProCon, the plugin is listed. The Plugin IS uploaded to my layer and it is located in the BF4 directory

**Comment by ColColonCleaner** [comment]
What was the issue? Adding to questions section.

**Comment by tngweb** [comment]
Sorry about that, The issue is resolved. I am new to the ProCon thing. I found that the plugin files have to be on my local machine as well as the layer.

**Comment by ColColonCleaner** [comment]
No, that is not true, you only need plugin files on your layer. If you have plugins on your local machine your layer is not doing anything...

**Comment by ColColonCleaner** [comment]
Closing, but you should really find out why you needed to have plugin files on both ends. Your system is most likely not functioning properly.

**Comment by tngweb** [comment]
After some playing around and waiting for my server to come back online, I found that you're right. Like I said, I am new at ProCon.

**Comment by ColColonCleaner** [comment]
Glad you located the issue. Cheers.
