### ISSUE TITLE
Small issue: special players

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#785]
In the special players info, the game played by the special palyers doesn't show up.
In the table "adkats_specialplayers" the "player_game" is empty, while if we search in the table "tbl_playerdata" we can find the "gameid" for the same eaguid.

Can you fix it so we can use this info in the bfadmincp ?

Thank you

**Comment by ColColonCleaner** [comment]
You seem to misunderstand what Game ID in that table does. Game ID there does not identify players, it restricts that listing.

For example, if someone uses an EA GUID in the player_identifier, EA GUIDs are not unique to a game so if you want that listing to only apply on game 1 servers, put 1 in the game column. The same goes for server ID, if you only want that listing to apply to a specific server, specify a server ID.

If you want to find all special players for a certain game only, left join on the playerdata table matching player_id to PlayerID, and only take those from the GameID you want.

Keep in mind, player IDs are already unique by game.

This is explained in the docs: https://github.com/AdKats/AdKats#special-player-lists

**Comment by ChaT0n** [comment]
My mistake :)
I thought that the info "game" in special players in bfadmincp was releated to the info of player_game in the "adkats_specialplayers" table.
So if the gameid for bf3 is 1 and bf4 is 2 and I put the value 1 in "player_game", the whitelist for the specified ea_guid will only apply for the bf3 servers.
can be usefull to restrict the whitelist for some players on only specific games

**Comment by ColColonCleaner** [comment]
Yep it's just so you can restrict special player listings to the games/servers you want, not providing info about the player. Closing question.

**Comment by ColColonCleaner** [comment]
Just a note though, game is already specified in the ACP because player ID implies game. Like i said before, player IDs are unique by game, so if you have a player ID you already know the game. The same player will have different player IDs for their BF3/BF4/BFHL soldiers.
