### ISSUE TITLE
DPS not work

### ISSUE THREAD

**Issue by duna3** [AdKats/AdKats#787]
DPS not work 100% sure

I banned unreason, i never use or have hack

Not how the system works but I think dont it's safe. Considering that there are many values that could give a false positive.
bad connection, packet loss, data is not recorded on the server, netcode, etc. too posible i shot opponet with low health what no register in server.

I need for kill 10 bullest and few times 4 (headshot or low health) and same time lose de connect 10seg and i run in map 200 meter and go back (teleport)

this is the last match on the server where dps ban me

pardo_daxer  bf4

http://battlelog.battlefield.com/bf4/battlereport/show/1/617523866360228416/248089607/

The problem is not to be a single server ban. The problem is being on a list metabans of hacker that many servers use or search Nick and assume that is hacker.

sry my english

**Comment by ColColonCleaner** [comment]
This is a development site, not a place to dispute bans.

However, just to field this to any who might come across this issue, yes you are using a damage mod.

Player: pardo_daxer (http://battlelog.battlefield.com/bf4/soldier/pardo_daxer/weapons/248089607/pc/)
Banned from Breakmaster's servers via the DPS LIVE check.
Hacking/Cheating DPS Automatic Ban [LIVE 100][ACE23-93-69-11-74]

You were averaging 93 damage per shot over 69 kills. 

DPS yes work. Issue closed and locked. Better luck next time.

**Comment by ColColonCleaner** [comment]
This issue has been resolved.
