### ISSUE TITLE
Hacker-Checker settings

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#788]
There is no option to enable/disable the hack-checker, also no enable/disable for for the DPS and no option to choose the value of the DPS trigger.
Using version 6.7.0.87 (noticed this since 6.7.0.80 but forgot to post)

![adkats](https://cloud.githubusercontent.com/assets/13076710/8784560/ffb2fc2c-2f22-11e5-8eae-ec065dd9e7ac.png)

**Comment by ColColonCleaner** [comment]
Correct, the DPS section is always active. The other sections of the hacker-checker are optional and off by default.
