### ISSUE TITLE
mbwhitelist

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#789]
Is this command missing or was it totally removed ?
cause I tried to use it but it didn't work and had no reply from server, so i've checked in the sql file and it wasn't there

Thank you

**Comment by ColColonCleaner** [comment]
Check in your commands table, not the setup script. Is it there?

**Comment by ChaT0n** [comment]
Found it, it is named whitelist and not mbwhitelist, maybe a small correction for a future release

**Comment by ColColonCleaner** [comment]
Odd, mbwhitelist is the correct name. I'll look into that.

**Comment by ChaT0n** [comment]
If u have a few minutes, can u come over ts ?

**Comment by ChaT0n** [comment]
well if you look into the adkats.sql you will find it on line 156 and it is the related one to the remove command on line 213

**Comment by ChaT0n** [comment]
Just to remind you about the player rep that was marked as "???" until we check their profile and then refresh the page, and also the log issue (ex refresh the info to get the player clan or tag)

**Comment by ColColonCleaner** [comment]
How long after you installed stat logger did you install AdKats?

**Comment by ChaT0n** [comment]
maybe 2 or 3 minutes

**Comment by ColColonCleaner** [comment]
updated command name to mbwhitelist
