### ISSUE TITLE
How to read the Magic Bullet Ban?

### ISSUE THREAD

**Issue by wizard45** [AdKats/AdKats#791]
I do I interpret the below ban for the Magic bullet.  What do the numbers mean?

daltonj354  Magic Bullet [LIVE][7-13-0]

**Comment by ColColonCleaner** [comment]
Firstly, please check your plugin logs from when this player was banned. There will be a warning line just after the line which banned him. If that warning line does not contain any weapon codes, and this ban was issued from a server running operation locker you should unban this player. Fire pipes on that map could trigger this ban if that weapon list was empty before a recent patch, 6.7.0.98 to be exact. Your servers may have already updated to this version so don't use your current version number as a reference.

Now on to the code.

7 is just the code for magic bullet. There are several other codes out there but they are not public at this time.
The second number is the number of kills the player got with weapons not on battlelog, basically weapons which don't exist, a universal attribute of the magic bullet hack. This could have been triggered by the fire pipes on lockers until a recent patch if that weapon list warning message was empty.
The last number is the number of hits the player got with weapons not on battlelog. This number will almost always be zero or a number much lower than the previous one.

**Comment by wizard45** [comment]
Here is the code line for the player banned for using magic bullet:
[17:14:44] [AdKats] WARNING: KILLDIFF - [BEST]daltonj354 - (13 Unaccounted Kills)(0 Unaccounted Hits)
[17:14:44] [AdKats] WARNING: Death, Death, Death

This play was banned in the map of Zavod 311

Does this look correct to you?  The mentioned player is banned by BF4DB.com.  A review of his stats suggest that the ban is correct.

**Comment by ColColonCleaner** [comment]
Yes that is a valid ban. 

Any false positives from this system either caused by the fire pipes on lockers or cruise missiles by commanders were ironed out as of 6.7.0.98. Every ban it issues should be valid, however if you have questions on any of them feel free to respond to this issue. I'll keep it open for a couple weeks.
