### ISSUE TITLE
Players joining Teamspeak annoucement in game.

### ISSUE THREAD

**Issue by wizard45** [AdKats/AdKats#792]
With the Monitor TeamSpeak Players feature of Adkats, I would like to know if it is possible to have Adkats announce players who are joining the server’s TeamSpeak in the game text box or have a feature that allows us to either have it announced in the text box of the game and yell feature.  Basically have the option announce who is joining in TeamSpeak within the text, yell,  or both.

It would be nice to have this feature in TeamSpeak since the overlays in TeamSpeak does not seem to work for most people.  If this would be possible, I would be willing to donate to have it done.

**Comment by ColColonCleaner** [comment]
Send $10 to the AdKats donation link and i'll add the feature tonight.

**Comment by ColColonCleaner** [comment]
Could add a customizable message. 

%player% has joined teamspeak!

**Comment by wizard45** [comment]
Sounds great!  Where do I find the donate button?

**Comment by wizard45** [comment]
I found the donate button. I just donated 10.00.  Let me know if you got it!

**Comment by ColColonCleaner** [comment]
All set, i'll work on this tonight.

**Comment by ColColonCleaner** [comment]
Added an initial version of this in 109. Completely untested. Let me know if it works.

**Comment by wizard45** [comment]
Hello,

Thank you so much for your quick efforts.  I regret that it does not work.  When I go to the TeamSpeak Player Join Announcement section, and try to change it from Disable to Active, it will not let me change it to active and then shows the below errors:

07:04:27] [AdKats] ERROR-670110: [Unknown setting when setting teamspeak player announcement.]
[07:05:28] [AdKats] ERROR-670110: [Unknown setting when setting teamspeak player announcement.]

I know your busy with life, so when you get a chance, let me know what to try next.

Thank you for your efforts.

**Comment by ColColonCleaner** [comment]
I missed a single line last night, lol. Let me know if it works now.

**Comment by wizard45** [comment]
Thank you for the quick response.  I'm afraid it is not working.  I can now activate the TeamSpeak Player Join Announcement section, but when in game and someone one joins teamspeak, it does not show anything within the game.  Tried it on say, yell, and tell.  By the way,  I know what say and yell is, but what is 'Tell".  Is that text that only admins can see?

Thank you for your help.

**Comment by ColColonCleaner** [comment]
Tell = Say + Yell

Perhaps we had a misunderstanding, it does not announce when just a random user joins the teamspeak channel. What constitutes a teamspeak player is someone who is both in teamspeak and in game, so they were either in teamspeak and then joined the server or were in the server and then joined teamspeak.That's what the teamspeak players system handles. 

Do you want it to also announce when random people join your battlefield teamspeak channels? Their names may not map to real player names. I could do a search for matching players by IP, but there could be duplicates in your database since they aren't actually in the server.

**Comment by wizard45** [comment]
What I did was join our server, after joining the server I then log onto our team speak.  Nothing showed within the game.  Also, for us, Our team speak is only for clan members so it wont matter.  But the system you have in mind works the same because only clan members will be joining the server.

Again, after your patch, I join my server and entered the game. I then logged on to team speak and it did not show anything in the game about me logging onto team speak.  I don't know if this matters, but I used a different computer for my team speak than the computer for my game.

So the way you have set this up will work for us, because only clan members use our team speak, it is just getting it to show other players is the issue.  Also, I tried this out just we me in server, not other clan mates.  We have 4 servers, and I used the only empty server at the time to test it out.

**Comment by wizard45** [comment]
I just look at the plugin logs and noticed this error code being put up once I activated the display button:

[06:11:11] [TSCV] [Error] Minor Error - Update Teamspeak Information:
[06:11:11] [TSCV] [Error] An error occurred during obtaining an Advanced Client Information.
[06:11:11] [TSCV] [Error] 512: invalid clientID

Not sure if this has anything to do with is.  Looks like this error has been popping up before I updated to latest Adkats with the Team speak display feature.

**Comment by wizard45** [comment]
Well, I spoke too soon. It is working.  Just a long delay from the time a person enters TS and then the game.  But it works!  Thank you for your efforts.

**Comment by ColColonCleaner** [comment]
That can be modified if need be, there is a 5 minute delay to avoid over-querying your teamspeak server, especially if this is done from multiple servers at once. This isn't because teamspeak servers can't handle it, instead because people run anti-ddos protection on their teamspeak servers and many queries can trigger that resulting in your layer IP being banned.

I can add a setting so you can set the speed it checks teamspeak if you want. Defaulting to 300 seconds.

**Comment by wizard45** [comment]
"I can add a setting so you can set the speed it checks teamspeak if you want. Defaulting to 300 seconds"

That would be great!

**Comment by wizard45** [comment]
Any ETA when the multiple speed settings will be added?

**Comment by wizard45** [comment]
Sorry to keep bothering you, but I'm just wondering when the multiple speed settings will be added?

**Comment by ColColonCleaner** [comment]
I'll be able to work on it tonight :)

**Comment by wizard45** [comment]
Thank you!

**Comment by ColColonCleaner** [comment]
I posted an update for this

**Comment by wizard45** [comment]
Thank you for your efforts and time.

**Comment by ColColonCleaner** [comment]
Did reducing the timer work?

**Comment by wizard45** [comment]
Yes it did. I am experimenting with it at this time.  I have reduced it down to 5 secs to see if that is manageable.  

Again, thank you so much for Adkats and for helping me out.

**Comment by ColColonCleaner** [comment]
I should probably put a lower limit on that value so people don't end up shooting themselves in the foot. If you don't see a reason why anything lower than 5 seconds would be required i'll put that as the lower limit.

**Comment by wizard45** [comment]
Let me run it this way for a day or two, and then I will report back if I noticed any issues.  Since we only let clan members use our Team Speak Server, I do not expect there to be any issues but I will let you know.

**Comment by wizard45** [comment]
FYI--I'm still experimenting with reducing times.  I had it set at 5 seconds, but it stopped working.  Not sure why. I set it back to 10 secs and it works.  (When I say it doesn't works, what I mean is that nothing was being displayed when a player joined team speak while in our server).  I am going to try 5 seconds again, but will reboot layer server this time to see if that was why it did not work the first time.

I will keep you updated when I figure this out.

**Comment by ColColonCleaner** [comment]
Keep in mind i've never been able to test this on our servers, our teamspeak server is on lockdown from external queries. All of it should work in theory, and I know the base works, but i don't have any data myself realtime. Please provide as many specific as you can to help solve issues you find with this system.

**Comment by Prophet731** [comment]
Colon, if you need a test server let me know and i'll put one up for you.

**Comment by wizard45** [comment]
For some reason, it is not always working.  It seems that yesterday, our server provider was being DDOS so that might have played a part in why it would not display a person joining the server.  I am setting this to 15 secs to see if that helps.

**Comment by wizard45** [comment]
Seems that 15 seconds is working good.  Again, for the last two days our server provider was being DDOS but they seem to have fixed that issue.  I still think that you should have the default at say 20 seconds and let people chose what works best for them.  I still intend to lower it again within the next few days to 10 seconds to see of it will work.  Will update when I know more.
