### ISSUE TITLE
A18. Internal Hacker-Checker Settings  problem: DSP cant close

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#793]
A18. Internal Hacker-Checker Settings  problem: DSP cant close
![a18](https://cloud.githubusercontent.com/assets/12322494/9060644/408042ca-3ae8-11e5-91a1-c7cb59d86ea9.jpg)

Use version: 6.7.0.115

 I can't close the DPS detection
Can't adjust values.
Only message can be set

**Comment by ColColonCleaner** [comment]
Correct, this is intended.

**Comment by Super-Wong** [comment]
=.=....I can mandatory closed?
Because of my guests were unable to access the server. His data is normal

**Comment by ColColonCleaner** [comment]
This is why it is a test version and not pushed to everyone yet.

What is the ban message it gave him, and which version of the plugin was running at the time?

**Comment by ColColonCleaner** [comment]
Remember, you can /hcwhitelist players from this system. Whitelisted players will not be acted on by it.

**Comment by Super-Wong** [comment]
HK Time [22:09:01 34] [AdKats] INFO: a562401243 auto-banned for damage mod. [QBB951-59-71-14]
I don't see any abnormal data
And I can't give all whitelist.
So I hope it's closed the DPS

![qbb](https://cloud.githubusercontent.com/assets/12322494/9063326/66397e26-3af9-11e5-9fc0-17c8acaf1df2.jpg)

**Comment by ColColonCleaner** [comment]
Don't see anything abnormal? He's getting 60 damage per shot with a 24 damage weapon. That's a 250% damage mod.

https://i.gyazo.com/841d85a3f25aeb5ed5a092e666f38824.png

**Comment by Super-Wong** [comment]
Um.. Yes. I know this value. But from his overall data. He's not a cheating players
Abnormal damage. 
If he went to the HardCore server.. 60 blood
So it is possible that such abnormal DMG?

**Comment by ColColonCleaner** [comment]
Hardcore servers are accounted for. Hardcore servers result in 166% normal damage, or in other words a 66% increase in damage. He's at 250% normal damage, in other words a 150% increase. And that's assuming he played with that weapon ONLY on hardcore servers; even with this 20% HSKR it doesn't add up.

**Comment by ColColonCleaner** [comment]
If you are absolutely certain he is not hacking i would suggest issuing a whitelist, but the system issued a valid ban. That damage combined with the very low accuracy and high KPM is a trigger by anyone's standards.

**Comment by ColColonCleaner** [comment]
Just to be clear, this system is now hardcode enabled because the likelihood of false positives is near zero. If there are cases where they can happen they need to be weeded out before this goes live to everyone using the plugin, not just testers.

**Comment by Super-Wong** [comment]
Ok. Thank you for your answer.. And I'm sorry. Ask an idiot
HOW do add the DPS white list?

**Comment by Super-Wong** [comment]
Are there any other features white list command?
If I have other need to add the white list. Should how to type the command?

**Comment by Super-Wong** [comment]
Ok. I think I know how to add other white list
I have seen that file
And thank you again for your help..
issue close

**Comment by Super-Wong** [comment]
issue close
