### ISSUE TITLE
EXCEPTION-670116-RunAction-ActionHandling37

### ISSUE THREAD

**Issue by Breakmaster90** [AdKats/AdKats#794]
[20:50:52 90] [AdKats] EXCEPTION-670116-RunAction-ActionHandling37: [Command Previous Temp Ban not found in runAction]

AdKats - Advanced In-Game Admin - 6.7.0.116
Procon Layer Hosting by G-Portal.de on Windows Server 2008 R2 System.

Only on this Server happen:
#MhSV Ranked TDM The Block Only | MhSV.de |No Tripmine /No C4
Battlefield Hardline

**Comment by Breakmaster90** [comment]
Oh wait, fail. Is also on the other Servers happen too.

**Comment by ColColonCleaner** [comment]
This is a bug with the BFAdminCP. I've talked about this with prophet and we are working on it.

**Comment by Prophet731** [comment]
What version are you running? The latest develop version doesn't do this.

**Comment by Prophet731** [comment]
Do me a favor and run this query and post back the results.

```SQL
SELECT * FROM adkats_records_main WHERE adkats_read = 'N'
```

**Comment by Breakmaster90** [comment]
+-----------+-----------+--------------+----------------+-----------------+-----------------+-----------+------------------+-----------+------------------+---------------------+-------------+------------+
| record_id | server_id | command_type | command_action | command_numeric | target_name     | target_id | source_name      | source_id | record_message   | record_time         | adkats_read | adkats_web |
+-----------+-----------+--------------+----------------+-----------------+-----------------+-----------+------------------+-----------+------------------+---------------------+-------------+------------+
|   1456318 |        47 |            7 |             72 |              60 | CHUCK_NORRIS_SK |    673183 | MhSV_ll-Stahl-ll |    582982 | Hacking/Cheating | 2015-07-19 00:39:45 | N           |          1 |
+-----------+-----------+--------------+----------------+-----------------+-----------------+-----------+------------------+-----------+------------------+---------------------+-------------+------------+
1 row in set

**Comment by Prophet731** [comment]
Ok, then just run this.

```SQL
UPDATE adkats_records_main SET adkats_read = 'Y' WHERE record_id = 1456318
```

**Comment by Breakmaster90** [comment]
Looks good. Thanks!
