### ISSUE TITLE
Battlereports

### ISSUE THREAD

**Issue by naurel06** [AdKats/AdKats#795]
the goal is to add extended stats available like a battlereport but in database.
The stats would add 2 tables at least in database : extended_playerstats, and extended_weaponstats. The first one will provide the same stats than playerstats but given a specific round (to link with extended_roundstats table) a specific game, a specific server and a specific player. I'd like to see the team and squad for every player too.
The second on will be the détails of kills AND respawn of every players during the game with the same conditions as before and with the time of thoses events.

The record will be activated when an admin type a keyword at the begin of the round (like during the warm up time). Or being always activated ?

**Comment by ColColonCleaner** [comment]
This would be a quite large addition to the plugin. Not something I would plan to do at this time on my own or even with funding, the overall benefit is not worth the effort involved.
