### ISSUE TITLE
IPAPI Issue on 6.6.0.0

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#796]
[18:19:43 89] [AdKats] EXCEPTION-6600-D-HandleException-IPAPIComm86: [Error while parsing IP response information.][System.NullReferenceException: ???????????????
   ? PRoConEvents.AdKats.FetchIPLocation(AdKatsPlayer aPlayer)]

Is a network problem?
But I     ping ipapi.com - t
Return to normal 68 ms delay

**Comment by ColColonCleaner** [comment]
Please update your version with /pupdate and see if this error continues.

**Comment by Super-Wong** [comment]
I use a formal version.. 6.6.0.0
I don't want to use test version. Because he has a bug

**Comment by Super-Wong** [comment]
I use a formal version.. 6.6.0.0
I don't want to use test version. Because he has a bug

**Comment by ColColonCleaner** [comment]
What is the bug?

**Comment by Super-Wong** [comment]
A18. Internal Hacker-Checker Settings problem: DSP cant close #793

**Comment by ColColonCleaner** [comment]
That's not a bug though....

**Comment by Super-Wong** [comment]
T_T   Ok.. He is not a BUG..
But cannot close.. Cause I have been troubled.. So I returned to the 6.6.0.0

**Comment by ColColonCleaner** [comment]
I'll work on making that section slightly more lenient so this won't be an issue for you anymore. It still can't be disabled, but i'll make bans issued by it more hardened. I'll let you know when you can give it a try again.

**Comment by Super-Wong** [comment]
Ok. Thanks for everything you do.. The great project

**Comment by ColColonCleaner** [comment]
Reopened until we can confirm it's resolved.

**Comment by Super-Wong** [comment]
[14:16:28 97] [AdKats] EXCEPTION-6600-D-HandleException-IPAPIComm91: [Error while parsing IP response information.][System.NullReferenceException: ???????????????
   ? PRoConEvents.AdKats.FetchIPLocation(AdKatsPlayer aPlayer)]
[14:16:34 04] [AdKats] EXCEPTION-6600-D-HandleException-IPAPIComm91: [Error while parsing IP response information.][System.NullReferenceException: ???????????????
   ? PRoConEvents.AdKats.FetchIPLocation(AdKatsPlayer aPlayer)]

**Comment by Super-Wong** [comment]
And Cause the loadout check failure

**Comment by ColColonCleaner** [comment]
Wait, you are running 6.6.0.0 with the loadout enforcer? So i'm assuming you have the Integrate with AdKats setting off in LRT then?

**Comment by Super-Wong** [comment]
是的...之前我使用
Adkats  6.6.0.0 + Adkats-LRT 2.0.4.1

but now use Adkats  6.7.0.119 + Adkats-LRT 2.0.4.1

**Comment by ColColonCleaner** [comment]
Ok. you can now enable the integration options in LRT.

Also 119 includes the changes to DPS bans you were looking for.

**Comment by Super-Wong** [comment]
Ok. Thank you very much. I will test later
