### ISSUE TITLE
Hacker-Checker LIVE DPS system issuing reports instead of banning?

### ISSUE THREAD

**Issue by wizard45** [AdKats/AdKats#797]
This morning, I received two separate @player reports as shown below:

AutoAdmin has reported [PxP]PxPxVampPxPx for Damage Modifier Hack Detected [LIVE][M416-48-16-1-33]
Reported 1 times during the current round.
Has 0 infraction points on this server.
Score: 550
Kills: 5
Deaths: 1
Kdr: 5
Ping: 32
SoldierName: PxPxVampPxPx
EA GUID: EA_E52093A209EC9EE4F6F7C558526BDB70
PB GUID: c40185710768a702c6b361809cfea6ce
IP: 96.50.185.70
Country: Canada

Now while in this match, this player changed his name several times.  When I search the name PxPxVampPxPx, BFadminCP could not find it. Only when I search under one of the other names he used (DesertF0Xgameing), did BFadminCP find his player record.  It showed that he had been issued two of the above type AutoAdmin Reports which I have never seen before.  Yet it had not banned him at all. In fact, the only reason he got kicked was because the language filter temp banned him.

My question is how come this player was not banned by auto admin when it detected this hack?  I have been following your posts regarding the Magic bullet hack, but is this one of those?  It seems that the system should ban and let us sort it in the morning!

I like the system of the @player report by auto admin and hope that this could be used in all auto admin bans that it issues when it bans a player for cheating.  Helps admins later review bans to make sure they are valid.

So I quess my main question is how come this guy was not banned?

**Comment by ColColonCleaner** [comment]
He wasn't banned because i'm not sure the [LIVE] system is free of false positives yet. Once i'm sure of that it will be converted back to banning the players.

**Comment by wizard45** [comment]
Thank you for your answer.  Again, for the what its worth department, I think auto admin should send an @player report on ever auto ban.  This is a great way to make sure admins / staff can review all auto bans to confirm that they are valid should they chose to do so.  Or if people do not want to be bothered by them, have this as a option to chose from.

**Comment by ColColonCleaner** [comment]
There is a list of latest bans on the ACP dashboard. I'm not sure of a better way to inform admins since putting a report after every ban would put double records on a player's profile.

**Comment by wizard45** [comment]
Ya I forgot about the ban list.
