### ISSUE TITLE
Live Scoreboard Problem

### ISSUE THREAD

**Issue by pavitra14** [AdKats/AdKats#800]
Gives this error whenever i try to see the Live Scoreboard of any server(Total 3 servers)
"Could not connect to server. It may be offline or port is closed. Please try again later."
I have entered the rcon pass and Battlelog guid(it may be wrong as i dont know from where to get it).
Please help!

**Comment by ColColonCleaner** [comment]
This is not an AdKats issue please contact @Prophet731.

**Comment by Tr3adster** [comment]
Pavitra14

Did you ever get this solved
