### ISSUE TITLE
Adkats database issue

### ISSUE THREAD

**Issue by pavitra14** [AdKats/AdKats#801]
adkats tables not preset or valid in database, have you run the database script yet?......... 
i have this error in procon
i have already run the script in db
how to fix that
i tried reinstalling and changing database many times but no fix

**Comment by ColColonCleaner** [comment]
You have stat logger running without error?

**Comment by pavitra14** [comment]
yes!

**Comment by ColColonCleaner** [comment]
Did you try rebooting your procon layer?

Please send a screenshot of your database structure.

**Comment by pavitra14** [comment]
@ColColonCleaner 
Screenshot 1 - http://prntscr.com/8931h5 
Screenshot 2 - http://prntscr.com/8931tr
These screenshots show my database having Adkats, Xpkiller's Stat logger and BFACP installed!

**Comment by ColColonCleaner** [comment]
@Prophet731 Is there still that issue where the ACP can make a table that's not InnoDB?

**Comment by pavitra14** [comment]
Just for info, I am using the 2.00 Version of BFACP
link - http://bfacp.pavitra14.in

**Comment by ColColonCleaner** [comment]
Yeah, there was a bug the ACP had where it created an adkats_ prefixed table that wasn't in the InnoDB engine. AdKats will refuse to start if any of the adkats_ tables are not InnoDB.

**Comment by pavitra14** [comment]
@ColColonCleaner  Can you tell me the fix?

**Comment by pavitra14** [comment]
There's this table which is MyISAM and starts which adkats_ prefix
http://prntscr.com/893ay5
Will it fix the problem if i change it to InnoDB

**Comment by ColColonCleaner** [comment]
Yes that will fix the problem, that table was injected by the ACP.

Change it, reboot your layer, then run AdKats.

**Comment by pavitra14** [comment]
Doing it now!
But any idea why the plugin was working in Bf4 , not in BF3?

**Comment by pavitra14** [comment]
@ColColonCleaner  HAving this Exception now - http://prntscr.com/893ei8

**Comment by ColColonCleaner** [comment]
That's another bug injected by the ACP when you unban a player from there.

update adkats_records_main set adkats_read = 'Y' where adkats_read = 'N';

That will make the error stop happening.

**Comment by pavitra14** [comment]
@Prophet731 Bro, You really need to have a look at this!

**Comment by Prophet731** [comment]
All those bugs have been fixed in the develop version. I even made a post in the AdKats thread with the proper SQL commands to fix the InnoDB issue. So they are fixed, just not officially released yet.

**Comment by pavitra14** [comment]
You know,  you should add it to the FAQ.
