### ISSUE TITLE
IP-API Failed response message can spam logs

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#805]
ERROR-6800: [ip-api failed to respond with player location information, your layer may be IP banned. ]

ping ip-api.com
is 70ms delay

**Comment by ColColonCleaner** [comment]
I'll look into stopping it from spamming the logs

**Comment by Super-Wong** [comment]
How long will it take it to normal?

**Comment by ColColonCleaner** [comment]
Try putting in the IP address of your layer here first: http://ip-api.com/docs/unban

**Comment by Super-Wong** [comment]
Error: IP XX.XX.XX.XX is not banned

I tried so many IP is prompt no ban
And I also replaced the network IP address
The same mistake
Can I disable IP-API function?

Very annoying.. Has been going all day

**Comment by ColColonCleaner** [comment]
It still happens if you reboot the layer? I'll be posting the patch today.

**Comment by Super-Wong** [comment]
Yes.. I have tried to very many times to restart
Including my routing restart
And external network IP changes
Can't let him disappear.

**Comment by Super-Wong** [comment]
![231](https://cloud.githubusercontent.com/assets/12322494/9701168/e7646e0a-5450-11e5-946a-b3f4216adb50.jpg)

**Comment by Super-Wong** [comment]
Lasted for a whole day again...   T_T

**Comment by ColColonCleaner** [comment]
This is patched in 6.8.0.12. It will now only display the message at 5 minute intervals if connection cannot be made.

**Comment by ColColonCleaner** [comment]
I'll reduce the priority of this as well, removing it as an error message.

**Comment by ChaT0n** [comment]
we are facing the same problem: the ip gets banned. Too many requests ? maybe cause we have 10 procon layers on the same server so with the same ip, and also another community is facing the same problem, but they have only 6 procon layers on the same dedicated server.

**Comment by Super-Wong** [comment]
![31](https://cloud.githubusercontent.com/assets/12322494/10658480/d57d24aa-78c9-11e5-9678-1e1e64754588.jpg)
Problem happen again.. Has been for 2 days.

I have trying to change the Layer external network IP 
But there is no any effect
I also try to use VPN channel.. Also is unable to bring him back
Whether can you let me know.. I cannot link what IP ?
Or I can edit the HOSTS file. To force binding new IP?



Because this problem.. Cause AdKatsLRT cannot be check loadout
I can't run AdKatsLRT alone,
Because when I run AdKats, I can't run AdKatsLRT alone

**Comment by Prophet731** [comment]
@ColColonCleaner 

I could build an API as a fallback when that error happens. Getting a persons location shouldn't be difficult.

**Comment by Super-Wong** [comment]
I will need to download the version number is how many?
This will feedback to my API IP failure? Or other useful information

**Comment by ColColonCleaner** [comment]
Yes, updating to the latest version will fix the IP API issue.

**Comment by ColColonCleaner** [comment]
Also, please update your LRT plugin as well and make sure high request volume is OFF.

**Comment by Camcito** [comment]
Same problem here, AdKats 6.8.0.0

![image](https://cloud.githubusercontent.com/assets/15348417/10768430/c86da0e2-7cbf-11e5-9132-d0c06ba1bcee.png)

**Comment by ColColonCleaner** [comment]
This spam is blocked in the latest test version, please /pupdate
