### ISSUE TITLE
MULTIbalancer and AdKats cannot cooperate with each other

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#808]
Issue one:
AdKats - 6.8.0.0
A16 - Feed MULTIBalancer Even Dispersion List = True

MULTIbalancer - 1.1.6.0
On Whitelist =True

when
Player "A" have MULTIbalancer Whitelist   
and Plaery "A" also auto add to Adkats - A16 Dispersion List
When the player move, will not be able to normal to move to other teams
(or I can manually removing players from "3-3. Verbose Special Player Display" ?)

Issue two:
when
A16 - Feed MULTIBalancer Whitelist = True
A16 - Automatic MULTIBalancer Whitelist for Admins = True

In Game command:    /mbwhitelist perm player ID     is not work.
Don't have any information feedback

**Comment by ChaT0n** [comment]
the command  is named whitelist and not mbwhitelist (small typo mistake was mentionned in another issue)

**Comment by ColColonCleaner** [comment]
It is mbwhitelist for new installs. It used to be called just 'whitelist' because it was the only whitelist at that time. Now that there are a dozen or so whitelists it couldn't be just called whitelist anymore.

Look at the 'Multibalancer Whitelist' command in your command list and check to see which name it is.

**Comment by ChaT0n** [comment]
so editing the 'command_text' in the table  from whitelist to mbwhitelist should be ok, or is it related to something else also ?

**Comment by ColColonCleaner** [comment]
Or just use the command list editor in the plugin to change the text. This is why it's still 'whitelist' for some people, they have made their own changes to the text and I can't just overwrite their work.
