### ISSUE TITLE
wrong DPS automatic ban

### ISSUE THREAD

**Issue by vassiligemini** [AdKats/AdKats#809]
Hello ColColonCleaner ! 
First : sorry for my bad english and my "newbie language" but I'm not aware on admin things. 
My story : 
I have been banned 2 or 3 weeks ago from a server for DPS automatic ban  [M240B-62-111-18], and again from an other server on monday. The thing is that this server is my team's one, but everytime they unban me, I'm banned again when I join.
So, I send you this message because I'm totally sure there's a bug about this automatic ban : you can look at my stats : http://battlelog.battlefield.com/bf4/fr/soldier/vassili_gemini/weapons/364078759/pc/

 I just used the m240b for a little bit more than 1hour with a correct ratio, clearly not a cheater's ratio. Also look at my main stats, I think it's clear I'm just a common player, playing for fun with no importance for the stats.
I checked GGCstream and PBbans lists with my GUID, but I'm not inside, EA also told me to make a request to punkbuster but I've no answer and I really think the problem comes from Adkats plugin : 
because I can play on some other servers, and because my team admins receive this message when I try to join : 
[21:42:07] AdKats > Say > [AC]vassili_gemini was BANNED by admin for  [M240B-62-111-18]
[21:42:07] AdKats > Say > vassili_gemini > Your reputation decreased further from -500 to -512,2

They tried to change lots of settings in procon, but every time I try to join, I'm banned again, even if they delete me from all list they can :  [AdKats] ERROR-68017: [No players matching 'vassili' have active bans.]

The ban messages can change : Enforcing permanent ban on vassili_gemini for  [M240B-62-111-18, or something like "ask to [EDS] and [AC] admins ..." so we are really confused. 

At one moment, they have disabled Adkats plugin and I have been able to play, but the plugin seems to have relaunch by himself so I was banned again directly. 

So, could you help me please ? I think you understand that it's hard to pay for a server and not been able to play on it when you're clear about cheating things. 
We think my ID is on a Adkats list or something and that's why I'm always automatically banned. 
Hum, last thing I have to say, I've a bad connexion, perhap's that's why there was a bug with the DPS ?? 

Thanks in advance for taking some time for me, and sorry for the long post. 
Cheers, 
Vassili

**Comment by ColColonCleaner** [comment]
Please look at the damage stats for your M240B. The simplest way is to use BF4DB/BF4Stats

http://bf4db.com/players/724369
http://bf4stats.com/pc/vassili_gemini

Look down at your M240B. You have 111 kills, 171 hits, calculated to 62 damage per shot, which is a 258% damage modifier. These stats reported by battlelog and based on what the plugin is seeing this is a very valid ban.

If the admin of this server believes you are clean regardless of what battlelog says they can issue
/hcwhitelist perm vassili_gemini
which will whitelist you from bans through this system, but you should keep in mind that mine is not the only system that bans based off of these stats and others seeing this may cause you issues in the future.

**Comment by ColColonCleaner** [comment]
It also appears they have emptied the automatic ban message, which is not a good idea. They should add it back as "DPS Automatic Ban" or something along those lines.

**Comment by vassiligemini** [comment]
Hello and thanks a lot for your quick and clear answer ;)
I really never tried to cheat and never used DPS modifier (I didn't know that was existing before my ban), so what can I do to change this DPS stat ? 
if I play again with the M240B, my new kills will make this % going down ? 
is it as simple as this ?
or is there an other way ?


Date: Wed, 16 Sep 2015 15:47:49 -0700

**Comment by ColColonCleaner** [comment]
Yes, playing more with that weapon will make the overall damage percentage go down. You just need to get a lot more hits than you do kills, so shooting people in the legs is an easy way to do it.
