### ISSUE TITLE
EXCEPTION-6800-D-UploadStatistic-DatabaseComm46: [Unexpected error uploading statistic.][MySql.Data.MySqlClient.MySqlException

### ISSUE THREAD

**Issue by mikedevita** [AdKats/AdKats#819]
> [13:18:23 71] [AdKats] EXCEPTION-6800-D-UploadStatistic-DatabaseComm46: [Unexpected error uploading statistic.][MySql.Data.MySqlClient.MySqlException: Cannot add or update a child row: a foreign key constraint fails (`proconstats_prod`.`adkats_statistics`, CONSTRAINT `adkats_statistics_target_id_fk` FOREIGN KEY (`target_id`) REFERENCES `tbl_playerdata` (`PlayerID`) ON DELETE NO ACTION ON UPDATE NO ACTION)
   at PRoConEvents.AdKats.SafeExecuteNonQuery(MySqlCommand command)
   at PRoConEvents.AdKats.UploadStatistic(AdKatsStatistic aStat)]

I had to restore a database of stats to two days prior and now i'm getting these errors at the end of a round... any ideas on how i can delete this foreign key constraint?

**Comment by ColColonCleaner** [comment]
Did you restore your database without shutting down your layers first?
