### ISSUE TITLE
Public Tables

### ISSUE THREAD

**Issue by smogsy** [AdKats/AdKats#820]
This is slightly out of your realm in terms of Functionality feature, but i'm sure Prophet could link it into BFadmincp functionality at some point. & its easy $

I want 2 .php files that are self sufficient. (can be run from anywhere & work, so db connection in same file)

Simple  table Borders are ok, No need for .CSS at this point as i can use my .CSS

File 1.
Contain a simple table showing Everyone in a certain Group in this case VIP
Fields
Name
Start date (not sure if possible)
Expiry date
if you can think of any other good fields please add

File 2.
Contain a simple table showing Everyone That's currently a  server Populator & not a Admin 
(if possible also not a certain Clan tag in this case AUK)

Fields
Name
Start date (not sure if possible)
Expiry date#
if you can think of any other good fields please add

shall send you pp donation now, if you fill this too easy of a $ please do my other populator feature request for in game at some point no huge rush

**Comment by ColColonCleaner** [comment]
This is something that prophet would need to handle. Closing here.
