### ISSUE TITLE
Loadout Enforcer has stopped catching prohibited item

### ISSUE THREAD

**Issue by dap52** [AdKats/AdKats#822]
I have (both) C4 turned off on our server. But for the last few days some players are able to join with it while others are not. We first noticed it on 15 Oct. This seems to be random, and most players are newbies. But I haven't been able to find a pattern yet. 
 My AdKats is version 6.8.0.56 (and has just updated about 5 min. ago)
 My AdKatsLRT is version 2.0.4.1
I can send log files if needed.

Thanks,
David P

**Comment by ColColonCleaner** [comment]
I would suggest putting further inquiries on the LRT repository, not here.

Please update to the latest version of LRT and turn on high request volume.

**Comment by dap52** [comment]
I am a forum noob so I am not up on the proper etiquette you seem to require. I thought it might be a bug so I posted it here.
I have told you about what we are experiencing, and I have offered any further info we have available.
You got the message. But protocol seems to take precedence over facts here. If you need anything from our server just email me here: bubbasplacegaming@hotmail.com

**Comment by ColColonCleaner** [comment]
Wait what? All I asked is that you update your LRT plugin, you are 21 versions behind the latest version. I'm not sure what protocol you are referring to.

**Comment by dap52** [comment]
I thought it updated automatically...and I don't know where to download it.

**Comment by ColColonCleaner** [comment]
It does update automatically if you have a current token, github expires them after a week.

You can go here to grab a new token: https://github.com/AdKats/AdKats-LRT/raw/master/AdKatsLRT.cs

The token is generated in the URL. Drop that into AdKats and it will auto-update LRT. Then just reboot your layer.

**Comment by dap52** [comment]
Thank You,
I'll let you know what the outcome is, but the update thing was obviously the problem. Sorry for the mis-post. This is my second one... I am a forum noob, seriously.
Have a Good one,
David p

**Comment by dap52** [comment]
I'm sorry Daniel, but the link you furnished put me in the AdKats-LRT.cs file. I have groped around in github trying to find a token since your last response. I guess that sounds silly to a github user, but I will save any shortcut that will just get me to where I can acquire this token.

**Comment by ColColonCleaner** [comment]
I would just post a token but the problem is this is a public repository, anyone can see it. Send me a PM on the rcon forums and i'll respond with the token.

**Comment by dap52** [comment]
ok.

**Comment by wizard45** [comment]
When you clicked on that link and it takes you to the "AdKats-LRT.cs file", just look in the url box and click on the url address in your browser and you will see the url address change with the token inside of it.  Hope that helps!  I had the same problem too at first, then I was able to see that the token would show up after you click on the url address.

**Comment by ColColonCleaner** [comment]
I sent the token privately.

Yes wizard, i prefer to show people how to get their own tokens so I don't need to send new ones manually when they expire. Perhaps I wasn't clear with explaining how to do that though.

**Comment by dap52** [comment]
I have the token mystery solved! Thanks Wizard45 for that clue, and thank you ColColonCleaner for your infinite patience and great work. I will watch for this problem to re-occur, but I'm not expecting to see it, having been that far behind in updates. I will follow up in the LRT forum if need be.

Thanks Guys
