### ISSUE TITLE
Date Tome Conversion Issue

### ISSUE THREAD

**Issue by DevilOmaxe** [AdKats/AdKats#823]
![received_10205146821086239](https://cloud.githubusercontent.com/assets/15216977/10613682/d3b878b0-7773-11e5-8b2f-e2dfc0628f96.jpeg)

Started experiencing this issue.. Any possible fix? MySQL Server is hosted on Linux but i don't have much knowledge about it.

**Comment by ColColonCleaner** [comment]
Hmmm, it sounds like a DB issue since I haven't seen this reported before. Are you still experiencing this?
