### ISSUE TITLE
Hide chat info

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#830]
The plugin delivers to the admins in game some info about the ping kick average, and populaters success, ...., but most admins in game don't pay attention to this.
Would be it be possible to add an option to hide those messages in the game's chat and leave it just in the procon console, or an option to enable/disable those info messages ?

PS: might be double posted cause of a copy/past over teamviewer

**Comment by ColColonCleaner** [comment]
Population success is because you populated the server, it's a message given in accordance with reputation increasing.

I will remove the message about ping kick average though, that was really only added as a debug message for our servers.

Cheers.
