### ISSUE TITLE
EXCEPTION-68079-FetchPlayerBattlelogInformation-BattlelogComm81

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#831]
![3123](https://cloud.githubusercontent.com/assets/12322494/11144321/b7e4c49c-8a36-11e5-896d-3d2a5e87d145.jpg)

Seems the player changes the game ID.. But why has been repeated errors?
Very annoying

**Comment by ColColonCleaner** [comment]
This should be fixed now.
