### ISSUE TITLE
SQL Update Script

### ISSUE THREAD

**Issue by Prophet731** [AdKats/AdKats#833]
The script is adding duplicate keys to the tbl_chatlog table on our database causing the index to be larger than need. You should check this and make sure it doesn't make those keys if they already exist.

**Comment by ColColonCleaner** [comment]
What duplicate key are you talking about?

The insert statement I use doesn't include any key columns.

INSERT INTO `tbl_chatlog` 
(
	`logDate`, 
	`ServerID`, 
	`logSubset`, 
	`logPlayerID`, 
	`logSoldierName`, 
	`logMessage`
) 
VALUES 
(
	UTC_TIMESTAMP(), 
	@server_id, 
	@log_subset, 
	@log_player_id, 
	@log_player_name, 
	@log_message
)

**Comment by Prophet731** [comment]
I mean the actual KEY on the column, not the insert statement. That update statement is being ran a few times and it's causing it to add it over and over even though it exists already.

https://github.com/AdKats/AdKats/blob/master/adkatsupdates.json#L23

**Comment by ColColonCleaner** [comment]
Ah, misunderstood. Looks like the check for the key already existing is failing.
