### ISSUE TITLE
special players management question

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#836]
How will the plugin handle it, if we have two different latency whitelisting for the same player id, one on a specific server and one on all the servers both have same starting dates but different ending dates ?
Will the plugin find it wrong if the player connects to the server 2 where he will have a double entry for the ping whitelist  (server id 2 and NULL)?

specialplayer_id  player_group   player_id  player_game  player_server  player_identifier  player_effective     player_expiration    
----------------  -------------  ---------  -----------  -------------  -----------------  -------------------  ---------------------
               1  whitelist_ping      16423       (NULL)              2  TesT          2015-11-20 12:03:34  2016-01-30 12:03:34  
               2  whitelist_ping      16423       (NULL)             (NULL)  Test          2015-11-20 12:03:34  2015-12-30 12:03:34

**Comment by ColColonCleaner** [comment]
That is an invalid configuration, if you want it for specific servers you should have an entry for each server it should apply to. If you want it for all servers, only one entry with a null server ID is the correct config.

I don't know how the plugin will act if it gets something else.

**Comment by ChaT0n** [comment]
Will give it a try during next week and I will give you a feedback

**Comment by ChaT0n** [comment]
Ok, if the dates are following each other for example all server till end of november and 1 sever ending  at the end of december, the plugin was alway giving the reserved slot without any problem. I think the value for all server is iverriding the 1 server.

I will try the opposite configuration next week
