### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by EntraVenuS** [AdKats/AdKats#837]
can i set the balancer up to disperse clan members evenly on low population but then once full they can stick together, As its difficult seeding a server when clans can dominate 1 team causing potential players to rage quit. 

Thanks in advance

**Comment by wdfstryfe** [comment]
This would be nice to have regardless of the population.  Keep clan members evenly spread out between teams based on skill or some other stat.

**Comment by ColColonCleaner** [comment]
This should be already in the system now that the team power monitor is there.
