### ISSUE TITLE
ping limit for whitelist

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#838]
Would it be possible to add a value also for whitelisted players (reserved slots, auto balance, ...)
Cause some persons who have reserved slot, or admins sometimes come to play while doing something else (like dl) and their ping goes above 300, 350, and this have an impact of the high tickrate servers.

So it would be nice to have a high ping limit for the whitelisted or admins, like one value that applies to them  and depending ont he server population, and seperated from the from the settings of the other players.

Thank you

**Comment by ColColonCleaner** [comment]
I don't think this can be applied, there is a whitelist for ping if you would like to whitelist your admins.
