### ISSUE TITLE
EA Team Balance with AdKats 

### ISSUE THREAD

**Issue by HitchItch** [AdKats/AdKats#841]
Has anyone found a way to disable the EA team balance permanently for BF4?

procon/server settings/gameplay/team balance

We have to uncheck this box multiple times a day, it somehow turns itself back on.

This totally screws up adkats team balance, the teams become horribly unbalanced and people start to leave the server. IE: 12 vs 4

I cannot find any way to keep this box unchecked.

Im hoping someone has a solution, this thing drives me nuts

Thanks

Hitch

**Comment by ColColonCleaner** [comment]
Discussed on the MyRcon forums.
