### ISSUE TITLE
CIDR banlist (request)

### ISSUE THREAD

**Issue by hit757** [AdKats/AdKats#842]
Hi,
I'd like to propose taking under consideration one feature which could be useful.

Assuming some cheaters/trolls create another "test" accounts after being banned,
the only solution is ban on IP. What if they're coming from dynamic IP range and each time
they reconnect to the Internet they have different IP?

I'd like to have possibility to add any IP range (preferably in CIDR notation) to some kind
of blacklist, and when player joins the game his IP would be compared to that list.
If it's within any blacklisted range, that single IP would be banned. This way you can base
on built-in ban system and only thing that would have to be done is a piece of code
to manage additional IP range blacklist.

Example: someone is violating the rules, you ban him and 5 minutes later he's back
with slightly different IP, let's say 84.44.225.43 (I picked it randomly to make an example).
You can see it's dynamic range.

$ whois 84.44.225.43
[...]
inetnum:        84.44.224.0 - 84.44.255.255
netname:        NC-DIAL-IN-POOL
descr:          NetCologne dynamic IP Pool
[...]
route:          84.44.128.0/17
descr:          NetCologne PA space
origin:         AS8422
[...]

Let's assume I don't want anybody from that ISP on my server (collective responsibility).
I'd like to have possibility to blacklist whole 84.44.128.0/17 range, which is:

$ ipcalc 84.44.128.0/17
Address:   84.44.128.0          01010100.00101100.1 0000000.00000000
Netmask:   255.255.128.0 = 17   11111111.11111111.1 0000000.00000000
Wildcard:  0.0.127.255          00000000.00000000.0 1111111.11111111
=>
Network:   84.44.128.0/17       01010100.00101100.1 0000000.00000000
HostMin:   84.44.128.1          01010100.00101100.1 0000000.00000001
HostMax:   84.44.255.254        01010100.00101100.1 1111111.11111110
Broadcast: 84.44.255.255        01010100.00101100.1 1111111.11111111

I hope I'm not the only one who'd love that feature.

**Comment by ColColonCleaner** [comment]
This would require a lot of changes to tracking and management for bans.

**Comment by hit757** [comment]
Looks like I was the only one interested in having that feature.
In that case it's not worth to do it.
