### ISSUE TITLE
Feature request Pushbullet

### ISSUE THREAD

**Issue by SharpShotGif** [AdKats/AdKats#846]
can we get Pushbullet support for !admin and !Report

https://docs.pushbullet.com/

**Comment by ColColonCleaner** [comment]
This would need to be a funded request as this will not be used internally by us.

**Comment by Prophet731** [comment]
I could implement this into the ACP as well, im currently testing out [Pusher](https://pusher.com/) for a realtime chat/online users for it.

**Comment by SharpShotGif** [comment]
Donated some money. I was hoping you could make it send an message when someone has used !report or any words in a list. This could allow admins get notifications on pushbullet when they are needed on the server.

**Comment by ColColonCleaner** [comment]
Alright, i'll look at their API tonight and see what I can do. If all looks good i'll transition this to a funded request.

**Comment by ColColonCleaner** [comment]
What do you guys know right now about pusher vs pushbullet?

**Comment by SharpShotGif** [comment]
I have not used pusher sorry

**Comment by Prophet731** [comment]
No it's 100 max simultaneous connections and 200k messages per day. The connections part is something I would be using. So you can have a max of 100 clients (new tab window is a client). That wouldn't be limiting for colon.

**Comment by ColColonCleaner** [comment]
Planning on getting this developed tomorrow.

**Comment by Prophet731** [comment]
Unrelated with this but what about the settings restructuring?

**Comment by ColColonCleaner** [comment]
I've added code for this through pushbullet but it appears to be having authorization issues. Gonna try finding out why.

**Comment by SharpShotGif** [comment]
Any luck with this or still having problems?

**Comment by ColColonCleaner** [comment]
A lot has been going on. I'm hoping to have this closed out this weekend. Sorry for the delays.

**Comment by SharpShotGif** [comment]
Oh don't worry about it. Its just a request I can understand if it doesn't get implemented.

**Comment by ColColonCleaner** [comment]
Finished adding this feature. Please confirm @SharpShotGif so it can be closed. Cheers.

**Comment by SharpShotGif** [comment]
Sorry am going to be a pain our server does not allow the mod to update by using /pupdate I can however update by uploading it by ftp but i need a link to the download

**Comment by ColColonCleaner** [comment]
I'll look into that tonight.

**Comment by ColColonCleaner** [comment]
Fixed that issue.
