### ISSUE TITLE
DPS Ban In Battlefield 4 

### ISSUE THREAD

**Issue by CapeCod** [AdKats/AdKats#849]
As of the last couple of weeks I have been getting banned from servers for  Stated reason: DPS AdKatz Automatic Ban [M416-68-53 [perm][AutoAdmin].I have tried Contacting EA, Fairfight, Dice ect. and at least 4 owners  of servers to try to resolve this issue. They unban me from there server and as soon as I try to get back on same message. I would not be spending hours and hours of my time trying to get this resolved if I was any kind of cheat. Please take a look. http://battlelog.battlefield.com/bf4/soldier/CapeCodKiller/stats/318761388/pc/ There is clearly something wrong with the auto ban plugin. 

I would really appreciate any help. BF4 is about the only game I play and I'm almost to the point that I can play it anymore. Thx for your time

CapeCod

**Comment by ColColonCleaner** [comment]
There is not something wrong with the plugin. According to your stats on battlelog you are dealing 68 damage on average with the M416.

If they are convinced you are clean then they can use the following command to whitelist you from being banned:

/hcwhitelist perm KapCodeKiller 

This is not a place to dispute bans. Please ask the admins you're dealing with to read the manual for AdKats so they know about these commands and how their system works.

**Comment by CapeCod** [comment]
Seems very odd that the plugin would perm ban someone that has use a weapon for not even an hour. Is there a way to change that in the plugin so you have to have at least played with a weapon for a certain duration of time before it starts banning people. You have no Idea the hell I have gone through because of this.

Thanks so much for the info and your time.
CapeCod

**Comment by ColColonCleaner** [comment]
It has a minimum kill count for DPS bans, which is 50. HSK bans have 100 minimum kills, and KPM bans have 200 minimum kills. Each is an optimal number based on frequency and reliability of bans at their respective kill counts.

Your weapon over 53 kills was dealing 283% of the M416's normal damage output. This is why the plugin banned you.

**Comment by CapeCod** [comment]
I must have been on a locker/metro server when I use the guns. I don't remember ever using it but that's the same with most weapons lol. 

Thank you for your time I at least now what why and how to get it corrected

Thanks again Cape Cod
