### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wizard45** [AdKats/AdKats#850]
Would it be possible to have Adkats have a feature to auto kick player with a certain level of KDR in their Battlelog?

For example, to have an feature where one could select the KDR limit of a player and then auto ban the player if that player is over the set KDR.

If this feature is possible, I would fund it.

Thank you and Happy New Year.

**Comment by SharpShotGif** [comment]
You can do this with insane limites

**Comment by wizard45** [comment]
I am currently not running insane limits and would prefer not to have to add another plugin if adkats can do it.  I want to thank you for your comments because  I was not aware that Insane limits could do that and I might have to resort to that if necessary.

**Comment by ColColonCleaner** [comment]
You can already do this via an autoadmin plugin like insane limits, and I think someone already has that written up.

I will not be adding functions to AdKats that can easily be done with another, more adapted plugin. Not wanting to run another plugin is not a good enough reason for this to be implemented here.

The only times i've absorbed functionality from other plugins is when the functionality needed a pretty big facelift, or more features that were unavailable with that plugin. Doing KDR kicking is easy with IL.
