### ISSUE TITLE
limit of sniper rifles and DMR

### ISSUE THREAD

**Issue by GAZGAZ** [AdKats/AdKats#851]
Is it possible to implementation the limit of sniper rifles and DMR in your plugin. What would be in excess of the number of sniper rifles in the game plug-in would react Kill

**Comment by ColColonCleaner** [comment]
AdKats does not control weapon usage, outside of our servers anyway.

If you are talking about LRT, the loadout enforcer, there is currently not a way to limit the number of weapons per team or categories per team. That is another endeavor that would take time to implement. Please continue this discussion there if that's what you're interested in.
