### ISSUE TITLE
auto-surrender bug

### ISSUE THREAD

**Issue by Hodor228** [AdKats/AdKats#854]
After restart procon i have that values for some minutes and NUKE goes crazy:
https://forum.myrcon.com/attachment.php?attachmentid=4191&d=1451554101

After some minutes after restart valuses become a normal state automatically:
https://forum.myrcon.com/attachment.php?attachmentid=4190&d=1451554084

**Comment by ColColonCleaner** [comment]
Should be fixed now. Please let me know if it actually is.

**Comment by Hodor228** [comment]
Fixed

**Comment by Hodor228** [comment]
Bug is back 6.8.1.106

**Comment by ColColonCleaner** [comment]
This shouldn't be an issue anymore. Please reopen if necessary.
