### ISSUE TITLE
Feature request: Auto Nuke threshold

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#856]
On B25, when setting "Nuke winning ..."
a) show another value that says "Disable nuke when ticket lower than"
and
b) Disable auto-nuke after X amount of nukes

reference: https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-8-0-0&p=130013&viewfull=1#post130013

**Comment by ColColonCleaner** [comment]
These settings have been added. Please let me know if they work to your liking.
