### ISSUE TITLE
Issue with email

### ISSUE THREAD

**Issue by Sno69** [AdKats/AdKats#859]
ColColonCleaner,

 Having issues setting up my email sending. Followed the instructions, but am erroring out.
 Here it is, any suggestions?

 Demand
 The type of the first permission that failed was:
 System.Net.Mail.SmtpPermission
 The Zone of the assembly that failed was:
 MyComputer]

 I am using gmail,
 have it to smtp.gmail.com, port 587, and ssl set true.

 BTW, love the plug in.

 Sno69

**Comment by ColColonCleaner** [comment]
You need to set up gmail to accept connections from this application with a unique password. This is a setting in gmail.
