### ISSUE TITLE
Preset Message Spam

### ISSUE THREAD

**Issue by sammad143** [AdKats/AdKats#862]
My server uses manual nukes only by admins, is there any provision in Adkats via which the admin can issue a command like /tell 8 5
8 being the preset message-"Nuke incoming! Brace yourselves!" and 5 being the number of times this message is spammed?
It will be very helpful to add a suffix Numerical to preset messages in order for us to make a quick repetition which is required in many situations.
Please guide me if such a system is already present.

**Comment by ColColonCleaner** [comment]
This has been added. Nuke countdown is available in the latest test version.
