### ISSUE TITLE
Manual and All Server bans

### ISSUE THREAD

**Issue by Soulzz** [AdKats/AdKats#863]
Hello,

I would like to request a feature, similar to that of RCONNET.de, where we can choose to do a manual server ban via the web, or an all server ban.  Currently, if you set the server ID's to the same identifier, all bans entered will go across all servers if it is configured as such.  I would like the ability to have separate server identifiers, but the ban should either have the option of being on all servers, or one server.

Thank you.

**Comment by iraqiboy90** [comment]
It's already mentioned here: https://github.com/AdKats/AdKats/issues/740

**Comment by Soulzz** [comment]
Sorry, I didn't see that.  If this requires funding, how much money is needed?

**Comment by ColColonCleaner** [comment]
I have so many things to catch up on i can barely keep up with it. I can't really do a commitment right now for how fast it would be implemented.

This would affect both the BFAdminCP and AdKats with how bans are parsed, and it wasn't built to operate this way.

I'll comment back on #740 and close this ticket.
