### ISSUE TITLE
Seeding Feature request

### ISSUE THREAD

**Issue by EntraVenuS** [AdKats/AdKats#865]
Ok i would like to know if this can be done, If it can i will pay for this feature.

I need to be able to monitor players on a empty server. 0 to 20 players max who seed an empty server.  

Basically i want to reward players who help seed servers on a daily basis. (But once 20 players are met on the server i need this to stop following players), needs to give hours and mins in the output.

This needs to be able to output to this plugin lets say https://forum.myrcon.com/showthread.php?6854-Stats-webpage-for-XpKiller-s-Stats-Logger-Plugin-(Updated-1-21-2015) I will ask ty_ger07 if he can accommodate this output on his plugin. 

Reason for this .. I want to be able to see the top -10 seeders for the month and give them free VIP Access.
In game commands needed  !seed this will display the current top 10 current seeding.

As i have stated I'm willing to pay for this feature I would just like to know if it can be done 
Thanks Entra

**Comment by ColColonCleaner** [comment]
Yes, this can be done, and most of the stuff you want is already in the plugin. It only goes back two weeks though, not a month, but that can be updated. The plugin can already assign automatic reserved slots to people who seed over X times in a period, but there is no setting to only allow the top 10 in that list to have reserved slots. Also there is no !seed command.

So the basic system you want is already there, just needs some new stuff added to it. Look at the populator monitor in the settings, i believe it's one of the B27 sections.

**Comment by ColColonCleaner** [comment]
This is already added in the populator monitor.
