### ISSUE TITLE
adkats.sql error

### ISSUE THREAD

**Issue by CheckaWiemi** [AdKats/AdKats#866]
mySQL Version:
Variable_name 	Value 	
innodb_version 	5.5.47
protocol_version 	10
slave_type_conversions 	
version 	5.5.47-0+deb8u1
version_comment 	(Debian)
version_compile_machine 	x86_64
version_compile_os 	debian-linux-gnu

I always get an error when i try to import adkats.sql or when i try to run the command via SQL console:

SQL-Befehl:

REPLACE INTO `adkats_rolecommands` VALUES(2, 78);

REPLACE INTO `adkats_rolecommands` VALUES(2, 79);

MySQL meldet: Dokumentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `adkats_rolecommands` VALUES(2, 79)' at line 3 

I run the latest version of Statslogger first and that works great in this DB and then I try to run adkats.sql but get everytime this error.
I don't know what to do :-/

**Comment by ColColonCleaner** [comment]
I'm assuming your are using the latest version of PHPMyAdmin? There is a bug with that system that breaks those lines, others have seen this many times before. There isn't anything wrong with the SQL syntax, just something on their end. Please try running the script with another client such as MySQL Workbench, cheers.

**Comment by CheckaWiemi** [comment]
Hey ColColonCLeaner. Thanks a lot for your reply.
So for Workbench I need at least SSH for my DB but I have no SSH for this :-/
Everytime I want to create a connection to the DB Workbench says that there's a SSL problem -.-
So iI guess I have to find another way.
Thanks for your help!

**Comment by CheckaWiemi** [comment]
And I also talked to my provider and he told me not to use a "changing" delimiter, I should use a kind of "uniform" delimiter and then it should work. But I don't know how to change it or if it makes sense?

**Comment by CheckaWiemi** [comment]
Okay guys, I found a solution. I used HeidiSQL and started the script with that tool and it works great :-)

**Comment by ColColonCleaner** [comment]
Uniform delimiters are not possible for these type of queries, multiple levels required different delimiters. Glad you were able to solve the issue. Closing.
