### ISSUE TITLE
New weapon stats required for BFHL DLC

### ISSUE THREAD

**Issue by mambochambo** [AdKats/AdKats#871]
Hello ColColon- im new at BFHL- i got ADKATs Warning- could not find damage stats http://prntscr.com/abenaz
ive uploaded the latest Adkats-master into my bfhl folder to my layer- is there anything im missing-
can you please tell me, where to put the files. Ive uploaded the whole folder content into the bfhl plugin folder. Is that right? 
I checked the adkatsweaponstats.json for entries, but for the entries shown above, in my screenshot, there is no entry. Is that due to the new DLC?

**Comment by ColColonCleaner** [comment]
handguns:improvised-gun
machine_pistols:mp9
smg:mx4
assault_rifles:aug-a3
handguns:dual-vz-61
assault_rifles:rpk-74

**Comment by ColColonCleaner** [comment]
handguns:improvised-gun 18/10
machine_pistols:mp9 20/10
smg:mx4 20/8
assault_rifles:aug-a3 25/18
handguns:dual-vz-61 15/8
assault_rifles:rpk-74 24/12

**Comment by ColColonCleaner** [comment]
Added.
