### ISSUE TITLE
Feature Request: Add option for auto-nuke countdown before it fires.

### ISSUE THREAD

**Issue by CEBEP78** [AdKats/AdKats#876]
Improving please AUTO-NUKE, using the command .cdown all 10 AUTO-NUKE, make notification to the NUKE, and that many players do not understand what happened, and why they died, and the team does not understand that the enemies are dead, and we must attack !!!!

**Comment by CEBEP78** [comment]
Hi, I'm very sorry, I do something wrong written or described are not they? Sorry for bad english

**Comment by CEBEP78** [comment]
5 EUR? 
7 EUR?

**Comment by ColColonCleaner** [comment]
I just haven't had the spare time to do everything. There is another feature someone paid for that is taking my time. If you want to send a donation I can push this toward the top of my list.

**Comment by CEBEP78** [comment]
yes I want to. How many ?

**Comment by ColColonCleaner** [comment]
What you said is fine, send that and i'll fit it in to my schedule this week. The donation link is in the AdKats thread.

**Comment by CEBEP78** [comment]
Done

**Comment by ColColonCleaner** [comment]
Added.
