### ISSUE TITLE
Create a modified report/calladmin command which triggers emails/notifications but doesn't require a targeted player

### ISSUE THREAD

**Issue by D3licat3** [AdKats/AdKats#878]
Is it possible to implement a command in AdKats with which a player can just contact an admin without having to write a playername (e.g. !calladmin something is wrong...). If this would be forwarded via PushBullet it would be a great support for offline admins to react via mobile devices if something goes wrong with the server.
Thank you!
Dete96

**Comment by ColColonCleaner** [comment]
I will need to discuss this with @Prophet731 since his system works off of player_calladmin in some cases.

If this command was revamped to just call admin attention not directed at a player what would need to change on your end for that?

**Comment by Prophet731** [comment]
@ColColonCleaner 

Do you have time on saturday to doing some planning for this and a couple other things?
