### ISSUE TITLE
Feature Request: Notify donators of expiring donation.

### ISSUE THREAD

**Issue by wdfstryfe** [AdKats/AdKats#880]
I had a user ask me if there was a way to notify them once their reserved slot was about to expire.  I know it would require adding a field in the role for email address and fields for how long before it expires to notify the user.  It would be nice to have to let people know when their slots are about to expire.

**Comment by ColColonCleaner** [comment]
How would you like them to be notified? An in-game message when they first spawn within X days of their expiration?

Email addresses can be done and emails sent if you want that.

Would you like a command that lists off the persons groups and when they expire? Like how long till their reserved slot, spectator slot, balance whitelist, etc expire?

**Comment by wdfstryfe** [comment]
In-game message that triggered like 7-14 days before it expired would be fine but maybe have a variable that you can configure the days till it expires.  Or have it do 1 notification 7-14 days and then each day they join after their first kill or something along that lines until it expired.  A command to show a list would be a nice addition as well.

**Comment by ColColonCleaner** [comment]
Yeah, I can add a config for the days till expiration where it will begin notifying.

It could be on their first spawn a few seconds after their first spawn message/battlecry go off.

Now, we just need to figure out how it would work for multiple perks with different expiration dates. For example, their reserved slot could end in 5 days, but their balance whitelist could still have 10 days left. How would both of those be displayed?

Maybe the message on their first spawn could just say 'You have perks expiring soon! Use !perks to see when they expire!'

Then we wouldn't have to worry about that first message and just put all the info in the !perks command, or whatever we end up calling it.

**Comment by wdfstryfe** [comment]
That works for me!  Normally I have them both setup at the same time.  But, that idea does work for me.  Reserved expires in X days Whitelist in X days.

**Comment by ColColonCleaner** [comment]
It would probably be on multiple lines, with like a 1 second interval between posts.

A player example:
!perks
Reserved Slot: 5d19h
Balance Whitelist: 10d19h

An admin example (in they case they have these perks forever):
!perks
Reserved Slot: Never Expires
Spectator Slot: Never Expires
Whitelist 2: Never Expires
Whitelist 3: Never Expires

Durations longer than 2 years the plugin displays as forever, so i'll take that same thing here.

Anything else to add? This is smaller than the other one so I'd be fine with like $10-15 for it.

**Comment by wdfstryfe** [comment]
That sounds good to me! I'll send the money over now. :)

**Comment by ColColonCleaner** [comment]
Thanks for the bonus. Marking funded for completion shortly.

**Comment by wdfstryfe** [comment]
No problem! You do great work and I'm happy to help out where I can. :)

**Comment by ColColonCleaner** [comment]
Working on this now.

**Comment by ColColonCleaner** [comment]
This is added and reasonably tested. Please let me know if it's to your liking. Cheers.

**Comment by ColColonCleaner** [comment]
The settings for enabling the warning of expiration are in the A12 section. It defaults to 7 days for the notification.

**Comment by wizard45** [comment]
I have set the setting for true on this feature and I see nothing in the server when I join.  I am an admin and on the Reserve list indefinitely.  What am I doing wrong?

**Comment by wdfstryfe** [comment]
It only works for people that are set to expire in 7 days.  So, if you're an admin and have an indefinite reserved slot you should never see this message. On the other hand if you take your admin slot away and changed your reserved slot to let's say 7 days the next time you join you should see a message.

**Comment by ColColonCleaner** [comment]
Correct. It can be used by admins to see what perks they have active but most of the admin level perks are permanent.

There are more things users can be assigned, like auto-assist blacklists, report blacklists, and other bad things. However, right now the !perks command does not return bad or detrimental groups, only good ones or things people should want.

Please let me know how it's working after some testing on your servers stryfe. Once again life has been busy so this took more time to start.

**Comment by wdfstryfe** [comment]
Small request if it can be done.  Can this also be added for people that have for instance just reserved slots?  If they are in the Default Group they of course don't have access to the !perks command.

**Comment by ColColonCleaner** [comment]
Why wouldn't they have access to it? All it would do is say that they don't have any perks. This command applies to any beneficial list, so it should already work for your case.

**Comment by ColColonCleaner** [comment]
@wdfstryfe Do you still have questions on this?
