### ISSUE TITLE
Feature Request: Forbid @join command on self or squad mates

### ISSUE THREAD

**Issue by Subman-CNP** [AdKats/AdKats#881]
I've found out that some players are using the @join command on self, just because they can't use anymore @killme due to timeout. In this situation players can just bypass this restriction, because you can use @join on self as many times as you want. The @join command should not work as well on any current squad member (at least it should not kill him).

**Comment by ColColonCleaner** [comment]
Sounds good, and not that difficult to implement with the current system.

**Comment by Subman-CNP** [comment]
Hello, I have sent you some money to get this enhancement a little bit quicker :)

**Comment by ColColonCleaner** [comment]
lol dammit. Alright i'll try fitting it in this week as well. Thanks.

**Comment by ColColonCleaner** [comment]
This should work in the latest test version now. Please let me know if it works to your liking. Cheers.
