### ISSUE TITLE
Add faction randomizer options to AdKats

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#887]
FPSG funded feature

**Comment by III-Pho3niX-III** [comment]
Faction Randomizer still give some warning messages when i setup the settings.
"[AdKats] ERROR-68193: [Unknown setting when updating faction randomizer restriction.]"

**Comment by ColColonCleaner** [comment]
That error should be fixed now.

**Comment by III-Pho3niX-III** [comment]
Thank ColColonCleaner!

**Comment by ColColonCleaner** [comment]
Add the following options:

AlwaysSwapUSvsRU
AlwaysSwapUSvsCN
AlwaysSwapRUvsCN

**Comment by ColColonCleaner** [comment]
@III-Pho3niX-III That feature should be added now.

**Comment by III-Pho3niX-III** [comment]
I dont see a message that the function AlwaysSwapUSvsCN is activated for the next round.
AlwaysSwapUSvsCN doesnt work, i have the same default server setting.

**Comment by ColColonCleaner** [comment]
What is your setting for "allow repeat team selection". That should be true.

**Comment by III-Pho3niX-III** [comment]
My settings:
Faction Randomizer: Enable = True
Faction Randomizer: Restriction = AlwaysSwapUSvsCN
Faction Randomizer: Allow Repeat Team Selections = True

Every end-of-round the Team Side must be switched to US-CN en-round CN-US. But it doesnt work right now.

**Comment by ColColonCleaner** [comment]
Still testing this.

**Comment by Phenom300** [comment]
Bringing up the dead here, this appears to create an issue with other parts of the plugin in that it detects the wrong faction which breaks things like team power, nuke function etc.

For example I had US and CN showing in procon yet in battelog it was RU and US and the tickets were reversed, once disabling the randomiser option things worked as expected upon the start of a new round.
