### ISSUE TITLE
DPS Automatic Ban [AN94-54-58-9] [perm][AutoAdmin] 

### ISSUE THREAD

**Issue by callekla** [AdKats/AdKats#890]
Hi guys, 

Sorry if this is the wrong forum but I can't really understand what is going on here?
From the looks of it I've been banned for using the AN94?

This a recorded session from the time I think I must have been banned?
About 1h in: https://youtu.be/OMknEYCLhxo

A second session running the AN94:
https://youtu.be/OMknEYCLhxo about 45min in.

As you can see I get some streaks but nothing special. Bug?

**Comment by callekla** [comment]
My nick in BF4 is TheJacka1
http://battlelog.battlefield.com/bf4/user/TheJacka1/

**Comment by ColColonCleaner** [comment]
Please reference #860 for this issue.
