### ISSUE TITLE
Allow the "assist"-command only after x Tickets/Time are gone

### ISSUE THREAD

**Issue by BP4U** [AdKats/AdKats#893]
Is there a possibility to allow the "assist"-command only after x Tickets/Time are gone?
Atm several guys "abuse" that function on locker by assisting at roundstart when they see which team captures "C" first.
In most cases that team wins in the end...

**Comment by CheckaWiemi** [comment]
We also have many problems on our Metro server with abusing assist commands. They're pushing the enemyteam into baserape and assist the weakteam and push them again in baserape, assist the weak team and so on.
So like BP4U said a tickets/time or maybe how often (e.g. a limitation of 2 times in a game) would be nice.
