### ISSUE TITLE
Add squad split whitelist to the top player monitor

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#894]
When the top player monitor is activated and multiple players with this whitelist are in the same squad, they will be kept together.

**Comment by ColColonCleaner** [comment]
Adding two tiers, one where each person whitelisted in the squad will be kept together, and a second tier where one person having it whitelists their whole squad

**Comment by Hodor228** [comment]
And please add the selection fields: 
*Keep same clan tag in one team: "true or false"
** Sort by power if more than <value> with the same clan tag: "value"

* Do not move players with the same clan tag in different teams
** Dispense evenly over the power in different teams if more than <value> people with the same clan tag

**Comment by ColColonCleaner** [comment]
The original goal of this was attempted, but I was not able to complete testing, and a lot more testing and reconfiguration needs to happen. Working with full squads between rounds is very cumbersome in battlefield.

**Comment by ColColonCleaner** [comment]
The top player monitor has been completely gutted and replaced with a new system since the previous one caused issues. There is an option to enable scrambling which does keep squads together.
