### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by EntraVenuS** [AdKats/AdKats#895]
would it be possible to have a !moveme limit added per month, This could be given to VIP but the limit would stop VIP abusing the moveme. 

No extra ingame commands needed only an adkat pm to player once all the !moveme allowance has been used.

Also could a menu be added to adkats to enable it (with a !moveme limit) for VIP Members  

Thanks In Advance

**Comment by Hodor228** [comment]
Per day would be better.
