### ISSUE TITLE
CMD to add or remove reputaion point.

### ISSUE THREAD

**Issue by windorose** [AdKats/AdKats#897]
Hi , if it s possible to add a commands to add or remove rep.

**Comment by windorose** [comment]
WARNING: Unable to find source weight for command 18|61 on test version 6.8.1.111

**Comment by ColColonCleaner** [comment]
Please send 5-10 bucks and I'll add these commands, otherwise this issue can be closed.

**Comment by windorose** [comment]
i made a don before (14-06-2016 transaction id : 9C801820V58963803).

**Comment by ColColonCleaner** [comment]
Think I completely missed this after transitioning it. Apologies. If you are still interested in this feature please let me know.
