### ISSUE TITLE
player join issue

### ISSUE THREAD

**Issue by deluxesss** [AdKats/AdKats#898]
Hi :),

a player told me about issues to join our server. If adcats is switched off he is able to join. The issue is on a 32-Slot bf3 G-Portal Server with the following error message: "Game disconnected: you were kicked by an admin. Stated reason your soldier name". There is not such an entry in my ban list.

Do you have any idea ?

Greetings Oliver

**Comment by ColColonCleaner** [comment]
Please link the player's battlelog profile here so i can examine the issue.

**Comment by deluxesss** [comment]
http://battlelog.battlefield.com/bf3/user/Sgt.Hulkstar/
thx in advance

**Comment by deluxesss** [comment]
today i saw this error in console, maybe it helps: 

[21:03:28 94] [AdKats] ERROR-6810: [Could not find Dr.Brausefrosch in player dictionary on spawn.]
[21:03:30 35] [AdKats] WARNING: Dr.Brausefrosch has an invalid player name, unable to process.

**Comment by ColColonCleaner** [comment]
This issue has been fixed as of now,
