### ISSUE TITLE
Values

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#899]
Some values are not totally clear
In adkats.cs some values like the lock player duration (2.5) or rules print delay (0.5) are specified with a . between the two values. But if I try to enter those values in the procon layer as example for the rule print delay 1.5 for rule print delay it says 'property value is not valid'. And if I try to enter a value with a coma like 1,5 it changes it to 15.

Can you check it out ?

Thanks

**Comment by ColColonCleaner** [comment]
Seems like a localization issue. Seen this before but not for a while.

**Comment by ChaT0n** [comment]
Another question, we are getting warning for high memory usage: [AdKats] WARNING: 307MB estimated memory used.

I know it reprents nothing compare to the memory we have on the machine, but I prefered to tell you.
And no the procon layers have not been reboot since last test version update

**Comment by ChaT0n** [comment]
So the value should be used with , or with .    ?

Thanks

**Comment by ChaT0n** [comment]
Think we found the origin of the problem. Will give u a feed back after testing it
