### ISSUE TITLE
Could not find persona ID for Srynx01

### ISSUE THREAD

**Issue by Dancger** [AdKats/AdKats#901]
Hello all

I'm asking for a friend who's administering some battlfield 4 servers.
We're getting flooded with the following message every two/three seconds:
![error5390_couldnotfindpersonaidfor](https://cloud.githubusercontent.com/assets/803922/15100703/8490c47c-157a-11e6-827d-8ad52dc29796.png)

Same problem as in #781 and #816 .
We  set the debug level on zero - no success.
**What can we do against these error messages?**

btw: we're using version 1.5.1.1 (177035).

**Comment by ColColonCleaner** [comment]
This should be completely fixed.
