### ISSUE TITLE
Request: Function for additional Chattrigger

### ISSUE THREAD

**Issue by mambochambo** [AdKats/AdKats#903]
Hello- is there a way- that the function of the Plugin Chattrigger- Autoresponder can be implemented in Adkats?
https://forum.myrcon.com/showthread.php?1165-Chat-Trigger-Auto-Responder-(v1-1-2014-03-15)

**Comment by ColColonCleaner** [comment]
This would need to be a paid feature for it to be done in any reasonable amount of time, things are too busy right now to cover every request people are asking for.

**Comment by JuniorZancan** [comment]
I am willing to help fund this request

**Comment by ColColonCleaner** [comment]
I can look over that plugin and see how it works.

What is wrong with that plugin that it can't be used as-is?

**Comment by JuniorZancan** [comment]
I don't know @mambochambo, but here every time I reboot the Procon Layer, the plugin reset all the fields. There's a way to prevent this, changing the startup mode of Procon, but it's a little hacky and can compromise another plugin.

(Sorry for my English)

**Comment by mambochambo** [comment]
connect with ftp to your proconlayer, go to your config folder, and then edit procon.cfg
in procon.private.options.UsePluginOldStyleLoad False set it to true. then the settings wont overwrite.

**Comment by ColColonCleaner** [comment]
Looks like their issue was solved by another plugin. Removing from the AdKats issue list.
