### ISSUE TITLE
FR: Delay before assist is allowed.

### ISSUE THREAD

**Issue by wdfstryfe** [AdKats/AdKats#904]
If there is a way currently, that would be awesome. But, I would like a way for at least the first 5 minutes to disallow the assist command because a lot of people are abusing the assist to stack teams.

**Comment by jaggedsoft** [comment]
I have the opposite problem, I would love a way to eliminate the 2 minute wait between !assists to the losing team

**Comment by ColColonCleaner** [comment]
Both of these requests have been fulfilled. A duration before assists are allowed has been added. And you can enable the team power monitor to turn the larger wait into a smaller wait.
