### ISSUE TITLE
New issue: Scrambing on round end

### ISSUE THREAD

**Issue by jaggedsoft** [AdKats/AdKats#905]
Hi guys, I absolutely love AdKats and I plan to donate as soon as I can afford it. Thank you for making such an awesome plugin! I hope you have plans to make it work for BF1 as well!

Out of the blue about 2 or 3 days ago, my server started killing people on round end, and booting them from the squad. I have no idea why. I have disabled all plugins but AdKats and this continues. I disable AdKats and it stops. Any ideas?

![sc17ayl](https://cloud.githubusercontent.com/assets/4283360/15495588/aea01318-2145-11e6-91e4-c8feca6f779d.png)

**Comment by ColColonCleaner** [comment]
Please update to the latest test version, this should be fixed. Cheers.

**Comment by jaggedsoft** [comment]
Thank you ColColonCleaner!

"I added code to the top player monitor for controlling squads. Didn't realize the code for controlling squads was active anyway even when the monitor was off. I'll fix that tonight.
For those with the squad issue at round end, please update to the latest version *.110, it should be fixed there."
