### ISSUE TITLE
dps ban message

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#906]
Had a weird ban message in the weapon name for an automatic dps ban : 
"Hacker/Checker DPS Automatic Ban [4-M416-98-141-36-143]"
The 4 before the M416 is it normal ?

Using the test version v 6.8.1.111

**Comment by ColColonCleaner** [comment]
It's the code for a DPS ban, i had that missed in the messages before. 4 is for DPS. 5 is for KPM, and 6 is for HSK. We use it for reading/parsing the ban codes.

**Comment by ChaT0n** [comment]
Thanks for clearing this up
