### ISSUE TITLE
Problem with Spectator Slots

### ISSUE THREAD

**Issue by JuniorZancan** [AdKats/AdKats#907]
I'm having a little problem in my Spectator Slots list. 

We have the Full Admins (including myself):
[http://s33.postimg.org/nlivsq5f3/admins.png](http://s33.postimg.org/nlivsq5f3/admins.png)

Some Supervisors:
[http://s33.postimg.org/4y21qpii7/supervisores.png](http://s33.postimg.org/4y21qpii7/supervisores.png)

And a few VIPs:
[http://s33.postimg.org/uqu3hpgq7/VIPs.png](http://s33.postimg.org/uqu3hpgq7/VIPs.png)

But for some strange reason, AdKats isn't syncing all the players in the Spectators Slots list as you can see:
[http://s33.postimg.org/iz759njzj/spectators.png](http://s33.postimg.org/iz759njzj/spectators.png)

There are missing all the Admins, all the Supervisors and, the weirdest part, some VIPs are in and others don't.

The Spectator List it was supposed to have almost the same quantity of players that the Reserved List:
[http://s33.postimg.org/l4pjryrjj/reserved.png](http://s33.postimg.org/l4pjryrjj/reserved.png) 

Look at the Verbose List:
[http://s33.postimg.org/7hojgv3sf/verbose.png](http://s33.postimg.org/7hojgv3sf/verbose.png)

The Orchestration config:
[http://s33.postimg.org/jux8tel0v/orchestration.png](http://s33.postimg.org/jux8tel0v/orchestration.png)

The VIP and Full Admin Role Settings:
[http://s33.postimg.org/433593xtb/role.png](http://s33.postimg.org/433593xtb/role.png)

There is something that I can do to check what's going on?

Thanks and sorry for my English.

**Comment by wizard45** [comment]
I could be wrong here, but isn't the maximum number of people you can have on your spectator list only 15 people?

**Comment by ColColonCleaner** [comment]
The server itself can only support 15 people in the spectator slot. I have no idea why. However, AdKats can support more. Turn off the setting on your server that only allows whitelisted spectators, the server setting, not AdKats setting. Then update to the latest test version with /pupdate. Your issue will go away then.

Thanks for being so detailed with your issue.

**Comment by ColColonCleaner** [comment]
Giving more info.

When AdKats sees there is anyone in the AdKats spectator slot list, it will not allow any other players to join as a spectator. It will kick them. If it sees the spectator slot list is empty, it will allow everyone to join spectator. You do not need any server settings enabled like only allowing whitelisted spectators for this to work, in fact, those settings should be disabled. Cheers.

**Comment by JuniorZancan** [comment]
@ColColonCleaner The more I see about AdKats, even the source code, the more I love it. You just considered everything.
I will make a donation ASAP.

Thank you very much.

**Comment by ColColonCleaner** [comment]
@JuniorZancan Thank you much!
