### ISSUE TITLE
REQUEST: Add option to disable AdKats instance checks in admin chat

### ISSUE THREAD

**Issue by danfango** [AdKats/AdKats#910]
Great plugin and its working great but its spamming my server. I saw a thread on the procon website that descibes the exact problem but it doesn't seem to have a fix for it. It's spamming the rconnet chat. Hope you can help : . I am running procon on a dedicated pc at home and not on a procon layer. (BF4) is the game we have a server for thanks.

 
Server to all
/AdKatsInstanceCheck VioNJikkBBwkB05OSw0MAlJBN1BaOzoTQTk2QgE7Llo= 1878
2 hours ago
Server to all
/AdKatsInstanceCheck VioNJikkBBwkB05OSw0MAlJBN1BaOzoTQTk2QgE7Llo= 1847
2 hours ago
Server to all
/AdKatsInstanceCheck VioNJikkBBwkB05OSw0MAlJBN1BaOzoTQTk2QgE7Llo= 1817
2 hours ago

**Comment by ColColonCleaner** [comment]
Their system displays hidden admin say messages as normal chat messages and logs them, which i explained to them they shouldn't be doing. It looks like they haven't done anything about it. Can't you just turn off logging of admin say messages? Why would you log spam?

AdKats instances watch chat for hidden instance check messages, and use that to make sure only one instance of AdKats is running on a server at any time. Had a lot of issues with this in the past with people booting up instances on the same server.

If you want a feature to disable that then you can request it, but I am already behind with the list of things being done for free.

**Comment by danfango** [comment]
Many thanks for your quick reply. Yes I had an idea it was rconnet logging and showing the messages. I'll have a look at turning off the logs in rconnet. Many thanks again for an excellent plugin and all your hard work in the past. Maybe a feature would be to include a switch to turn /AdKatsInstanceCheck (on or off). Cheers for now !.

**Comment by ColColonCleaner** [comment]
Logging normal player chat is great, but why you would be logging admin says, especially hidden admin says, is beyond me.

**Comment by danfango** [comment]
Yes and I just had a look at rconnet doesn't seem to be a way to turn it off. A lot of our plugins are rconnet based and a few are procon based looks like I'll won't be able to use Adkats for now until rconnet guys come up with a fix or I move entirely to procon

**Comment by ColColonCleaner** [comment]
Make this a funded request and i'll make sure the feature is added within the week.

**Comment by danfango** [comment]
How much of a donation ?

**Comment by ColColonCleaner** [comment]
5-10 would be enough. cheers.

**Comment by danfango** [comment]
10$ sent via my paypal account mystique_entertainments@hotmail.co.uk

Cheers SteveJ.

**Comment by ColColonCleaner** [comment]
Funded for completion within the week.

I edited your comment to remove the email. It's not a good idea to post emails publicly on the web, spiders everywhere.

**Comment by danfango** [comment]
Yes I did wonder thanks

**Comment by ColColonCleaner** [comment]
I've added the setting. It's in the D99 debug section. Turn off "Enforce Single Instance" and you should be fine.

Please comment back saying it's fixed or not. Cheers.

**Comment by danfango** [comment]
Do you have a link to the new version thanks

**Comment by ColColonCleaner** [comment]
https://raw.githubusercontent.com/AdKats/AdKats/test/AdKats.cs

**Comment by danfango** [comment]
Thanks got it and it seems to have stopped the spam on the rconnet chat. However the crashing of procon is back. I'm not sure what plugin is causing it and it seems to crash at a much later stage than before. I have had to disable both plugins is there a way within procon to determine what's causing the crash ?

**Comment by ColColonCleaner** [comment]
How long is your layer normally running before the crash?

**Comment by danfango** [comment]
Hi I think I may have fixed it. In an effort to solve some statslogger plugin errors I gave both plugins temp root access - this seems to have cause the crashing because I reverted back to user access level on the sql database and now zero crashes it seems !. Will continue to montior the situation and reply back

**Comment by danfango** [comment]
Bizarrly it seemed stable all afternoon yesterday (server empty) but as soon as players started to join in the evening it was constantly crashing again

**Comment by danfango** [comment]
Gonna leave these plugins for now can't get them stable no matter what I try thanks anyway
