### ISSUE TITLE
Assign automatically to specific group 

### ISSUE THREAD

**Issue by windorose** [AdKats/AdKats#911]
Hi CCC

It's possible to assign automatically a player on a specific group  when he reach XX Hrs play on server?

Donation Made (for the considerable effort you make for the community and for helps you have brought me)

**Comment by windorose** [comment]
???

**Comment by ColColonCleaner** [comment]
Wait what? You already paid for this? We never discussed anything with it, or how it would be done, or anything.

I don't know what settings are wanted, or how big the effort is going to be to implement it.

**Comment by windorose** [comment]
No no no,  i made a donation i didn't paid for any service .
you brought me a help you and Prophet731 and i really appreciate.

**Comment by windorose** [comment]
Just i want know if i can set Adkats assign automatically any player has played 100 hrs or more on a specific group (to give them some perks).

**Comment by Hodor228** [comment]
Sounds really great, should be encouraged devotees server players

**Comment by ColColonCleaner** [comment]
This would need to assign special player groups to players over a certain hour count. This would probably be in section B27. Please send 10-15 bucks and I'll implement it in the system for reserved slots, autobalance whitelist, ping whitelist, and tk tracker whitelist. Option available to adjust at what hour count they get this perk set.

Actually better yet, just an hour count for each perk, so you can stagger your perks based on hours played.
