### ISSUE TITLE
REQUEST: Self-kill message

### ISSUE THREAD

**Issue by JuniorZancan** [AdKats/AdKats#913]
It's possible to add a message when a player kills himself with a weapon? 

I'm not talking about suicide, but about killing himself with damage from a weapon, like firing a RPG in a very close wall. When it was supposed do show "Player [RPG] Player".

How much this will cost?

Thank you.

**Comment by ColColonCleaner** [comment]
This would probably be more reasonable to do with insane limits. I mean, it can be done here, but then it can't be customized easily. I would suggest asking in the insane limits requests thread.

**Comment by JuniorZancan** [comment]
Ok, thanks.
