### ISSUE TITLE
Documentation on Pre-Recording

### ISSUE THREAD

**Issue by jaggedsoft** [AdKats/AdKats#915]
> Yell/Say Pre-Recording. Use numbers to reference predefined messages. Avoid typing long reasons or messages. e.g. /kill player 3 

Hi, I would like to start using this feature but can't find any documentation or if it's an ingame command. I would like to set up a few different predefined ban messages. Is this possible?
!ban player 3

**Comment by ColColonCleaner** [comment]
https://github.com/AdKats/AdKats#pre-messaging

I believe it's setting section A12 these can be added in.

**Comment by ColColonCleaner** [comment]
And yes you will then be able to use the ban command like you want to.

**Comment by jaggedsoft** [comment]
Thank you!!
