### ISSUE TITLE
Question: Translation

### ISSUE THREAD

**Issue by JuniorZancan** [AdKats/AdKats#916]
I'm trying to translate AdKats to Portuguese (Brazil), I already had success translating the warning and info texts inside AdKats.cs

But now I wonder if I change the "command_name" column in the database (image attached) would cause any problems.

Thank you.

![commands](https://cloud.githubusercontent.com/assets/8093540/16187041/69b4b7bc-36a4-11e6-9606-3361e4d8a1ef.PNG)

**Comment by Prophet731** [comment]
It shouldn't cause problems, however, with changing the source code in AdKats you would have to translate it every time an update is released.

**Comment by JuniorZancan** [comment]
@Prophet731 yeah, unfortunately I realized that after I did an update last week :-(

Maybe in the future somebody put this as a request. A file where AdKats can consult a sentence and then members of the community could send those translation files. 

But this would require several changes to the plugin and a lot work

**Comment by Prophet731** [comment]
There were plans on adding in a translation table for AdKats but we've both been very busy for these last few months.

**Comment by JuniorZancan** [comment]
@Prophet731 When possible, I offer myself to help for Portuguese (Brazil).

Thanks again.
