### ISSUE TITLE
Unable to find source weight for command

### ISSUE THREAD

**Issue by III-Pho3niX-III** [AdKats/AdKats#917]
Hi Colon,

After many messages and reports what i send with no repsonse i want to ask you, please fix this reputation setting value error message. [AdKats] WARNING: Unable to find source weight for command 123|123
![ss 2016-06-23 at 10 20 08](https://cloud.githubusercontent.com/assets/14888758/16296417/73b0f70a-392c-11e6-87b4-d701e41d1ee4.png)

Thanks in advance!

**Comment by Prophet731** [comment]
@ColColonCleaner 

Merge this pull request.

https://github.com/AdKats/AdKats/pull/918

**Comment by ColColonCleaner** [comment]
I have not looked at my messages for quite some time, sorry man. Thanks for taking care of this prophet.

**Comment by III-Pho3niX-III** [comment]
No problem Colon! We have also a private life then only coding the hole day. 
Prophet is doing good job :+1: 

I close this topic.
