### ISSUE TITLE
Auto-Nuke/Auto-Surrender based on server tickets

### ISSUE THREAD

**Issue by taman1990** [AdKats/AdKats#922]
Hello!
So i would like to suggest this idea for auto-nuke/auto-surrender based on server tickets 

For example...
lets say i have a server with 2000 tickets 

and I would like to set up an auto-nuke based on  settings like 

**_Minimum players: 32
definition of early phase as tickets from start: 200
definition of late phase as tickets from end: 400
If all the flags has been taken, And if Max tickets difference Is: 200_**
Optional setting to enable or disable _**Losing team flags: 2**_ 

_**Result: Nuke Winning team**_ 

So right now based on the settings above the auto-nuke works only if the Minimum number of players is 32 
and function after 200 tickets from beginning of round and not less that 400 tickets from end 
and only if enemy has all the flags and the ticket difference is +200
Then auto-nuke the winning team. 

About this "Losing team flags: 2" Im not sure if its possible but would be great to keep nuking the winning team until losing team captures 2 flags
if that is not possible then a setting to keep nuking for 2 minutes maybe xD 

Of course adjusting the tickets you can make it work great for any server tickets, plus for auto-surrender for example if the ticket difference is +800 

I believe this will make a perfect balance of tickets :)

**Comment by ColColonCleaner** [comment]
Please send 10 bucks and i'll implement this into the plugin for everyone.

**Comment by taman1990** [comment]
How do i send money? what email?
sorry mate, a total newbie here

**Comment by ColColonCleaner** [comment]
Please use the donation link in the main AdKats thread. Thank you.

**Comment by Breakmaster90** [comment]
Hey, i donate 15 Dollar. Go go , Power Rangers! xD

**Comment by ColColonCleaner** [comment]
Several of the setting he is asking for are already in the plugin, such as "tickets from start" and "tickets from end". There is no way to get the actual flag count a team has, it's all calculated, so this needs to be tackled slightly differently.

The normal auto-nuke will still fire when all flags are captured based on your ticket loss settings, this will be an additional trigger if a team is winning by too much (but still not taking all flags) and they need to be toned down a bit to keep the matches interesting.

Basically the way this will function is an additional way for triggers to fire beyond ticket loss rates. If a team that has more flags (we don't know how many, but we know they have more), and that team is also winning, and they are winning by more than the ticket count we configure, fire a nuke trigger.

The only issue I see with this is a winning team will basically keep getting nuked until they have less flags than the other team, which could be a bad thing. However, you will be able to use the 'minimum seconds between nukes' setting to make sure that winning team isn't nuked too often.

**Comment by ColColonCleaner** [comment]
This is added, with the setting:

Fire Nuke Triggers if Winning Team up by X Tickets

It's in the nuke section, and defaults to 9999 tickets, so it should never activate unless you lower that number. Please let me know if it's working as you expect.

**Comment by Breakmaster90** [comment]
Hmm this Option worked not great.
It nukes in bad timing.
Also if the Winner Team have already only 1 Flag.

**Comment by ColColonCleaner** [comment]
@Breakmaster90 Please explain what you mean by not great. The timing of the nuke happens when the ticket gap between teams goes above the threshold you set. It should however only be nuking the winning team if they have more flags than the losing team. What is not working?

**Comment by taman1990** [comment]
Hello! Sorry couldn't donate yet, i will ofc do whenever i can :) 
but good to see someone else also funded 

I will test and report but looking at setting is just a headache for me i do not understand how to set it correctly 

for example what setting is to set the ticket from start and ticket from end exactlly?  

and this losing and winning team rate window....., are they dependable too? i still do not know how to set it correctly, looking at my procon chat i see messages like 
US Rate: -43,97 t/m | CN Rate: -2,79 t/m | CN up 3 flags, US gaining ground.
US Rate: -35,35 t/m | CN Rate: 0 t/m | CN up 1-3 flags, CN gaining ground.
US Rate: -18,84 t/m | CN Rate: 0 t/m | Flags equal, not changing.
...
no idea what to make out of this man, no clue what number to give to losing or winning team window

**Comment by taman1990** [comment]
There should be a donation by name dan.shafir now
sorry can not donate on my own paypal doesn't support the stupid country i live

**Comment by ColColonCleaner** [comment]
@taman1990 I'll explain this tonight if I get a chance. There is also a section about this in the AdKats documentation. All the settings (most anyway) are explained there.

**Comment by taman1990** [comment]
Hi!
its all good
just tell me if i do it right in this settings bellow 

server ticket is 2000
i've set it like this 

Auto-Surrender Minimum Ticket Count 300
Auto-Surrender Maximum Ticket Count 1900
Auto-Surrender Minimum Ticket Gap 260

Auto-Surrender Losing Team Rate Window Max 1900
Auto-Surrender Losing Team Rate Window Min 350
Auto-Surrender Winning Team Rate Window Max 1900
Auto-Surrender Winning Team Rate Window Min 350

now what i understand from this 
it should only work if the ticket gap is 260 
and it should only happen if losing and winning tickets rates are between 1900 and 350 tickets
correct?

**Comment by taman1990** [comment]
ah wait, winning and losing ticket rates are NOT ticket rates its the number we see in procon chat haha  

anyways i set it up 
it works fine but needs alot of game play till i figure out what numbers are accurate 
for a couple rounds worked good i still have to adjust the numbers i see in procon chat tho


But the messages are annoying, spams the chat the entire round, hundreds of nuking messages in one round, every 10 seconds i see messages like 
AdKats > Say > Auto-nuke 1 17% ready. ~50s till it can fire.

right now i had to disable this setting because these messages are confusing everyone, spams the chat every time 

there should be a setting to customize the messages or disable it completely 
for example...
I dont think its necessary to say
"Auto-nuke 1 17% ready. ~50s till it can fire.   ....Auto-nuke 1 50% ready. ~50s till it can fire. ...... Auto nuke cancelled.. "
this spams the chat ALOT or at least a setting to show this messages to admins only 
would be good if it simply shows the count down message before nuking and nothing else
