### ISSUE TITLE
AdKats.cs file 0 bytes?

### ISSUE THREAD

**Issue by sitekeeper** [AdKats/AdKats#925]
Been use AdKats for 2 years now on 4 servers, had something strange happen. 
Our NFO server DDOS and for a short time (3-5 mins) Procon could not connect to it. After checking DB and starting the 4 layers again, one was missing the AdKats plugin in procon so I looked in ftp and AdKats.cs was at 0 bytes. I uploaded only that file and everything was fine. 

Any ideas on why that happened. 
Game servers and DB @ NFO and Procon @ Brandzone AdKats  6.8.1.117
Is  version 6.8.1.117 ok? My procon layers seem to update it to test version no mater what I do.

Thanks
Bob

**Comment by ColColonCleaner** [comment]
This is a very rare but known issue with the automatic updater during stressful times, it can fail to properly write to the plugin file with updates, leaving it empty. It's one of the things on my plate to look at.

**Comment by sitekeeper** [comment]
Ok thanks for the info...

Thank You 
Bob

**Comment by ColColonCleaner** [comment]
I have not seen this happen in many months and nobody has reported it further. I'm deeming this too low of a priority to research since a lot of exception handling already exists around the update system.
