### ISSUE TITLE
EXCEPTION-681117-D-FetchIPLocation-IPAPIComm40

### ISSUE THREAD

**Issue by lonelymoonlight** [AdKats/AdKats#926]
[AdKats] EXCEPTION-681117-D-FetchIPLocation-IPAPIComm40: [Error while parsing IP response information.][System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.FetchIPLocation(AdKatsPlayer aPlayer)]

local mysql and Other host mysql Will be displayed
version 6.8.1.117 and 6.8.1.0 Will be displayed

**Comment by ColColonCleaner** [comment]
Please enable plugin debugging on your layer.

In the procon.cfg file

procon.private.options.enablePluginDebugging True
