### ISSUE TITLE
ERROR-6810 Failed to fetch weapon stat definitions. AdKats cannot be started.

### ISSUE THREAD

**Issue by Aismel** [AdKats/AdKats#927]
I use Proscon v1.5

When i fill the parameters in plugin tab is frozen every time i change line
Host:
User:
Pass:

It's normal ¿?

Then i try to enable the plugin obtain this error and frozen the proscon complete again !!

ERROR-6810 Failed to fetch weapon stat definitions. AdKats cannot be started.

And i try to close the proscon again frozen ¿?

Thx any help

**Comment by ColColonCleaner** [comment]
What operating system is your layer running on? Is it linux?

**Comment by Aismel** [comment]
I use Windows 8.1 and everything work ok only happend with this plugin. Any idea ??

Thx any answer.
