### ISSUE TITLE
Feature Request: Battlecry

### ISSUE THREAD

**Issue by JuniorZancan** [AdKats/AdKats#928]
I want to suggest a new feature for the Battlecry function. To show the player name + the Battlecry message.

Just like this: http://pastebin.com/Qxvj9ZFt

But due to character limitation of the "Yell" (and consequently the "Tell"), perhaps something like this: http://pastebin.com/4uTjC1mc

Thank  you.

**Comment by ColColonCleaner** [comment]
This would need to be enabled optionally, not everyone would want it with a player's name. So settings/options will need to be created for it. Please either create a pull request for this, or send 5-10 bucks for me to take time and add it to the plugin.
