### ISSUE TITLE
[AdKats] WARNING: 279MB estimated memory used.

### ISSUE THREAD

**Issue by mambochambo** [AdKats/AdKats#929]
Hello can you help me out- i get this warning in Adkats.
Best Regards

**Comment by Breakmaster90** [comment]
We get also this Warning. For us sometimes more than 500MB per Layer!
Also CPU goes high.
The Procon Layers going laggy. Needs everday restart.

**Comment by ColColonCleaner** [comment]
Please perform daily restarts when your server is empty until we locate this issue. It is known, but we are not currently sure what is causing it. We are working on it.

**Comment by ColColonCleaner** [comment]
Please update to the latest version and let me know if the memory issues stay the same or if they slow down on the increase.

**Comment by mambochambo** [comment]
stable version or test build?
Thank you
Best Regards

**Comment by ColColonCleaner** [comment]
Test build, the 6.8.1.128 build i believe is the latest.

**Comment by Breakmaster90** [comment]
Still the same :/

**Comment by Breakmaster90** [comment]
It appears after 12 Hours.

You mean this?
[AdKats] SUCCESS: User fetch complete [20 users, 41 Special Players, 72 Fetched Players]

**Comment by ColColonCleaner** [comment]
Wow, that's way too fast. Normally for us it would appear after like, a week of constant running, so we assumed it wasn't a large issue since people normally rebooted their layers regularly.

Are you running multiple layers on the same instance of procon? Or do you have separate procon instances for each server?

**Comment by Breakmaster90** [comment]
separate procon instances.
Started as Service on Windows Server 2012 R2 64 Bit Standard Machine.
We have 8 separate procon instances.
Our MhSV Server most of the time full.

**Comment by ColColonCleaner** [comment]
Very strange. I'll do more looking into it.

I'm probably going to add an output of numbers onto the memory warning, to show the size of some of the arrays/dictionaries in the plugin. This should help find the issue quicker. Once the update drops and you see some of these warning messages with extra numbers on them please post those messages here (one for each layer please).

**Comment by ColColonCleaner** [comment]
Ok with the latest test version you will see that memory warning with a bunch of numbers after it. For each of your servers please send me those log messages when they show up.

**Comment by ColColonCleaner** [comment]
@Breakmaster90 Please confirm you saw this message so we can move forward with this quickly. Thanks!

**Comment by Breakmaster90** [comment]
Yes i saw this message. I wait for the log messages. ^^

**Comment by mambochambo** [comment]
Hello Guys- i installed the Version on all our Servers- since then everything is fine! Thx for your work
Best Regards

**Comment by Breakmaster90** [comment]
The First one:

[19:04:46 55] [AdKats] WARNING: 256MB estimated memory used. MAP: 1:13, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:20, 9:18, 10:18, 11:41, 12:52, 13:0, 14:64, 15:19, 16:218, 17:317, 18:0, 19:0, 20:0, 21:0, 22:0, 23:22, 24:0, 25:0, 26:0, 27:37, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0, 34:0, 35:0, 36:18744, 
[19:04:49 56] [AdKats] SQL updates fetched.
[19:06:04 83] [AdKats] User List Fetched from Database. [20 users, 41 Special Players, 317 Fetched Players]

After 14 Hours.

**Comment by Breakmaster90** [comment]
Next One:

[21:02:00 76] [AdKats] User List Fetched from Database. [20 users, 42 Special Players, 255 Fetched Players]
[21:02:01 66] [AdKats] WARNING: 269MB estimated memory used. MAP: 1:13, 2:0, 3:0, 4:0, 5:0, 6:1, 7:2, 8:20, 9:18, 10:18, 11:42, 12:53, 13:0, 14:62, 15:16, 16:157, 17:255, 18:0, 19:0, 20:0, 21:0, 22:0, 23:0, 24:1, 25:0, 26:0, 27:0, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0, 34:0, 35:0, 36:33470,

**Comment by ColColonCleaner** [comment]
Found it, it's the queue for fetching player's IP addresses. For some reason on your layers it's unable to fetch those so instead of removing the player it always requeues them, and now you have 33,470 player objects waiting to have their IP info fetched. I'll add a patch for this to make sure those get purged and your memory problem should go away. Cheers.

**Comment by ColColonCleaner** [comment]
To clarify, it's the queue for fetching location info based on their IP addresses, like state/city/etc.

**Comment by ColColonCleaner** [comment]
@Breakmaster90 Please go to this page, and let me know if the IP of your layers was banned due to oversaturation, >150 requests per minute.

http://ip-api.com/docs/unban

**Comment by ColColonCleaner** [comment]
@Breakmaster90 Please install version 6.8.1.132 and send me the memory messages if they show up. Thank you.

**Comment by Breakmaster90** [comment]
After 4 Days with your new Version:

[13:45:30] [AdKats] User List Fetched from Database. [21 users, 41 Special Players, 354 Fetched Players]
[13:45:32] [AdKats] WARNING: 272MB estimated memory used. MAP: 1:13, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:21, 9:18, 10:18, 11:41, 12:53, 13:0, 14:62, 15:16, 16:257, 17:354, 18:0, 19:0, 20:0, 21:0, 22:0, 23:43, 24:0, 25:0, 26:0, 27:0, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0, 34:0, 35:0, 36:69,

**Comment by Breakmaster90** [comment]
Ok my Mistake. After 3 Days.

**Comment by ColColonCleaner** [comment]
If this is still an issue, please reopen this ticket.

**Comment by XDNDX** [comment]
I'm getting the same warning tonight,
[20:06:38 20] [AdKats] WARNING: 316MB estimated memory used. MAP: 1:13, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:40, 9:22, 10:22, 11:0, 12:200, 13:0, 14:40, 15:0, 16:124, 17:175, 19:0, 20:0, 21:0, 22:0, 23:0, 24:0, 25:0, 26:0, 27:0, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0, 34:0, 35:0, 36:0,

**Comment by Graymanflo** [comment]
@ColColonCleaner, same issue here, usually after 18h of uptime I get this warning:

> 254MB estimated memory used. MAP: 1:13, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:74, 9:21, 10:21, 11:10, 12:110, 13:0, 14:61, 15:16, 16:215, 17:311, 19:0, 20:0, 21:0, 22:0, 23:37, 24:0, 25:0, 26:0, 27:0, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0, 34:0, 35:1, 36:0, 

The Adkats commands slows down at that point and I have to reboot the layer.

**Comment by XDNDX** [comment]
@ColColonCleaner 

It has not done it again since.. must of just bugged out,
