### ISSUE TITLE
Balancing with Adkats Playerstats

### ISSUE THREAD

**Issue by Breakmaster90** [AdKats/AdKats#930]
Hey,
is it possible to integrate in Adkats a Balancer that works only with Playerstats from the Database and not from Battlelog?  (with a little Donate ^^ )
The Problem is that the guys plays sometimes little bit different like other Servers.
And the Actual Roundscore is for Scrambling sometimes also not perfect, because some guys leaving it.

So Balancing with Playerstats from Database would be great.
Balancing + Scrambling after the Roundend.

Also maybe with the Idea with the Auto Nuke from the other Issue.

We have a Operation Metro in BF4 with 64 Slots, 2000 Tickets, No Explo and No Shotgun.
The Balance and the Auto Nuke is at the moment not very good sometimes. The Balancer and Unstacker from Multibalancer is little bit buggy or work bad, because many different Players joining.

**Comment by ColColonCleaner** [comment]
This is something I am working on with the top player monitor, it uses stats in your database for balance. I would not suggest using the testing version of this right now though, some more work still needs to be done and you will see undesired behavior. I'll let you know when i'm done
