### ISSUE TITLE
Request to add a new function: At the end of the round. XX seconds into the next round

### ISSUE THREAD

**Issue by Super-Wong** [AdKats/AdKats#936]
Request to add a new function: At the end of the round. XX seconds into the next round

**Comment by ColColonCleaner** [comment]
Please explain this further and i'll re-open the ticket.

**Comment by Super-Wong** [comment]
When the round end .. There will be 50 seconds to display your score statistics
I hope to have a function.. Mandatory in 10 seconds or directly into the next round after 20 seconds
