### ISSUE TITLE
can't delete members of the 3-3 section

### ISSUE THREAD

**Issue by mikedevita** [AdKats/AdKats#939]
everytime i try to delete the 37 people in the list they just come back in the list automatically..

is there a way to remove them or is this a bug?

![image](https://cloud.githubusercontent.com/assets/2991640/19421992/ffa79210-93c1-11e6-8268-cd3fb27e5e62.png)

**Comment by ColColonCleaner** [comment]
That is a verbose display, you can't edit it there. You need to find out what is adding those people to the list and turn the setting off.

Several things can do this. The top player monitor, a setting in the admin section that adds automatic balance whitelist to people, among others. Look around to see.

**Comment by mikedevita** [comment]
ok thanks..

**Comment by ColColonCleaner** [comment]
The top player monitor adds players to that list because it takes control of them away from other autobalancer plugins. They are whitelisted from actions by other balancers in that case, but not AdKats internally.

**Comment by mikedevita** [comment]
cool i think we found it in **B27**.. Monitor/Disperse top players was true.
