### ISSUE TITLE
DPS Automatic Ban [LIVE][4-M19 [perm][AutoAdmin]

### ISSUE THREAD

**Issue by TheKillingDen** [AdKats/AdKats#940]
Hello everybody, 
searching for "DPS automatic Ban" on Google I found this page, so I don't know if this is the right place to ask or even if this page is related to DPS (can't understand what it is). The fact is that I got banned on the Battlefield 4 server where I am admin (just in game admin, I don't have ProCon access) without any reason. I was sitting in front of elevator shooting at mines to kill several players with pistol, all fine, but when the next round started I got banned without reason.. So, how can I appeal this ban? I have to ask to my head admin or to you?

Hope you can find time to reply, have a nice day and a nice weekend!

**Comment by TheKillingDen** [comment]
Also, this is the battlereport related to the round I am talking about: 

http://battlelog.battlefield.com/bf4/battlereport/show/1/792352058369045696/1576794981/

Maybe you can understand something more from this, thanks in advance.

**Comment by ColColonCleaner** [comment]
You will need to be whitelisted by your admin for the time being. The command is below:

/hcwhitelist perm TheKillingDen

It appears slams can now be detonated with smaller sidearms, while mines still cannot.

You got 37 kills with 60 hits with the m1911, which to the stat detector means you were dealing 62 damage per shot with your pistol on average, so it banned you for having a damage modifier.

It was assumed during development a year ago that slams would also only be detonatable with larger sidearms and sniper rifles, such as the rex, magnum, bolt actions, and DMRs, those of which this case is known for.

As for your actions other than getting whitelisted by your admin, you should get more normal kills with your m1911 so other servers running cheat detection do not pick up these stats without knowing the context (being able to detonate slams with a small sidearm).

**Comment by TheKillingDen** [comment]
Thanks for your reply, I am linking this post to the server owner. Just to say, I like your work and I like to see that guys like you are working hard to prevent cheaters from ruining our games, anyway I think what happened means that your plugin is not working as expected and it's interfering with the normal game. I see many players detonating c4 and slams with sidearms or sniper rifles, and if every player doing this get banned this may be a problem. Could you fix this? Also I would mark this as bug, considering that this behave is not expected. 

Thanks for your fast reply, have a nice day!

**Comment by ColColonCleaner** [comment]
Like i said, normal weapons that detonate mines and such (revolvers, snipers, dmrs, etc) are accounted for in the code. The m1911 being a low damage sidearm that shouldn't detonate them is not. You are a special case here.

**Comment by TheKillingDen** [comment]
Ohh that's ok then! But from what I know (I may be wrong) every weapon, also a handflare, can blow up a slam with two or more shots. With m1911 for example it took them two shots to detonate, with other low-damage firearms it's the same, so you may want to fix it (I don't pretend you to do that, you've already done much for us all).

Again thanks, have a nice weekend.
