### ISSUE TITLE
Feature Request: Show server status in teamspeak

### ISSUE THREAD

**Issue by Hedius** [AdKats/AdKats#941]
I want to suggest a new feature for the teamspeak monitor.
I would really like smth that posts some server info within the teamspeak(e.g.: Server name: online_players/offline_players) by updating the name of a given channel/placeholder with a certain channel-id

Would it be possible to include this feature?

**Comment by ColColonCleaner** [comment]
This would be a paid feature request, you can comment back if this is still something you're interested in.
