### ISSUE TITLE
Ping Enforcer not working

### ISSUE THREAD

**Issue by RollinCoal** [AdKats/AdKats#942]
I noticed a while back that the ping enforcer was not working.  I didn't see it as a problem at the time because we were thinking of shutting down the server.  Traffic is picking up again and I would like to get it going again if possible.  

It may be a coincidence, but the Latency Manager plugin will not work as well.  I was able to use an Insane Limits code, but it is nowhere near as functional.  I have seen at least one other person with this issue on the MyRcon Forum https://forum.myrcon.com/showthread.php?15988-No-more-plugins-for-latency-ping-work!

I haven't messed with any settings in a very long time, and the Latency Manager Plugin was working but hasn't been used since the ping enforcer was added to Adkats.  

I don't know if this is an issue with Adkats, my layer, or server...but thanks for your time.

**Comment by RollinCoal** [comment]
I looked back through my logs and the last date that the Ping Enforcer was working was 10/30/16.

**Comment by ColColonCleaner** [comment]
Is this still an issue? Please comment back if so.
