### ISSUE TITLE
How to set wait time after the Round is over?

### ISSUE THREAD

**Issue by mpoonuru** [AdKats/AdKats#944]
@ColColonCleaner 
Hey Bro,
I just tried to write a plugin called RunNextLevel.cs. Where I am capturing the wait time after the round over and before go to next round. I used Thread.Sleep(CaptureTimeinSeconds). This is not the right way.

How to write the code for the thread to wait without using the Thread.sleep. My CS file is attached. Please do let me know bro. 
[RunNextLevel.zip](https://github.com/AdKats/AdKats/files/864237/RunNextLevel.zip)

**Comment by ColColonCleaner** [comment]
Thread.Sleep(TimeSpan.FromSeconds(CaptureTimeInSeconds))

Is what you need. Don't remember the capitalization but those are the functions.

**Comment by ColColonCleaner** [comment]
Also, if you thread.sleep in a procon thread it halts the entire UI, i would suggest spinning off another thread for doing what you want.

**Comment by mpoonuru** [comment]
Thanks a lot dude!

**Comment by ColColonCleaner** [comment]
@mpoonuru This is what you need:

Thread aThread = new Thread(new ThreadStart(delegate {
    Thread.CurrentThread.Name = "NextRoundTrigger";
    Thread.Sleep(TimeSpan.FromSeconds(SomeDurationInSeconds));
    ExecuteCommand("procon.protected.send", "mapList.runNextRound");
}));
aThread.Start();

**Comment by mpoonuru** [comment]
@ColColonCleaner 
Hi Friend,
Thanks a lot for the quick turnaround.
When we use this mapList.runNextRound, it goes to black screen and loops never comes back. I tried your nextlevel plugin :) as it was very old.
