### ISSUE TITLE
Metabans User name and API code not being saved.

### ISSUE THREAD

**Issue by wizard45** [AdKats/AdKats#946]
Adkats is no longer keeping my Metabans User name and API code after I reboot my layer server. Every time I reboot the server, I have to re-enter my Metabans User name and API code in section A13-2. It does however remember my Metabans filter strings list.

Thank you for your help.

**Comment by ColColonCleaner** [comment]
Please try the latest test version, i added the update.

**Comment by wizard45** [comment]
Hello,

Your fix seems to be working!  Thank you for taking the time to do this fix.  I cant tell you how much your work has made my job so much easier.  Adkats is the best!
