### ISSUE TITLE
Found a hacker, Glitcher without EAGUID or PBGUID--- Unable to kick or Kill him

### ISSUE THREAD

**Issue by mpoonuru** [AdKats/AdKats#947]
Hi @ColColonCleaner @Prophet731 ,

I found the guy who is DOsing our servers, Adkats found him. 
[13:42:44] AdKats > CouragePAL4 is glitched in the server, their player has no GUID.
I am unable to kick or kill him, Banned him with Name, still he is in my server. Will you guys be able to help me on how to deal this?

Scary: https://cdn.discordapp.com/attachments/267953604835540993/311042132578140160/unknown.png

**Comment by Prophet731** [comment]
That's actually a glitch that happens. The only solution I know is to restart the game server.

**Comment by mpoonuru** [comment]
I tried bro, Still he is glitching and joining. He is warning us that he would be kicking everyone out of the server and he is doing it. LOL. I don't know what to do.

**Comment by Chilace** [comment]
@mpoonuru Earlier there was a plugin for such a case: https://forum.myrcon.com/showthread.php?6291
But unfortunately it disappeared.
You can try this code for Insane Limits: https://forum.myrcon.com/showthread.php?6248
Or ask for help in this thread: https://forum.myrcon.com/showthread.php?4489

**Comment by mpoonuru** [comment]
Do you have the code? Could you please share? That guy is joining with different names and crashing my server, Adkats able to find him but I don't know how to stop him. 

If you have to code, could you please share?

**Comment by ColColonCleaner** [comment]
PBHackDetect was removed (if I remember correctly) because DICE patched the issue and it was no longer needed. I do not believe there is a way to remove the player from your server at this time, with or without that plugin.
