### ISSUE TITLE
Player listing spam causing layer stability issues

### ISSUE THREAD

**Issue by ab9876** [AdKats/AdKats#948]
I was running 6.9.0.153 and it was absolutely destroying my layers by spamming serverInfo and "admin.listPlayers all," once per second each. This was causing timeouts with the layer machine itself and extremely delayed commands. I rolled back from the experimental version (which it seemed to autoupdate from 6.9.0.0 in the first place) and it seemed to have stopped, but it does destroy any layer on the experimental version, at least on my windows box and my ubuntu box.

**Comment by ColColonCleaner** [comment]
I need more information. What is the full error including all of the text after it?

Please use /pupdate to grab the latest version of the plugin and let me know if all is well.

**Comment by ColColonCleaner** [comment]
Please re-open after you have updated to the latest version.

**Comment by ab9876** [comment]
I have updated, that issue seems to be gone now, but I was running 6.9.0.153 and it was absolutely destroying my layers by spamming serverInfo and "admin.listPlayers all," once per second each. This was causing timeouts with the layer machine itself and extremely delayed commands. I rolled back from the experimental version (which it seemed to autoupdate from 6.9.0.0 in the first place) and it seemed to have stopped, but it does destroy any layer on the experimental version, at least on my windows box and my ubuntu box.

**Comment by ColColonCleaner** [comment]
What do you mean once per second EACH? Are you servicing multiple BF servers from the same layer? That's not recommended with AdKats.

The player listing from AdKats is executed once every 5 seconds. However, i could add a setting for this so people can modify how quickly they want their player list updated, allowing the setting to be set between 5-15 seconds.

**Comment by ab9876** [comment]
Each of the servers has their own instance of procon, separate from the others. It happens a little bit on 6.9.0.0, but not as harshly as on the beta version. Even when the layers are up, they will occasionally go down because they lose connection because of how quickly they are executing the command and how long the server is taking to respond. The persona ID error is back again:
`EXCEPTION-6900-FetchPlayerBattlelogInformation-BattlelogComm29: [Could not find persona ID for DasNyce]`
Thanks again

**Comment by ColColonCleaner** [comment]
Huh...that's very strange. I'll add a section of the script in the /uptime command to show how many player lists have been requested and received in the last 60 seconds. Hopefully i'll have time to do that tonight.

**Comment by ab9876** [comment]
Awesome, thanks. It seems to be better on this version and only currently plagues 2 servers instead of the 7 that it affected before.

**Comment by ColColonCleaner** [comment]
@ab9876 

I've updated the test version of AdKats to have logging of player listing triggers, receives, and successful completions. Triggers are how often the plugin is requesting a player list, receives are how often the plugin is receiving a player list from procon, successes are how often the plugin completes processing an inbound player list.

You will see debug messages in the plugin console if you enable the player listing debug. This is enabled and disabled by entering 7621 into the debug level setting. This setting is not persisted to the database, and will reset to disabled when the layer is rebooted.

**Comment by ColColonCleaner** [comment]
Please reopen if this issue returns.
