### ISSUE TITLE
Question: Ban management

### ISSUE THREAD

**Issue by mpoonuru** [AdKats/AdKats#950]
Hi @ColColonCleaner ,

I have a legit player who got Auto banned by Adkats. Could you please help me to understand it?
134	BF4	SnoupDawg	BanEnforcer	Enabled	5 minutes ago	Permanent	GUID	Hacking/Cheating - AutoTrigger - SnoupDawg

How to handle this? Sorry to bother you too much! 

Since it is locker only server, People are getting banned like this. Is there a way to reset the stats like every month or something? I am clue less here

**Comment by ColColonCleaner** [comment]
I need the full ban message, it will include a code and a bunch of numbers. Thank you.

**Comment by ColColonCleaner** [comment]
"Hacking/Cheating - AutoTrigger - SnoupDawg" is not an AdKats ban message by default.

**Comment by mpoonuru** [comment]
Hi Bro,

Where can I find the information?

**Comment by ColColonCleaner** [comment]
It's in the ban message. Try /unban playername from procon, you'll see the ban message for him (it won't unban without a confirmation).

**Comment by mpoonuru** [comment]
http://imgur.com/a/NGPJj

**Comment by ColColonCleaner** [comment]
That's not an AdKats anti-cheat ban.

**Comment by mpoonuru** [comment]
I don't have any other plugins for Anti-Cheat bro. Which one is banning?

**Comment by ColColonCleaner** [comment]
Wait, that ban is in procon, which means you aren't using the ban enforcer. So /unban won't work.

Anyway, every ban from the anti-cheat section in AdKats has a code appended to the end of it. Like this: [4-RPK12-25-52-21-155]

That code shows why the plugin banned them. Which version of AdKats are you on?

**Comment by mpoonuru** [comment]
Hi Bro,

I have AdKats - Advanced In-Game Admin - 6.9.0.0

**Comment by ColColonCleaner** [comment]
Please screenshot setting section A18.

**Comment by ColColonCleaner** [comment]
Wait...you edited that message with a ban enforcer kick reason. But the ban you showed is in procon, not in the database. The ban enforcer clears out that list when it's looking for new bans, there should be no bans left visible in your procon instance.

**Comment by mpoonuru** [comment]
http://imgur.com/a/y413E

**Comment by ColColonCleaner** [comment]
Yeah, this is not an AdKats ban. Something else banned this player.

**Comment by mpoonuru** [comment]
How to find that bro? Is it a legit ban? Or which system triggering this ban?

**Comment by ColColonCleaner** [comment]
Screenshot your other plugins.

**Comment by mpoonuru** [comment]
Here you go!
http://imgur.com/a/Edyr1

**Comment by ColColonCleaner** [comment]
I don't see any plugin that would cause it. My first thought was proconrulz but that plugin doesn't have access to battlelog data. I would suggest you unban this player and see what happens. Something is adding the player's ban to the server ban list, which wouldn't be happening if it was coming from AdKats, so something else is triggering this ban.

**Comment by ColColonCleaner** [comment]
Renamed the issue to a question as this isn't related to AdKats.

**Comment by mpoonuru** [comment]
Ah ok! Thanks bro!
