### ISSUE TITLE
Store player's persona IDs in the stat logger database

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#952]
Right now there is no storage of persona IDs, so they need to be fetched every single startup. This should help with boot times for the loadout enforcer and anticheat systems.

**Comment by Prophet731** [comment]
I do have something setup already for storing that information. You can check to see if the table already exists and if it does go ahead and use it otherwise create it.

```PHP
        // Creates the adkats battlelog players table if it doesn't exist
        if (! Schema::hasTable('adkats_battlelog_players')) {
            Schema::create('adkats_battlelog_players', function (Blueprint $table) {
                $table->engine = 'InnoDB';
                $table->integer('player_id')->unsigned()->primary();
                $table->bigInteger('persona_id')->unsigned()->index();
                $table->bigInteger('user_id')->unsigned()->index();
                $table->string('gravatar', 32)->nullable();
                $table->boolean('persona_banned')->default(false);
                $table->unique(['player_id', 'persona_id']);
                $table->foreign('player_id')->references('PlayerID')->on('tbl_playerdata')->onUpdate('cascade')->onDelete('cascade');
            });
        }
```

```SQL
CREATE TABLE `adkats_battlelog_players` (
  `player_id` int(10) unsigned NOT NULL,
  `persona_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `gravatar` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  `persona_banned` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`player_id`),
  UNIQUE KEY `adkats_battlelog_players_player_id_persona_id_unique` (`player_id`,`persona_id`),
  KEY `adkats_battlelog_players_persona_id_index` (`persona_id`),
  KEY `adkats_battlelog_players_user_id_index` (`user_id`),
  CONSTRAINT `adkats_battlelog_players_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `tbl_playerdata` (`PlayerID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

These files show are my battlelog libraries for the BFACP.

https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5/app/Libraries/Battlelog

**Comment by ColColonCleaner** [comment]
Ah, it has the adkats prefix, i'll just include that in the adkats setup script. I don't fetch userid gravatar or banned status for those though. If my system adds records to this table with just playerid/personaid will your system still function and fill in the rest?

**Comment by Prophet731** [comment]
The only fields required are `playerid`, `persona_id`, and `user_id` the rest can be blank. If you're going through the same method as me you should be able to grab their user id. Once an entry exists for that player my system no longer hits battlelog to get that information so it can't fetch it. It'll just use what's in the database.

https://github.com/Prophet731/BFAdminCP/blob/dev-laravel5/app/Libraries/Battlelog/BattlelogPlayer.php#L94

**Comment by ColColonCleaner** [comment]
I use regexes to find the persona IDs and am now using that to find the user IDs. Looks like the new user ID regex worked on the first try, for BF4 anyway, so I'm now using that table properly.
