### ISSUE TITLE
Can't disable instance check spamming

### ISSUE THREAD

**Issue by jakesullyneytiri** [AdKats/AdKats#955]
Hi,

when i view my bf4stats webpage chatlog i se tons of spamming messages of /AdKatsInstanceCheck L1MSIAZQIxoeNkFSAz0VFiEkLTBTM0UKJxcgRzcXWjY= 210 but i can't get it to stop :/ it keeps going on. I even made sure instance setting is sett to false but still spamming away.

How do i fix this??

/Thanks

**Comment by ColColonCleaner** [comment]
Do you have more than one server being monitored? The setting needs to be disabled on every instance of AdKats if you want to completely disable it.

The reason behind instance checking is to block more than one instance of AdKats running on the same server. AdKats listens for instance check messages that aren't its own and shuts down the shorter running instance.

**Comment by ColColonCleaner** [comment]
That being said, i haven't tested this setting in a while. I can run it through a test to make sure that setting still disables the checks.

**Comment by jakesullyneytiri** [comment]
yes i gone through every settings section and it says false on instance settings on all of them :/ I only got 1 bf4 server hosted by g-portal atm.

**Comment by jakesullyneytiri** [comment]
i found out by another user it was proconrulez logging chatlogSPAM thats why chat on web script spammed away xD

**Comment by ColColonCleaner** [comment]
@jakesullyneytiri It wasn't proconrulz, it was stat logger logging the server spam messages. However, those messages shouldn't have been in there in the first place to be logged. It is good however that you turned off logging of server spam since it will only clog up your chat logs. I'll still look into why it wasn't being disabled properly.

**Comment by jakesullyneytiri** [comment]
ah yes now when i re-checked again it was server like you said lmaoz i must of miss looked the name, but yeah i hope you fix that ting in adkat so when instance check setting is false it should be able to turn on then off when needed :)

**Comment by jakesullyneytiri** [comment]
wut? how where you able to be added to my reserved player slot? on my bf4 server???

**Comment by ColColonCleaner** [comment]
@jakesullyneytiri Please take a look at the last sentence in the main AdKats post. It's been this way for over a year.

https://forum.myrcon.com/showthread.php?6045-FREE-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-9-0-0

**Comment by jakesullyneytiri** [comment]
well i must of missed that then xD, still new to this stuff.

**Comment by ColColonCleaner** [comment]
I just confirmed that the setting is working as intended. I made the plugin post the instance check messages into the procon chat log and they were printed when the single instance setting was enabled, and were not printed when that setting was disabled.

**Comment by ColColonCleaner** [comment]
For this to be looked at further i will need access to your procon instance. Please re-open if that can be provided.
