### ISSUE TITLE
Adding Reserved Slot Whitelist to Discord Player Perks

### ISSUE THREAD

**Issue by jay7981** [AdKats/AdKats#957]
Am I correct in assuming that all i have to do is add the following code to the .cs file and restart the layer to have this work? 

`//Line:4386	
                
} else if (Regex.Match(strVariable, @"Discord Player Perks - Reserved Slot Whitelist").Success) {
                    Boolean DiscordPlayerPerksReservedSlotWhitelist = Boolean.Parse(strValue);
                    if (DiscordPlayerPerksReservedSlotWhitelist != _DiscordPlayerPerksReservedSlotWhitelist) {
                        if (_threadsReady && !_FeedMultiBalancerWhitelist && DiscordPlayerPerksReservedSlotWhitelist) {
                            Log.Error("'Discord Player Perks - Reserved Slot Whitelist' cannot be enabled when 'Feed MULTIBalancer Whitelist' is disabled.");
                            return;
                        }
                        _DiscordPlayerPerksReservedSlotWhitelist = DiscordPlayerPerksReservedSlotWhitelist;
                        if (_threadsReady) {
                            if (_DiscordPlayerPerksReservedSlotWhitelist) {
                                Log.Info("Discord Player perks now include Reserved Slot Whitelist.");
                            } else {
                                Log.Info("Discord Player perks no longer include Reserved Slot Whitelist.");
                            }
                            FetchAllAccess(true);
                        }
                        QueueSettingForUpload(new CPluginVariable(@"Discord Player Perks - Reserved Slot Whitelist", typeof(Boolean), _DiscordPlayerPerksReservedSlotWhitelist));
                    }
			
//Line 31991:
QueueSettingForUpload(new CPluginVariable(@"Discord Player Perks - Reserved Slot Whitelist", typeof(Boolean), _DiscordPlayerPerksReservedSlotWhitelist));

//Line 1649:
lstReturn.Add(new CPluginVariable(GetSettingSection(discordMonitorSection) + t + "Discord Player Perks - Reserved Slot Whitelist", typeof(Boolean), _DiscordPlayerPerksReservedSlotWhitelist));`

**Comment by ColColonCleaner** [comment]
That would only add the settings, none of the functionality.

I don't think this will work like you expect. You want it to add a reserved slot for people who join discord so they can skip the queue, however discord information only updates every 5 minutes, which means the players might have to wait up to 5 minutes to be detected by the plugin.

There is no way decrease this either, procon with .net 3.5 does not have access to websockets which are required to access data from discord at an accelerated rate.

I would suggest using the vip kick whitelist already available. This adds people already in the server to the reserved slot list so they aren't kicked by aggressive reserved slots.

**Comment by jay7981** [comment]
actually I'm OK with the 5 min delay, as most people are in there chit-chatting away for a while before playing anyways, not to mention if they are already in the server, and have to leave the server/get kicked for afk, punk-buster screws up, internet craps out ect ... they wont have to wait in queue to get back in. what part am i missing to ad the functionality?
