### ISSUE TITLE
AdKats external control from ProconRulz

### ISSUE THREAD

**Issue by surfacerunner** [AdKats/AdKats#958]
Hey ColColonCleaner

I would like to run autoadmin kill and kick commands through ProconRulz for bans of certain weapons onKill. That being said, I would like the kill/kick to be process through AdKats by using "external plugin API" as mentioned in AdKats documentations.

I haven't found any examples of ProconRulz integration with AdKats on Mycron forums or within the documentation.

Any pointers as to how would be greatly appreciated.

**Comment by ColColonCleaner** [comment]
For general support it's best to reach me on the myrcon forums, for some reason i seem to be missing notifications from here. Didn't notice this one until now.

You can set up proconrulz to issue admin say messages with commands in them. The only thing that's required is that the say messages be hidden, e.g. /kill player reason
