### ISSUE TITLE
Disabling "Join-Assigned To TeamKey" Messages in chat when using the team power balancer.

### ISSUE THREAD

**Issue by onczopek** [AdKats/AdKats#965]
Hello last update give me in chat many messages.

join assigned to us / ru and have many many this messages, very please tell me how disable only this messages.

Thank You Very Much

**Comment by ColColonCleaner** [comment]
@onczopek I don't have a setting to disable them just yet. However, i updated the latest version to only display those messages when testing. If you update right now you shouldn't see them anymore, at least until i add a setting to disable them individually. Cheers.

This is part of the ongoing work to develop an internal AdKats team balancer.

**Comment by ColColonCleaner** [comment]
Will close when the development of the toggle for these messages is in the product.

**Comment by ColColonCleaner** [comment]
For now these messages will be kept in the context of the debugsoldier. Since they happen so often i don't see a case outside of debugging where they wouldn't be considered spam.
