### ISSUE TITLE
Enhance SpamBot and server rules sections to accept map/mode specific messages and rules.

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#968]
The values would be at the front of the each message, like so:

XP0_Metro/ConquestLarge0/insert message here
or
Operation Metro 2014/Conquest Large/insert message here
or
some combination of map file name and map display name. The string would be split on / characters and the first two values in the resulting list would be compared against map/modes. This would avoid causing issues with people including slashes in their messages.

If a message only contains a map prefix, it will be shown for all rounds on that specific map. If it only contains a mode prefix it will be shown for all rounds on that mode. If it contains no specific prefix it will be shown on all rounds.

The only issues i foresee with doing this are the following. 

The spambot works on a queue system of messages. Each message is taken off the queue and shown to players in the server, then thrown to the back of the queue. This would have to be updated so that the queue automatically just throws messages not matching the map/mode to the back of the queue until it finds one that does. Then you run into the issue of what if there are no matching messages for the given map/mode, at what point should it quit looking? Likely search until the original length of the queue is exhausted.

The rules system and spambot store their values as single strings in the database. So the set of rules gets encoded into a single string then stored as the 'server rules' setting. This is an issue if we add map/mode options since the character limit on all AdKats settings is 2000 characters. The most simple solution to this would be to further increase the number of characters allowed in the AdKats settings, but that might not be the best approach. At this stage in the game i'm considering it though since building a system where settings can have multiple sections if they exceed the character limit does not seem appealing to design. Probably just increase the size to 5000 characters and call it done.

**Comment by Prophet731** [comment]
Why not just make a new table with the 4 fields? That would be easier to manage.

**Comment by ColColonCleaner** [comment]
A new table for the rules? Ehhhhhhhhhhhhhhhhhh.....
It kinda breaks the import system from other servers, where you can enter the server ID and import all the settings from that server. But i'm sure people can just copy the rules manually.

Rule Columns needed
server_id
rule_index
rule_text
map_key
mode_key

The .def files contain mappings of the map/mode keys to real values so i shouldn't need to store the display names in the database

**Comment by ColColonCleaner** [comment]
I'm not sure i'll go for splitting them up into a separate table though. The way the editor works in procon the entire thing is encoded anyway, people can't edit specific sections that is, it has to be updated as a blob. Encoding and pushing it as a setting has been working for ages so i think i'll just increase the column size and stick with that. This isn't as much of an issue since there is a finite amount of settings, unlike other tables where we don't know how many rows there are going to be.

**Comment by Prophet731** [comment]
Don't know how it'll break the import system, you would just need to make that modification in your logic. Reason I think it should be done is that it it would avoid the thing of changing the column size and it will allow almost unlimited rules to be created.

**Comment by ColColonCleaner** [comment]
Added initial changes for this. It appears to be functional for the rules perspective.

**Comment by ColColonCleaner** [comment]
Changes for the spambot side have been added. Rudimentary testing done.
