### ISSUE TITLE
Improve server crash detection to give distinction between blaze disconnect and actual server crash

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#975]
Just use the current uptime value of the server to distinguish between the blaze disconnect and the server crash. If the current server uptime has been reset (is now less than it previously was, or is near zero), and additionally all players have been lost between listing events, then it is an actual crash. If the players have just been lost without an uptime reset then it's a blaze crash.

Also change the 'ERROR' message for this to a warning, since this is not actually an error.

**Comment by ViltsuV** [comment]
I started hosting a server around 2 months ago and have this Blaze server process stall issue where the server is up but can't be seen on the server listing. Is this a new issue with BF3 or has it existed for a long time?

**Comment by ColColonCleaner** [comment]
@ViltsuV I'm not sure. I would suggest contacting your server host to figure that out, they are usually good at that. Who is your host?

**Comment by ViltsuV** [comment]
G-Portal. I did. Here's what they said:

> "Its a Blaze Server Authentication error that stalls the Server. That's why it disappears from the server list and needs a restart since the process stalls.
This unfortunately is nothing we can fix on our side, we forwarded the logs to DICE and EA and got no reply so far."

and a bit later when I asked if they had replied:

> "Response from DICE? Zero! We do not even expect any reply to be honest."

..which made me kind of sad. But I set up a restart policy, which has been kind of a band aid for this.

**Comment by ColColonCleaner** [comment]
@ViltsuV Oh yeah you're not gonna get anything from DICE/EA at this point. The project has been closed for ages now. I haven't kept updated with the happenings back in BF3 but we always had nightly restarts on our servers when they were empty.
I would suggest setting up the automatic restart systems in AdKats with a 5 hour uptime reboot. If the server is empty (or just has seeder players) and has more than 5 hours uptime it will reboot the server. Keeps it fresh and doesn't impact people in the server.

**Comment by ViltsuV** [comment]
Yeah, that's pretty much exactly what I did, though, 6 hours. Thanks for the plugin! Loving it! :+1:
