### ISSUE TITLE
Add setrole command.

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#980]
There are no role management in-game commands at this time. I might be able to add some soon though. 

Substring case-insensitive fetching of the matching role would be used.
The command would check if the target player was already assigned to a user, if so then that user's role would be changed to the given role, otherwise a new user would be created and assigned the given role then the player would be assigned to that user.
The same expiration entry as special player commands would be used, "perm" or a duration being required.
You would not be able to modify the role of a player that is higher power level than you currently are.
You would not be able to change your own role to one that is higher power level than you currently are.
You would not be able to assign a role to another player that is a higher power level than you currently are.

It would likely be:
/setrole perm playername rolename

The role ID wouldn't be used because people wouldn't easily remember those. Setting someone to 'guest', or 'vip', or 'tier 2' is easy to remember.

**Comment by Prophet731** [comment]
Permissions should be done outside of ingame commands. Otherwise that would become way more complicated to type out everytime. The B3 bot does it this way which I think would be better. Like so.

`!putgroup player god`

https://bigbrotherbot-user-documentation.readthedocs.io/en/latest/userguide/users_groups.html#user-management

**Comment by ColColonCleaner** [comment]
Ah I understand where you were going with that, thanks for the info :). In this case that duration would be translated into the expiration date on their user record, just like the expiration date on the special player entry.

**Comment by Hodor228** [comment]
Hi, what do you need to continue work on it?
