### ISSUE TITLE
Triage issue where records marked as unread are not being marked as read after action processing.

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#981]
This appears to have started around the 18th of feb, but I am unsure of the cause since there wasn't a release or patch around that day.

**Comment by wizard45** [comment]
To be clear, I have had this issued for almost a year now.  The info I sent you only showed the 18th of Feb, but that issue has been happening to me a lot longer than Feb 18th.

**Comment by ColColonCleaner** [comment]
@wizard45 Thank you for clarifying, that makes me less suspicious of a more recent patch causing the issue then.
