### ISSUE TITLE
Move image hosting and update all image links in documentation.

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#984]
Github appears to be cracking down on image hosting via the repo itself. The original images will remain on the repo but the links in the docs will be updated to host links. I'm not sure where they will be hosted yet.

**Comment by Prophet731** [comment]
I can throw them under the AdKats backup URL if you want.

**Comment by ColColonCleaner** [comment]
Nevermind. Appears to be a fluke. Pictures are working again.
