### ISSUE TITLE
2LOW2CARRYY

### ISSUE THREAD

**Issue by 2LOW2CARRYY** [AdKats/AdKats#986]
Hi I'm banned from the server For BTF3. I also see the reason that shows me

 Game disconnected: you were kicked by an admin. Stated reason: DPS Automatic Ban [4-AN94-53-11629-1369-21627] [perm][AutoAdmin]
 I did not share any piracy in my account. Is there a solution to this problem?
Best regards,

**Comment by ColColonCleaner** [comment]
This is not a place to dispute bans. But i'll try to help explain what's going on.

You have 11,629 kills with the an-94, with 21627 hits on enemies with it. You have a 12% headshot rate.
This means that your 25 damage weapon is dealing 52 damage per hit. According to your stats you are using a damage mod for double damage on that weapon.

http://battlelog.battlefield.com/bf3/servers/show/pc/9c000652-456d-496d-b9a1-211293b81eca/WBKS-Gaming-1-Metro-NoRules-3000T-NoobMagnet-AllWeapon/
This server is the one you frequent most often, and it's not a hardcore server, so those hits are against 100 HP players.

How do you explain that your weapon is dealing double the damage it normally should?

You'll need to contact the admins of the servers that banned you for this one.

**Comment by ColColonCleaner** [comment]
@2LOW2CARRYY has not responded in the last month. Closing issue.
