### ISSUE TITLE
Adkats LRT Have 2 bugs ?

### ISSUE THREAD

**Issue by onczopek** [AdKats/AdKats#988]
https://www.youtube.com/watch?v=iGLMLIMONlc

Hello is possible fix ?

**Comment by ColColonCleaner** [comment]
Bug 1: This is an issue with battlelog's data. It happens most often with people who have zero unlocks on a gun and have never changed the weapon's attachements.
Go here: battlelog.battlefield.com/bf4/loadout/CyckiSeUsmaz/1727559062/pc/#0/kits/0/1906761969/0
Notice it says you have the IR sight installed on that gun, even though you don't have it unlocked.
This is not really something i can fix without parsing unlocks too, and i'm not going to add that at this point.

Bug 2: EOD Bot has the weapon code 'Death', which is the same weapon code as the explosive barrels. If you want to allow kills by explosive barrels, you need to allow EOD bots.

**Comment by ColColonCleaner** [comment]
If someone complains about being killed incorrectly by the loadout enforcer you can issue the ignore loadout command from AdKats and it will ignore their loadout temporarily.

/iloadout playername
