### ISSUE TITLE
Confused about DPS ban

### ISSUE THREAD

**Issue by PnkBster** [AdKats/AdKats#989]
Not sure if this is the place to appeal but, I've been banned for DPS for some time now due with the m249. I have no clue why, i dont even use the gun. I've made a few kills with it and tried to fix the stats by using it more, but no luck. Id like to know what the reasoning is behind the ban, when i got banned and if i can get unbanned. Im not a cheater, I've always played this game legit, and never really had issue with it.

Here is my battelog weapon stats if it may help.
http://battlelog.battlefield.com/bf4/soldier/PnkBster/weapons/471749702/pc/ 

Hopefully this can be resolved because its legitimately ruining the game for me due to it banning me from almost every server.

On a side note, my account has been hacked by some Russian hacker from januari to march. I still have records of me trying to retrieve my account with the help of EA themselves. I suspect he might have done some unlegit stuff to my account.

**Comment by ColColonCleaner** [comment]
@PnkBster 

The bans issued by this script are individual to each server, so you would need to appeal that individually for servers you are already banned from.

That said, could you please provide me the full ban reason from one of the servers where you are banned? That reason contains some code numbers which will give insight into why the script banned you. This reason is posted at the bottom of the screen when joining via battlelog, in a red banner. It does not get displayed when joining servers via the in-game UI.

Looking at your stats at-a-glance I do not see anything wrong with your damage per shot on the M249, so i assume this ban was for a different reason.

**Comment by PnkBster** [comment]
@ColColonCleaner Thank you very much for your quick response and my apologies for my late one. This is the ban message i receive on every single one of the servers: Game disconnected: you were kicked by an admin. Stated reason: BANNED permanent FOR DPS Automatic Ban [4-M249-48-70-4-144] [AutoAdmin] 
I've searched on google what this meant and there is surprisingly little to find about this ban message. However from what i did find is that i somehow did more damage with the m249 then possible. Now like i said, im not a cheater, not by a long shot. So i have absolutely no clue how this might've occurred.

**Comment by ColColonCleaner** [comment]
The normal damage of the M249 is 24 per shot. 
You got 70 kills (with 4 headshots) and 144 hits. 
This means without headshots your weapon was dealing 48 damage per hit, double the damage it normally should.

This happened at some point between January 1, 2017 and April 12, 2018. However, i cannot find the reports associated with the 70 kills on record at that time. There are reports from a few weeks ago when you were attempting to fix this issue by using the weapon, but none from before then. 

This leads me to believe you have fallen victim to the crash-stats issue which occasionally happens to some players. DICE has an issue with posting stats to battlelog after a server crashes, it sends kill counts properly but hit counts rarely do not get sent. There is no battlereport associated with these incidences so it's basically a hole in the player's history where they gained kills but there is no record of it. This is a known issue that happens rarely.

Please contact the admins of the server where this ban happened and link them this thread. Have them unban you using the following command.

/acwhitelist perm PnkBster

Cheers.

**Comment by PnkBster** [comment]
Thank you very much for your response, i was about to go insane because i couldn't find a explanation. This treat will definitely help me get back on some servers. All i can say is: Just my luck again. This kinds of stuff always happens to me. 

Anyways, thanks for your time and help, its much appreciated. At least i know now my account probably wasn't messed up by the hacker that got into it during januari through march.

Cheers man.
