### ISSUE TITLE
Punishment System Not Working

### ISSUE THREAD

**Issue by Phatkez** [AdKats/AdKats#990]
Hi,

I've recently turned on punishment within AdKats, but it doesn't seem to want to actually add any infraction points to anyone that I use the punish command on.

Attached is a screenshot of my punishment settings, am I missing something here?

Thanks
![punish screen](https://user-images.githubusercontent.com/38111862/40333996-3832330e-5d53-11e8-9a47-e83f8571ed0d.PNG)

**Comment by ColColonCleaner** [comment]
Check your adkats_records_main table. Do you see two triggers on it? 
adkats_infraction_point_insert
and 
adkats_infraction_point_delete

**Comment by Phatkez** [comment]
Thanks for the quick response!

I seem to have no triggers.... on pretty much any of the tables (bit of a MySQL rookie)

![image](https://user-images.githubusercontent.com/38111862/40334635-ca41890e-5d56-11e8-8862-f547277e352b.png)

I assume that is not normal then...

**Comment by Phatkez** [comment]
Just copy of all of that and execute in a query? I get a syntax error on line 1

![image](https://user-images.githubusercontent.com/38111862/40334891-8ccd0ee8-5d58-11e8-815d-ac302494c01e.png)

**Comment by ColColonCleaner** [comment]
@Phatkez It pasted really badly so i deleted my comment. It looks like you executed it anyway.

Try this one, i made a gist.

https://gist.githubusercontent.com/ColColonCleaner/0814cdd650a4459b9e6ca2e97110bea5/raw/91a25302705ff2ba0913f2ca70476682868012c1/gistfile1.txt

**Comment by ColColonCleaner** [comment]
After that, you will need to do two more things before you are done.

delete from adkats_records_main where command_type in (9, 10);
truncate table adkats_infractions_global;
truncate table adkats_infractions_server;

**Comment by Phatkez** [comment]
That's fixed it! Infraction points are now working. Thanks your help and your patience.

**Comment by ColColonCleaner** [comment]
Make sure you did the 3 commands i added after the main triggers, otherwise rep will be messed up.
