### ISSUE TITLE
Adkats doesnt pull chat logs from database (Maybe?)

### ISSUE THREAD

**Issue by Phatkez** [AdKats/AdKats#991]
Hi Colon,

Back again trying to fix some shit.

Back before my time and before the release of the Adkats Control Panel, our Proconchat/stats logger plugin died (i dont know the details). Since the release of ACP, it has never logged chat logs or displayed live chat on the leaderboard page.

Our chat logs for the stat/chat plugin work fine, as we have are able to view them in the page made by Ty_ger07 (part of the plugin i believe).

Is there anything I can do to start debugging why AdKats/ACP doesnt pull these logs anymore?

Thanks in advance

**Comment by ColColonCleaner** [comment]
Try modifying the settings as shown below and let me know if that fixes your problem.

![cagv7av](https://user-images.githubusercontent.com/1903507/41823684-e75e9404-77c9-11e8-8788-0077ca14d56c.png)

**Comment by ColColonCleaner** [comment]
For the future, all settings have documentation and these particular ones can be found here:
https://github.com/AdKats/AdKats#a16-orchestration-settings
Cheers.
