### ISSUE TITLE
DPS Automatic Ban [4-CBJMS-35-152-10-431] [Auto Admin] #860

### ISSUE THREAD

**Issue by ZZINOZZ** [AdKats/AdKats#992]
Hello!
I just got banned by Adkat again for "DPS Hack" in this case i was using the JS2 PDW. The Admin of the Server "Burdel" unbanned me and 2 weeks later Adkat banned me for the same reason again. Now im unbanned again but not whitelisted because the Admin says ist all ok, and he wants to take a look. Adkat kicks me on every specific Server using it after 2 min for the stated reason. now i want to ask is there a way to remove it? Or what van be done. my bf4 http://battlelog.battlefield.com/bf4/soldier/X3G0/stats/1054002839/pc/

**Comment by ColColonCleaner** [comment]
AdKats issues DPS based bans when it senses a player dealing more damage than is possible with a weapon. In this case the CBJMS deals a maximum of 22.5 damage per hit without headshots. Your player's CBJMS is dealing 35 damage per hit, with 10 headshots over 152 killls. That is nearly 60% higher than the base damage, and is why the plugin banned your player.

There is an issue with battlelog statistics where it can post a battlereport for a player with hits but not associated kills, causing an invalid DPS ban, but that is very rare. Out of the millions of players who have been through servers running AdKats this has been confirmed on less than a dozen players and they have been whitelisted. If you examine your battlereports for ones having many hits but close to zero kills that could be the ticket to being whitelisted by an admin.

**Comment by ZZINOZZ** [comment]
The last 6 Months the Server lags alot (you cannot move, or you move in slow Motion in tanks for example). I jsut got unabnned 1 hour ago and am banned again DPS Automatic Ban [4-CBJMS-35-171-10-488] [AutoAdmin]. one Thing i can add i never Player the CBJMS in all those 4 yeas i have BF4 and just after i used it i got that ban.  Also i only Play on this Hardcore rush Server.

**Comment by ColColonCleaner** [comment]
Lag does not affect damage stats on the server side, either the shots hit or they don't. However, at this point late in the game I would suggest that the admin of your server whitelist you, especially if they are a hardcore server. Please link them this thread with my suggestions. Cheers.

**Comment by ZZINOZZ** [comment]
Thanks alot for helping and the quick Response. I played the gun on another Server and the DPS went to 26 or lower.
