### ISSUE TITLE
i have some questions

### ISSUE THREAD

**Issue by koujiangheng** [AdKats/AdKats#993]
i have some questions about the program and how gamespy works, i dont now how to contact with you ,would you mind tell me your email? or just write an email to me(-EMAIL-REDACTED-)
thx man!

**Comment by ColColonCleaner** [comment]
Please ask your questions here. I have edited your comment to remove your email address, bots scour the internet looking for them.

I'm not sure how gamespy applies to this plugin, please tell me more.

**Comment by koujiangheng** [comment]
oh thx for replying , thx very much, youknow when game start  some game will check for gamespy backend server status, the server will send back info to game,but which port should the game to receive? i do not know this.  can you send me some tutorial about gamespy protocol let me understand how it works,i really want to emulate gamespy server for crysis2,this is my dream since 2013 when game spy shutdown
________________________________
发件人: ColColonCleaner <notifications@github.com>
发送时间: 2018年9月21日 0:49
收件人: AdKats/AdKats
抄送: xiaojiuwo; Author
主题: Re: [AdKats/AdKats] i have some questions (#993)


Please ask your questions here. I have edited your comment to remove your email address, bots scour the internet looking for them.

I'm not sure how gamespy applies to this plugin, please tell me more.

―

**Comment by koujiangheng** [comment]
okay thx
