### ISSUE TITLE
Help with script

### ISSUE THREAD

**Issue by dangerORclose** [AdKats/AdKats#994]
Hey, sorry for making this issue, but I have been trying all day to get the script running by using older versions of XAMPP and stuff but I can't get it to work whatever I try. And I am very new in this stuff. If there anyone who can help me to get the script working? I am getting the following error when running the script. https://raw.githubusercontent.com/ColColonCleaner/AdKats/master/adkats.sql
`Error
SQL query:

REPLACE INTO `adkats_commands` VALUES(144, 'Invisible', 'player_challenge_complete', 'Log', 'Player Completed Challenge', 'challengecomplete', TRUE, 'Any')

DROP TABLE IF EXISTS `adkats_infractions_global`
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DROP TABLE IF EXISTS `adkats_infractions_global`' at line 3`

Thanks

**Comment by ColColonCleaner** [comment]
Please take a look at the installation FAQ, it has the solution to your problem.

https://github.com/AdKats/AdKats#faq

**Comment by ColColonCleaner** [comment]
I found the issue. Missing semicolon in the latest push.

https://raw.githubusercontent.com/AdKats/AdKats/master/adkats.sql

Try that updated version.

**Comment by dangerORclose** [comment]
Thanks works!
Resolved!

**Comment by ColColonCleaner** [comment]
Glad it worked. Cheers,
