### ISSUE TITLE
Setting to only handle specific command prefixes

### ISSUE THREAD

**Issue by ghost** [AdKats/AdKats#996]
Hey, we are using a diffrent plugin that has a function to YELL a message when we type for example @b.
Then in our case it yells Do not baserape... But we also want to have the ban command be !b name reason.
But everytime someone types @b in chat they get banned. Where can I select the prefix I want to use for this plugin?

**Comment by dangerBEclose** [comment]
Could you add a way that people can select the prefixes to be used please?

**Comment by ColColonCleaner** [comment]
There are too many things in the queue of requests for that to be added. There are dozens and I likely won't get to any of them at this point.

**Comment by dangerBEclose** [comment]
Okay, anyway this is the best plugin I have seen for battlefield 4 no complaints at all from me :)
But if you can add it would be nice. But I understand that you are buzzy. Thanks

**Comment by Ryckie** [comment]
Hello,

I am the OP of this request.
Is there any update on it?

**Comment by Hedius** [comment]
No. AdKats uses all prefixes.
I recommend using not the same commands for different plugins.

Just use ban and not b or modify your @b command.

**Comment by Ryckie** [comment]
> No. AdKats uses all prefixes.
> I recommend using not the same commands for different plugins.
> 
> Just use ban and not b or modify your @b command.
> 
> For example you can achieve the same with AdKats by using pre defined messages.
> And just doing /yell {msgID} then.

Are you aboe to give the id's a letter instead of a number?
