### ISSUE TITLE
Procon keeps rebooting every round

### ISSUE THREAD

**Issue by dangerBEclose** [AdKats/AdKats#997]
Hey,
Somehow Procon reboots every round.
This is only happening when AdKats is enabled, maybe that someone has faced this before and can help me out?
Thanks in advance!

**Comment by ColColonCleaner** [comment]
Which version of AdKats are you running?
Does this happen at the end of each round or when a round starts?
Do you keep plugin logs, and if so are there any errors thrown in the logs when the round ends before the reboot is fired?

**Comment by dangerBEclose** [comment]
AdKats - Advanced In-Game Admin - 7.5.0.0
PRoCon Chat, GUID, Stats and Map Logger - 1.0.0.3
Before the round ends it does this and each round.
We do not have logs to provide you some more info.
But feel free to join our ts server to talk look for dangerBEclose or buxshots.
ts.DeadFriendsGaming.com
- danger

**Comment by ColColonCleaner** [comment]
Closing as expired.
