### ISSUE TITLE
moving to other hosting

### ISSUE THREAD

**Issue by catalin78** [AdKats/AdKats#998]
Hello , 
I might be forced to change my 2 server bf4 server isp to another hosting . I would like to preserve the playerdata and banlist. Is it possible? 
Thanks ,
Catalin

**Comment by ColColonCleaner** [comment]
You need to make a backup of your mysql database so that you can restore it on your new host. Once you restore that database on your new host you'll need to update the previous server IP addresses with the new IPs of your newly hosted servers.

**Comment by catalin78** [comment]
where can these ip can be located? Is there a faq or guide for doing this? Thanks!

**Comment by ColColonCleaner** [comment]
tbl_server, it contains the IPs/ports of each server. Update each server to the IPs/ports of your new servers before turning the procon layers back on.

**Comment by catalin78** [comment]
Great ! Thanks for info ! On the new sql database fresh we need to run adkats tool to setup tables first? Ive also sent a donation for your project.

**Comment by ColColonCleaner** [comment]
@catalin78 Thanks for the donation.

No you don't need to run any scripts again, that's what restoring your previous backup is for. Running the scripts again would destroy all of your existing settings, so i would advise against doing that.

**Comment by catalin78** [comment]
i was refferring on the empty mysql database before restoring . some providers don't accept a full file at once so i might have to divide and split groups of tables. there are rather large ones . Thanks !

**Comment by ColColonCleaner** [comment]
Oh, that's odd. Do this instead then.
Back up just your table data, not including any triggers.
Back up your triggers.
Import the tables/data first, then import your triggers.
If you import both together you'll have issues with duplicated infraction points.

**Comment by catalin78** [comment]
okay that should be cool . i got a memory error from adkats after running a day or two , should i create another thread for it? Thanks for clearing this up!

**Comment by ColColonCleaner** [comment]
Closing as expired.
